const calculate=input=>{const tokens=String(input).match(/\d*\.?\d+|[()+\-*/%]/g)||[];let at=0;const expression=()=>{let value=term();while(tokens[at]==='+'||tokens[at]==='-'){const op=tokens[at++],next=term();value=op==='+'?value+next:value-next}return value};const term=()=>{let value=factor();while(['*','/','%'].includes(tokens[at])){const op=tokens[at++],next=factor();value=op==='*'?value*next:op==='/'?value/next:value%next}return value};const factor=()=>{if(tokens[at]==='-'){at++;return-factor()}if(tokens[at]==='+'){at++;return factor()}if(tokens[at]==='('){at++;const value=expression();if(tokens[at++]!==')')throw Error();return value}const value=Number(tokens[at++]);if(!Number.isFinite(value))throw Error();return value};const result=expression();if(at!==tokens.length||!Number.isFinite(result))throw Error();return result};
export default{
  id:'calculator',title:'calculator',icon:'calc',color:'grey',width:520,height:470,singleInstance:true,
  mount(root,{i18n}){
    let expression='',history=[],scientific=false;
    const numeric=()=>{try{return calculate(expression.replace(/×/g,'*').replace(/÷/g,'/').replace(/−/g,'-'))}catch{return Number(expression)||0}};
    const render=()=>{root.innerHTML=`<div class="system-app calculator-pro" tabindex="0"><header class="app-commandbar"><div class="segmented-control"><button data-calc-mode="standard" class="${scientific?'':'selected'}">${i18n.t('standard')}</button><button data-calc-mode="scientific" class="${scientific?'selected':''}">${i18n.t('scientific')}</button></div><div class="toolbar-spacer"></div><button data-calc-clear-history>${i18n.t('clear')}</button></header><div class="calculator-workspace"><aside><strong>${i18n.t('history')}</strong>${history.length?history.map(item=>`<button data-history="${item.result}"><small>${item.expression} =</small><b>${item.result}</b></button>`).join(''):`<p>${i18n.t('noHistory')}</p>`}</aside><section><output data-calc-display>${expression||'0'}</output>${scientific?`<div class="scientific-keys">${[['sin','sin'],['cos','cos'],['tan','tan'],['sqrt','√'],['square','x²'],['inverse','1/x']].map(([key,label])=>`<button data-unary="${key}">${label}</button>`).join('')}</div>`:''}<div class="calculator-keys">${['C','(',')','÷','7','8','9','×','4','5','6','−','1','2','3','+','0','.','%','='].map(key=>`<button data-key="${key}" class="${key==='='?'equals':''}">${key}</button>`).join('')}</div></section></div></div>`;bind();setTimeout(()=>root.querySelector('.calculator-pro')?.focus())};
    const apply=key=>{if(key==='C')expression='';else if(key==='⌫')expression=expression.slice(0,-1);else if(key==='='){const source=expression;try{expression=String(calculate(source.replace(/×/g,'*').replace(/÷/g,'/').replace(/−/g,'-')));history.unshift({expression:source,result:expression});history=history.slice(0,12)}catch{expression=i18n.t('calculatorError')}}else{if(expression===i18n.t('calculatorError'))expression='';expression+=key}render()};
    const unary=operation=>{const value=numeric(),functions={sin:Math.sin,cos:Math.cos,tan:Math.tan,sqrt:Math.sqrt,square:number=>number**2,inverse:number=>1/number};const result=functions[operation](value);if(Number.isFinite(result)){history.unshift({expression:`${operation}(${value})`,result:String(result)});expression=String(result)}else expression=i18n.t('calculatorError');render()};
    const bind=()=>{root.querySelectorAll('[data-key]').forEach(button=>button.onclick=()=>apply(button.dataset.key));root.querySelectorAll('[data-unary]').forEach(button=>button.onclick=()=>unary(button.dataset.unary));root.querySelectorAll('[data-calc-mode]').forEach(button=>button.onclick=()=>{scientific=button.dataset.calcMode==='scientific';render()});root.querySelectorAll('[data-history]').forEach(button=>button.onclick=()=>{expression=button.dataset.history;render()});root.querySelector('[data-calc-clear-history]').onclick=()=>{history=[];render()}};
    const keydown=event=>{const map={'*':'×','/':'÷','-':'−','Enter':'=','=':'=','Escape':'C','Backspace':'⌫'},key=map[event.key]||event.key;if(!/^[0-9.+()%]$/.test(key)&&!['×','÷','−','=','C','⌫'].includes(key))return;event.preventDefault();apply(key)};root.addEventListener('keydown',keydown);render();return()=>root.removeEventListener('keydown',keydown)
  }
};
