import {icon} from '../../icons.js';

export const clockMarkup=(i18n,{extraActions='',compact=false}={})=>`<div class="clock-pro ${compact?'activity-clock-pro':''}"><nav><header>${icon('clock',22)}<strong>${i18n.t('clock')}</strong>${extraActions}</header><button data-clock-view="world">${icon('globe',17)} ${i18n.t('worldClock')}</button><button data-clock-view="stopwatch">${icon('timer',17)} ${i18n.t('stopwatch')}</button><button data-clock-view="timer">${icon('clock',17)} ${i18n.t('timer')}</button></nav><section><div data-world-view><header><h2>${i18n.t('worldClock')}</h2><small>${i18n.t('localTime')}</small></header><div class="world-clock-primary"><div class="clock-digital" data-clock-now></div><small data-clock-date></small></div><div class="world-clock-list">${[['Local',Intl.DateTimeFormat().resolvedOptions().timeZone],['San Francisco','America/Los_Angeles'],['London','Europe/London'],['Tokyo','Asia/Tokyo']].map(([city,zone])=>`<article data-zone="${zone}"><span><strong>${city}</strong><small>${zone}</small></span><b></b></article>`).join('')}</div></div><div data-stopwatch-view hidden class="clock-focus"><h2>${i18n.t('stopwatch')}</h2><output data-stopwatch>00:00.00</output><div><button class="primary" data-stopwatch-toggle>${i18n.t('start')}</button><button data-stopwatch-reset>${i18n.t('reset')}</button></div></div><div data-timer-view hidden class="clock-focus"><h2>${i18n.t('timer')}</h2><output data-timer>05:00</output><label>${i18n.t('minutes')}<input data-timer-minutes type="number" min="1" max="180" value="5"></label><div><button class="primary" data-timer-toggle>${i18n.t('start')}</button><button data-timer-reset>${i18n.t('reset')}</button></div></div></section></div>`;

export const mountClockView=(root,i18n,{extraActions='',compact=false,bindExtra=()=>{},onContext=()=>{}}={})=>{
  let view='world',started=0,elapsed=0,running=false,timerSeconds=300,timerRemaining=300,timerRunning=false,timerStarted=0;
  root.innerHTML=clockMarkup(i18n,{extraActions,compact});
  const report=()=>onContext({kind:'clock-view',id:view,name:i18n.t(view==='world'?'worldClock':view),metadata:{running,elapsedMilliseconds:elapsed+(running?Date.now()-started:0),timerRunning,timerRemaining}});
  const switchView=next=>{view=next;['world','stopwatch','timer'].forEach(name=>{const panel=root.querySelector(`[data-${name}-view]`);if(panel)panel.hidden=view!==name});root.querySelectorAll('[data-clock-view]').forEach(button=>button.classList.toggle('selected',button.dataset.clockView===view));report()};
  const update=()=>{const now=new Date(),clock=root.querySelector('[data-clock-now]');if(!clock)return;clock.textContent=new Intl.DateTimeFormat(i18n.t('dateFormat'),{hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(now);root.querySelector('[data-clock-date]').textContent=new Intl.DateTimeFormat(i18n.t('dateFormat'),{dateStyle:'full'}).format(now);root.querySelectorAll('[data-zone]').forEach(row=>row.querySelector('b').textContent=new Intl.DateTimeFormat(i18n.t('dateFormat'),{timeZone:row.dataset.zone,hour:'2-digit',minute:'2-digit'}).format(now));const ms=elapsed+(running?Date.now()-started:0),minutes=Math.floor(ms/60000),seconds=Math.floor(ms%60000/1000),centis=Math.floor(ms%1000/10);root.querySelector('[data-stopwatch]').textContent=`${String(minutes).padStart(2,'0')}:${String(seconds).padStart(2,'0')}.${String(centis).padStart(2,'0')}`;const remaining=timerRunning?Math.max(0,timerRemaining-Math.floor((Date.now()-timerStarted)/1000)):timerRemaining;if(timerRunning&&remaining===0){timerRunning=false;timerRemaining=0;root.querySelector('[data-timer-toggle]').textContent=i18n.t('start')}root.querySelector('[data-timer]').textContent=`${String(Math.floor(remaining/60)).padStart(2,'0')}:${String(remaining%60).padStart(2,'0')}`};
  root.querySelectorAll('[data-clock-view]').forEach(button=>button.onclick=()=>switchView(button.dataset.clockView));
  root.querySelector('[data-stopwatch-toggle]').onclick=event=>{if(running){elapsed+=Date.now()-started;running=false}else{started=Date.now();running=true}event.currentTarget.textContent=i18n.t(running?'stop':'start');report()};
  root.querySelector('[data-stopwatch-reset]').onclick=()=>{elapsed=0;started=Date.now();update();report()};
  root.querySelector('[data-timer-minutes]').onchange=event=>{if(timerRunning)return;timerSeconds=Math.max(60,Number(event.target.value||5)*60);timerRemaining=timerSeconds;update()};
  root.querySelector('[data-timer-toggle]').onclick=event=>{if(timerRunning){timerRemaining=Math.max(0,timerRemaining-Math.floor((Date.now()-timerStarted)/1000));timerRunning=false}else{if(timerRemaining<=0)timerRemaining=timerSeconds;timerStarted=Date.now();timerRunning=true}event.currentTarget.textContent=i18n.t(timerRunning?'stop':'start');report()};
  root.querySelector('[data-timer-reset]').onclick=()=>{timerRunning=false;timerRemaining=timerSeconds;root.querySelector('[data-timer-toggle]').textContent=i18n.t('start');update();report()};
  bindExtra();switchView('world');update();const timer=setInterval(update,50);return()=>clearInterval(timer);
};
