import { AerisKernel } from '../kernel/AerisKernel.js';
import { SettingsService } from '../services/SettingsService.js';
import { I18nService } from '../services/I18nService.js';
import { DialogService } from '../services/DialogService.js';
import { V86Machine } from '../platform/v86/V86Machine.js';
import { GuestSystemService } from '../services/GuestSystemService.js';
import { AiAgentService } from '../services/AiAgentService.js';
import { SystemMetricsService } from '../services/SystemMetricsService.js';
import { SystemToolService } from '../services/SystemToolService.js';
import { UserDataService } from '../services/UserDataService.js';
import { ClipboardService } from '../services/ClipboardService.js';
import { WeatherService } from '../services/WeatherService.js';
import { NotificationService } from '../services/NotificationService.js';
import { MusicService } from '../services/MusicService.js';
import { AgentContextService } from '../services/AgentContextService.js';
import { AgentEntryService } from '../services/AgentEntryService.js';
import { AppRegistry } from '../apps/AppRegistry.js';
import { AppRuntimeService } from '../apps/AppRuntimeService.js';
import { counterPackage } from '../apps/extensions/counter/package.js';
import { AppStudioService } from '../services/AppStudioService.js';
import { SkillRegistryService } from '../services/SkillRegistryService.js';
import { createAppSkill } from '../skills/create-app/index.js';
import { DesktopShell } from '../shell/DesktopShell.js';
import files from '../apps/files/index.js';
import terminal from '../apps/terminal/index.js';
import machineApp from '../apps/machine/index.js';
import monitor from '../apps/monitor/index.js';
import notes from '../apps/notes/index.js';
import settingsApp from '../apps/settings/index.js';
import calculator from '../apps/calculator/index.js';
import calendar from '../apps/calendar/index.js';
import contacts from '../apps/contacts/index.js';
import reminders from '../apps/reminders/index.js';
import textedit from '../apps/textedit/index.js';
import clock from '../apps/clock/index.js';
import diskutility from '../apps/diskutility/index.js';
import preview from '../apps/preview/index.js';
import photos from '../apps/photos/index.js';
import trash from '../apps/trash/index.js';
import weatherApp from '../apps/weather/index.js';
import aiAssistant from '../apps/ai/index.js';
import musicApp from '../apps/music/index.js';
import { attachActivitySurfaces } from '../apps/activity/index.js';

export async function createSystem(root) {
  window.aeris={ phase:'starting' };
  const kernel=new AerisKernel();
  const settings=kernel.register('settings',new SettingsService());
  await settings.start();
  const i18n=kernel.register('i18n',new I18nService(settings));
  const dialog=kernel.register('dialog',new DialogService(root,i18n));
  const machine=kernel.register('machine',new V86Machine(settings));
  const system=kernel.register('system',new GuestSystemService(machine));
  const metrics=kernel.register('metrics',new SystemMetricsService(system,machine));
  const userdata=kernel.register('userdata',new UserDataService(system));
  const clipboard=kernel.register('clipboard',new ClipboardService());
  const weather=kernel.register('weather',new WeatherService(settings));
  const music=kernel.register('music',new MusicService(system));
  const registry=new AppRegistry();
  attachActivitySurfaces([aiAssistant,files,photos,calendar,weatherApp,contacts,reminders,notes,textedit,preview,calculator,clock,diskutility,terminal,machineApp,monitor,settingsApp,trash,musicApp]).forEach(app=>registry.register(app));
  const appRuntime=kernel.register('appRuntime',new AppRuntimeService({registry,storage:localStorage,bundledPackages:[counterPackage]}));
  await appRuntime.prepare();
  const appStudio=kernel.register('appStudio',new AppStudioService(appRuntime));
  const skillRegistry=kernel.register('skillRegistry',new SkillRegistryService({storage:localStorage,bundledSkills:[createAppSkill(appStudio)]}));
  const agentContext=kernel.register('agentContext',new AgentContextService(registry,i18n));
  const agentEntry=kernel.register('agentEntry',new AgentEntryService(agentContext));
  const notifications=kernel.register('notifications',new NotificationService(userdata,i18n));
  const tools=kernel.register('tools',new SystemToolService({userdata,system,settings,weather,metrics,machine,music,registry,i18n}));
  appStudio.setApprovalService(tools);
  const aiAgent=kernel.register('aiAgent',new AiAgentService(tools,localStorage,agentContext,skillRegistry));
  const context={kernel,settings,i18n,dialog,machine,system,metrics,tools,aiAgent,agentContext,agentEntry,userdata,clipboard,weather,music,notifications,registry,appRuntime,appStudio,skillRegistry};
  const shell=new DesktopShell(root,context,registry);context.shell=shell;shell.mount();
  window.aeris={kernel,services:kernel.services,apps:registry,shell};
  await kernel.boot();
  return window.aeris;
}
