import { FutureKernel } from '../kernel/FutureKernel.js';
import { SettingsService } from '../services/SettingsService.js';
import { ThemeRuntimeService } from '../services/ThemeRuntimeService.js';
import { builtinThemes } from '../themes/BuiltinThemes.js';
import { I18nService } from '../services/I18nService.js';
import { DialogService } from '../services/DialogService.js';
import { V86Machine } from '../platform/v86/V86Machine.js';
import { GuestSystemService } from '../services/GuestSystemService.js';
import { AiAgentService } from '../services/AiAgentService.js';
import { AgentRegistryService } from '../services/AgentRegistryService.js';
import { MultiAgentOrchestratorService } from '../services/MultiAgentOrchestratorService.js';
import { SystemMetricsService } from '../services/SystemMetricsService.js';
import { SystemToolService } from '../services/SystemToolService.js';
import { UserDataService } from '../services/UserDataService.js';
import { SystemEntityService } from '../entities/SystemEntityService.js';
import { createCalendarEntityProviders, createNotesEntityProvider, createRemindersEntityProvider } from '../entities/providers/ProductivityEntityProviders.js';
import { createFileEntityProviders } from '../entities/providers/FileEntityProvider.js';
import { createBrowserEntityProvider, createContactsEntityProvider, createMusicEntityProvider, createPhotosEntityProvider, createWeatherEntityProvider } from '../entities/providers/BuiltinEntityProviders.js';
import { ClipboardService } from '../services/ClipboardService.js';
import { WeatherService } from '../services/WeatherService.js';
import { NotificationService } from '../services/NotificationService.js';
import { AgentNotificationService } from '../services/AgentNotificationService.js';
import { SystemTaskService } from '../services/SystemTaskService.js';
import { AutomationService } from '../services/AutomationService.js';
import { OperationHistoryService } from '../services/OperationHistoryService.js';
import { MusicService } from '../services/MusicService.js';
import { BrowserService } from '../services/BrowserService.js';
import { BrowserAutomationService } from '../services/BrowserAutomationService.js';
import { AppInstallationService } from '../services/AppInstallationService.js';
import { FactoryResetService } from '../services/FactoryResetService.js';
import { AgentContextService } from '../services/AgentContextService.js';
import { AgentEntryService } from '../services/AgentEntryService.js';
import { AgentModeRegistryService } from '../services/AgentModeRegistryService.js';
import { AgentQueryService } from '../services/AgentQueryService.js';
import { AppRegistry } from '../apps/AppRegistry.js';
import { AppRuntimeService } from '../apps/AppRuntimeService.js';
import { WidgetRegistry } from '../widgets/WidgetRegistry.js';
import { WidgetRuntimeService } from '../widgets/WidgetRuntimeService.js';
import { builtinWidgets } from '../widgets/BuiltinWidgets.js';
import { WidgetStudioService } from '../services/WidgetStudioService.js';
import { counterPackage } from '../apps/extensions/counter/package.js';
import { AppStudioService } from '../services/AppStudioService.js';
import { SkillRegistryService } from '../services/SkillRegistryService.js';
import { SkillPackageStore } from '../services/SkillPackageStore.js';
import { PythonSkillRuntime } from '../services/PythonSkillRuntime.js';
import { SkillStudioService } from '../services/SkillStudioService.js';
import { createAppSkill } from '../skills/create-app/index.js';
import { createWidgetSkill } from '../skills/create-widget/index.js';
import { skillCreatorSkill } from '../skills/skill-creator/index.js';
import { ThemeStudioService } from '../services/ThemeStudioService.js';
import { createThemeSkill } from '../skills/create-theme/index.js';
import { DesktopShell } from '../shell/DesktopShell.js';
import files from '../apps/files/index.js';
import terminal from '../apps/terminal/index.js';
import machineApp from '../apps/machine/index.js';
import monitor from '../apps/monitor/index.js';
import notes from '../apps/notes/index.js';
import settingsApp from '../apps/settings/index.js';
import calculator from '../apps/calculator/index.js';
import calendar from '../apps/calendar/index.js';
import contacts from '../apps/contacts/index.js';
import reminders from '../apps/reminders/index.js';
import textedit from '../apps/textedit/index.js';
import clock from '../apps/clock/index.js';
import diskutility from '../apps/diskutility/index.js';
import preview from '../apps/preview/index.js';
import photos from '../apps/photos/index.js';
import trash from '../apps/trash/index.js';
import weatherApp from '../apps/weather/index.js';
import aiAssistant from '../apps/ai/index.js';
import musicApp from '../apps/music/index.js';
import browserApp from '../apps/browser/index.js';
import { attachActivitySurfaces } from '../apps/activity/index.js';
import { systemTaskCapability } from './SystemCapabilities.js';

export async function createSystem(root) {
  window.future={ phase:'starting' };
  const kernel=new FutureKernel();
  const settings=kernel.register('settings',new SettingsService());
  await settings.start();
  const themeRuntime=kernel.register('themeRuntime',new ThemeRuntimeService({settings,storage:localStorage,bundledThemes:builtinThemes}));
  await themeRuntime.prepare();
  const i18n=kernel.register('i18n',new I18nService(settings));
  const dialog=kernel.register('dialog',new DialogService(root,i18n));
  const machine=kernel.register('machine',new V86Machine(settings));
  const system=kernel.register('system',new GuestSystemService(machine));
  const metrics=kernel.register('metrics',new SystemMetricsService(system,machine));
  const userdata=kernel.register('userdata',new UserDataService(system));
  const entities=kernel.register('entities',new SystemEntityService());
  [...createCalendarEntityProviders(userdata),createNotesEntityProvider(userdata),createRemindersEntityProvider(userdata),...createFileEntityProviders(system)].forEach(provider=>entities.register(provider));
  const clipboard=kernel.register('clipboard',new ClipboardService());
  const weather=kernel.register('weather',new WeatherService(settings));
  const music=kernel.register('music',new MusicService(system));
  const browser=kernel.register('browser',new BrowserService({storage:localStorage}));
  const browserAutomation=kernel.register('browserAutomation',new BrowserAutomationService());
  [createContactsEntityProvider(userdata),createMusicEntityProvider(music),createBrowserEntityProvider(browser),createPhotosEntityProvider(system,userdata),createWeatherEntityProvider(weather)].forEach(provider=>entities.register(provider));
  const registry=new AppRegistry();
  const widgetRegistry=new WidgetRegistry();
  builtinWidgets.forEach(widget=>widgetRegistry.register(widget));
  attachActivitySurfaces([aiAssistant,files,photos,calendar,weatherApp,contacts,reminders,notes,textedit,preview,calculator,clock,diskutility,terminal,machineApp,monitor,settingsApp,trash,musicApp,browserApp]).forEach(app=>registry.register(app));
  registry.register(systemTaskCapability);
  const appRuntime=kernel.register('appRuntime',new AppRuntimeService({registry,storage:localStorage,bundledPackages:[counterPackage],themeRuntime}));
  await appRuntime.prepare();
  const appInstallation=kernel.register('appInstallation',new AppInstallationService({registry,appRuntime,userdata,settings,storage:localStorage}));
  await appInstallation.prepare();
  const widgetRuntime=kernel.register('widgetRuntime',new WidgetRuntimeService({registry:widgetRegistry,storage:localStorage,themeRuntime}));
  await widgetRuntime.prepare();
  const widgetStudio=kernel.register('widgetStudio',new WidgetStudioService(widgetRuntime));
  const appStudio=kernel.register('appStudio',new AppStudioService(appRuntime));
  const themeStudio=kernel.register('themeStudio',new ThemeStudioService(themeRuntime));
  const queryUser=kernel.register('queryUser',new AgentQueryService());
  const pythonSkillRuntime=kernel.register('pythonSkillRuntime',new PythonSkillRuntime());
  const skillRegistry=kernel.register('skillRegistry',new SkillRegistryService({storage:localStorage,packageStore:new SkillPackageStore(),pythonRuntime:pythonSkillRuntime,bundledSkills:[createAppSkill(appStudio,queryUser),createWidgetSkill(widgetStudio),createThemeSkill(themeStudio)]}));
  const skillStudio=kernel.register('skillStudio',new SkillStudioService(skillRegistry));skillRegistry.registerBundled(skillCreatorSkill(skillStudio));
  const agentContext=kernel.register('agentContext',new AgentContextService(registry,i18n));
  const agentModes=kernel.register('agentModes',new AgentModeRegistryService());
  const agentEntry=kernel.register('agentEntry',new AgentEntryService(agentContext));
  const notifications=kernel.register('notifications',new NotificationService(userdata,i18n));
  const operationHistoryService=new OperationHistoryService(localStorage),systemTaskService=new SystemTaskService(localStorage),automationService=new AutomationService({storage:localStorage,tasks:systemTaskService});
  const tools=kernel.register('tools',new SystemToolService({userdata,system,settings,themeRuntime,weather,metrics,machine,music,browser,browserAutomation,registry,i18n,entities,operationHistory:operationHistoryService,automations:automationService,systemTasks:systemTaskService}));
  skillRegistry.setApprovalService(tools);
  skillStudio.setApprovalService(tools);
  appStudio.setApprovalService(tools);
  widgetStudio.setApprovalService(tools);
  themeStudio.setApprovalService(tools);
  const agentRegistry=kernel.register('agentRegistry',new AgentRegistryService({storage:localStorage}));
  const multiAgent=kernel.register('multiAgent',new MultiAgentOrchestratorService({registry:agentRegistry,storage:localStorage,toolService:tools,skillRegistry}));
  const aiAgent=kernel.register('aiAgent',new AiAgentService(tools,localStorage,agentContext,skillRegistry,multiAgent,agentModes));
  const factoryReset=kernel.register('factoryReset',new FactoryResetService({machine,skillRegistry,browserAutomation}));
  const operationHistory=kernel.register('operationHistory',operationHistoryService);
  const systemTasks=kernel.register('systemTasks',systemTaskService);
  const automations=kernel.register('automations',automationService);
  systemTasks.setRunner(aiAgent);automations.setRunner(aiAgent);
  const agentNotifications=kernel.register('agentNotifications',new AgentNotificationService({notifications,aiAgent,tools,queryUser,i18n}));
  appInstallation.setRuntimeServices({ai:{clearData:async()=>{await aiAgent.clearData();systemTasks.clearData();operationHistory.clear();automations.clearData()}},music,weather,browser:{clearData:async()=>{browser.clearData();await browserAutomation.disconnect().catch(()=>{})}}});
  multiAgent.setCapabilitySources({isToolAppEnabled:appId=>aiAgent.isToolAppEnabled(appId)});
  multiAgent.setRunner(options=>aiAgent.runIsolatedAgent(options));
  const context={kernel,settings,themeRuntime,themeStudio,i18n,dialog,machine,factoryReset,system,metrics,entities,tools,aiAgent,agentNotifications,agentRegistry,multiAgent,agentContext,agentModes,agentEntry,queryUser,userdata,clipboard,weather,music,browser,browserAutomation,notifications,systemTasks,automations,operationHistory,registry,appRuntime,appInstallation,appStudio,skillRegistry,skillStudio,pythonSkillRuntime,widgetRegistry,widgetRuntime,widgetStudio};
  const shell=new DesktopShell(root,context,registry);context.shell=shell;shell.mount();
  window.future={kernel,services:kernel.services,apps:registry,widgets:widgetRegistry,entities,shell};
  await kernel.boot();
  return window.future;
}
