import { icon } from '../../icons.js';
const esc=value=>String(value).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/"/g,'&quot;');
export default{
  id:'contacts',title:'contacts',icon:'contacts',color:'aqua',width:900,height:590,singleInstance:true,
  mount(root,{userdata,dialog,i18n,kernel}){
    let contacts=[],selectedId=null,query='',group='all',pendingResultId='';
    const selected=()=>contacts.find(item=>item.id===selectedId)||null,save=()=>userdata.save('contacts',contacts,{source:'contacts-app'});
    const filtered=()=>contacts.filter(item=>(group!=='favorites'||item.favorite)&&`${item.name} ${item.email} ${item.phone}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>a.name.localeCompare(b.name));
    const collect=async current=>{const name=await dialog.prompt({title:i18n.t(current?'editContact':'newContact'),placeholder:i18n.t('fullName'),value:current?.name||'',validate:value=>value.trim()?'':i18n.t('invalidName')});if(!name)return null;const email=await dialog.prompt({title:i18n.t('email'),placeholder:'name@example.com',value:current?.email||''});if(email===null)return null;const phone=await dialog.prompt({title:i18n.t('phone'),placeholder:'+1 555 0100',value:current?.phone||''});if(phone===null)return null;return{name:name.trim(),email:email.trim(),phone:phone.trim()}};
    const render=()=>{const current=selected(),shown=filtered();root.innerHTML=`<div class="system-app contacts-pro"><aside class="contacts-groups"><header><strong>${i18n.t('contacts')}</strong><button data-contact-add aria-label="${i18n.t('newContact')}">${icon('plus',15)}</button></header><button data-contact-group="all" class="${group==='all'?'selected':''}">${icon('contacts',16)}<span>${i18n.t('allContacts')}</span><b>${contacts.length}</b></button><button data-contact-group="favorites" class="${group==='favorites'?'selected':''}">${icon('star',16)}<span>${i18n.t('favorites')}</span><b>${contacts.filter(item=>item.favorite).length}</b></button><footer><small>${i18n.t('localAccount')}</small><strong>${i18n.t("system")}</strong></footer></aside><aside class="contacts-list"><label class="app-search">${icon('search',14)}<input data-contact-search value="${esc(query)}" placeholder="${i18n.t('searchContacts')}"></label><div class="contacts-list-scroll">${shown.length?shown.map(contact=>`<button data-contact="${contact.id}" class="${current?.id===contact.id?'selected':''}"><span class="contact-avatar">${esc(contact.name.split(/\s+/).map(part=>part[0]).slice(0,2).join('').toUpperCase())}</span><strong>${esc(contact.name)}</strong><small>${esc(contact.email||contact.phone||i18n.t('noDetails'))}</small>${contact.favorite?`<i>${icon('star',11)}</i>`:''}</button>`).join(''):`<div class="empty-state">${i18n.t(query?'noSearchResults':'noContacts')}</div>`}</div></aside><section class="contact-canvas">${current?`<div class="contact-card"><button class="contact-favorite ${current.favorite?'active':''}" data-contact-favorite aria-label="${i18n.t('favorite')}">${icon('star',18)}</button><span class="contact-avatar large">${esc(current.name[0])}</span><h2>${esc(current.name)}</h2><small>${i18n.t('localContact')}</small><dl><dt>${i18n.t('email')}</dt><dd>${esc(current.email||i18n.t('noEmail'))}</dd><dt>${i18n.t('phone')}</dt><dd>${esc(current.phone||i18n.t('noPhone'))}</dd></dl><div class="contact-actions"><button data-contact-edit>${icon('textedit',15)} ${i18n.t('edit')}</button><button class="danger" data-contact-delete>${icon('delete',15)} ${i18n.t('delete')}</button></div></div>`:`<div class="empty-state">${icon('contacts',38)}<span>${i18n.t('selectContact')}</span></div>`}</section></div>`;
      root.querySelectorAll('[data-contact-group]').forEach(button=>button.onclick=()=>{group=button.dataset.contactGroup;selectedId=filtered()[0]?.id||null;render()});root.querySelector('[data-contact-search]').oninput=event=>{query=event.target.value;render();requestAnimationFrame(()=>{const input=root.querySelector('[data-contact-search]');input?.focus();input?.setSelectionRange(query.length,query.length)})};root.querySelectorAll('[data-contact]').forEach(button=>button.onclick=()=>{selectedId=button.dataset.contact;render()});root.querySelector('[data-contact-add]').onclick=async()=>{const values=await collect();if(!values)return;const contact={id:crypto.randomUUID(),favorite:false,...values};contacts.push(contact);selectedId=contact.id;await save();render()};root.querySelector('[data-contact-favorite]')?.addEventListener('click',async()=>{current.favorite=!current.favorite;await save();render()});root.querySelector('[data-contact-edit]')?.addEventListener('click',async()=>{const values=await collect(current);if(!values)return;Object.assign(current,values);await save();render()});root.querySelector('[data-contact-delete]')?.addEventListener('click',async()=>{const approved=await dialog.confirm({title:i18n.t('deleteContact'),message:i18n.t('deleteContactConfirm').replace('{name}',current.name),confirmLabel:i18n.t('delete'),danger:true});if(!approved)return;contacts=contacts.filter(item=>item.id!==current.id);selectedId=filtered()[0]?.id||null;await save();render()})};
    const revealResult=detail=>{if(detail?.appId!=='contacts')return;pendingResultId=detail.result?.id||'';const contact=contacts.find(item=>item.id===pendingResultId);if(!contact)return;group='all';query='';selectedId=contact.id;pendingResultId='';render()};
    const offData=kernel.bus.on('userdata:change',async detail=>{if(detail?.name!=='contacts'||detail.source==='contacts-app')return;const previousIds=new Set(contacts.map(item=>item.id));contacts=await userdata.load('contacts',[]);const added=contacts.find(item=>!previousIds.has(item.id));selectedId=added?.id||(contacts.some(item=>item.id===selectedId)?selectedId:contacts[0]?.id||null);render();if(pendingResultId)revealResult({appId:'contacts',result:{id:pendingResultId}})});
    const offResult=kernel.bus.on('agent:open-result',revealResult);
    userdata.load('contacts',[]).then(items=>{contacts=items;selectedId=contacts[0]?.id||null;render();if(pendingResultId)revealResult({appId:'contacts',result:{id:pendingResultId}})});render();return()=>{offData();offResult()};
  }
};
