import {icon} from '../../icons.js';
import {esc} from './shared.js';
import './browser.css';

const remoteUrl=url=>/^https?:/i.test(url)?url:'';
const host=url=>{try{return new URL(url).hostname.replace(/^www\./,'')}catch{return''}};
const dataUrl=image=>image?.data?`data:${image.mimeType||'image/jpeg'};base64,${image.data}`:'';

export const browserActivity={
  mount(root,context){
    const{app,browser,browserAutomation,i18n,kernel}=context;let view=null,loading=false,error='',destroyed=false,wheelTimer=0,wheelDelta=0;
    const active=()=>browser.active(),home=()=>!remoteUrl(active()?.url);
    const status=()=>browserAutomation.snapshot().state;
    const draw=()=>{const tab=active(),source=dataUrl(view?.screenshot);root.innerHTML=`<div class="activity-surface activity-browser-edge"><main><div class="activity-browser"><header><nav><button data-activity-browser-back title="${esc(i18n.t('back'))}">${icon('back',13)}</button><button data-activity-browser-reload title="${esc(i18n.t('refresh'))}">${icon('refresh',13)}</button></nav><form data-activity-browser-address><label>${icon(tab?.url?.startsWith('https:')?'lock':'globe',11)}<input value="${esc(home()?'':tab?.url||'')}" placeholder="${esc(i18n.t('browserAddressPlaceholder'))}" autocomplete="off" spellcheck="false"></label></form><button data-activity-full-app="browser" title="${esc(i18n.t('openInApp'))}">${icon('maximize',13)}</button></header><section class="${loading?'loading':''}" data-activity-browser-remote tabindex="0">${source?`<img src="${source}" alt="${esc(view?.title||tab?.title||i18n.t('webBrowser'))}" draggable="false">`:home()?`<div class="activity-browser-home"><span>${icon('browser',30)}</span><strong>${esc(i18n.t('browseTheWeb'))}</strong><small>${esc(i18n.t('browserAddressPlaceholder'))}</small></div>`:'<div class="activity-browser-loading"><i></i></div>'}</section>${error?`<div class="activity-browser-error" data-copyable>${icon('warning',13)}<span>${esc(error)}</span></div>`:''}<footer><span><i class="state-${esc(status())}"></i>${esc(host(view?.url||tab?.url)||i18n.t('newTab'))}</span><small>${esc(i18n.t('browserRemoteRuntime'))}</small></footer></div></main></div>`;bind()};
    const updateView=result=>{if(!result||destroyed)return;view={...view,...result,screenshot:result.screenshot||view?.screenshot};loading=false;error='';const image=root.querySelector('[data-activity-browser-remote] img'),source=dataUrl(view.screenshot);if(image&&source)image.src=source;else draw();root.querySelector('[data-activity-browser-remote]')?.classList.remove('loading');const tab=active();if(result.title&&tab&&result.title!==tab.title)browser.updateTitle(tab.id,result.title);if(remoteUrl(result.url)&&tab&&result.url!==tab.url)browser.navigate(result.url,{replace:true})};
    const navigate=async value=>{loading=true;error='';draw();try{const result=await browserAutomation.navigate(value);browser.navigate(result.url||value);updateView(result)}catch(reason){loading=false;error=reason.message;draw()}};
    const point=event=>{const rect=event.currentTarget.getBoundingClientRect(),viewport=view?.viewport||{width:1280,height:720};return{x:(event.clientX-rect.left)/rect.width*viewport.width,y:(event.clientY-rect.top)/rect.height*viewport.height}};
    const bind=()=>{root.querySelector('[data-activity-full-app]')?.addEventListener('click',()=>context.openFullApp(app.id));root.querySelector('[data-activity-browser-address]')?.addEventListener('submit',event=>{event.preventDefault();navigate(event.currentTarget.querySelector('input').value)});root.querySelector('[data-activity-browser-back]')?.addEventListener('click',async()=>{loading=true;draw();try{const result=await browserAutomation.history('back');browser.navigate(result.url||active().url,{replace:true});updateView(result)}catch(reason){loading=false;error=reason.message;draw()}});root.querySelector('[data-activity-browser-reload]')?.addEventListener('click',async()=>{loading=true;draw();try{updateView(await browserAutomation.reload())}catch(reason){loading=false;error=reason.message;draw()}});const remote=root.querySelector('[data-activity-browser-remote]');if(!remote||home())return;remote.onclick=event=>{remote.focus();browserAutomation.pointer({...point(event),type:'click'}).catch(reason=>{error=reason.message;draw()})};remote.onwheel=event=>{event.preventDefault();const position=point(event);wheelDelta+=event.deltaY;clearTimeout(wheelTimer);wheelTimer=setTimeout(()=>{browserAutomation.pointer({...position,type:'scroll',deltaY:wheelDelta}).catch(reason=>{error=reason.message;draw()});wheelDelta=0},55)};remote.onkeydown=event=>{if(event.metaKey||event.ctrlKey||event.altKey)return;const supported=event.key.length===1||['Enter','Backspace','Tab','Escape','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Delete'].includes(event.key);if(!supported)return;event.preventDefault();browserAutomation.key(event.key.length===1?{key:event.key,text:event.key}:{key:event.key}).catch(reason=>{error=reason.message;draw()})}};
    const streamOff=browserAutomation.subscribe(message=>{if(message.type==='frame'||message.type==='navigation')updateView(message)}),offBrowser=kernel.bus.on('browser:changed',()=>{if(!destroyed)draw()}),offAutomation=kernel.bus.on('browser-automation:changed',()=>{const indicator=root.querySelector('.activity-browser footer i');if(indicator)indicator.className=`state-${status()}`});
    draw();if(!home()){loading=true;browserAutomation.view().then(updateView).catch(reason=>{loading=false;error=reason.message;draw()})}
    return()=>{destroyed=true;clearTimeout(wheelTimer);streamOff();offBrowser();offAutomation()};
  }
};
