import { icon } from '../../icons.js';
import { appShell,bindFullApp,empty,esc,fullAppButton } from './shared.js';

export const filesActivity={
  mount(root,context,target={}){const{app,system,i18n,kernel,dialog,shell}=context;let path=target.path||target.params?.path||target.result?.path||'/home/aeris',items=[],loading=true,error='';if(/\.[^/]+$/.test(path))path=path.split('/').slice(0,-1).join('/')||'/home/aeris';
    const draw=()=>{root.innerHTML=appShell(app,context,`<div class="activity-path"><button data-file-up ${path==='/home/aeris'?'disabled':''}>${icon('back',13)}</button><code>${esc(path)}</code><button data-file-refresh>${icon('refresh',13)}</button></div><div class="activity-file-list">${loading?`<div class="activity-loading"><i></i>${esc(i18n.t('loading'))}</div>`:error?empty('warning',error):items.length?items.slice(0,80).map(item=>`<button data-file-name="${esc(item.name)}" data-file-type="${esc(item.type)}"><span>${icon(item.type==='directory'?'folder':'document',18)}</span><span><strong>${esc(item.name)}</strong><small>${esc(item.type==='directory'?i18n.t('folder'):`${item.size||0} B`)}</small></span>${icon('chevron',11)}</button>`).join(''):empty('folder',i18n.t('emptyDirectory'))}</div><footer><button data-file-new-folder>${icon('plus',13)} ${esc(i18n.t('newFolder'))}</button></footer>`,fullAppButton(app.id,i18n));bind()};
    const refresh=async()=>{loading=true;error='';draw();try{items=await system.list(path,{fresh:true,priority:true,timeout:20000})}catch(reason){error=reason.message}finally{loading=false;draw()}};
    const bind=()=>{bindFullApp(root,app.id,{...context,openFullApp:()=>context.openFullApp(app.id,path)});root.querySelector('[data-file-refresh]')?.addEventListener('click',refresh);root.querySelector('[data-file-up]')?.addEventListener('click',()=>{path=path.split('/').slice(0,-1).join('/')||'/home/aeris';refresh()});root.querySelectorAll('[data-file-name]').forEach(button=>button.onclick=()=>{const next=`${path.replace(/\/$/,'')}/${button.dataset.fileName}`;if(button.dataset.fileType==='directory'){path=next;refresh()}else shell.open(/\.(png|jpe?g|gif|webp|svg|pdf)$/i.test(next)?'preview':'textedit',next)});root.querySelector('[data-file-new-folder]')?.addEventListener('click',async()=>{const name=await dialog.prompt({title:i18n.t('newFolder'),placeholder:i18n.t('folderName')});if(!name||name.includes('/'))return;await system.mkdir(`${path.replace(/\/$/,'')}/${name}`,{priority:true});refresh()})};
    const off=kernel.bus.on('filesystem:changed',detail=>{if(detail?.path===path)refresh()});if(system.ready)refresh();else{loading=false;error=i18n.t('startMachine');draw()}return()=>off()}
};

export const photosActivity={
  mount(root,context){const{app,system,i18n,kernel,shell}=context;let items=[],selected=0,error='';const path='/home/aeris/Pictures';const images=()=>items.filter(item=>/\.(png|jpe?g|gif|webp|svg)$/i.test(item.name));const draw=()=>{const list=images(),item=list[selected]||null;root.innerHTML=appShell(app,context,`<div class="activity-photo-stage">${item?`<span>${icon('image',44)}</span><strong>${esc(item.name)}</strong><small>${esc(`${item.size||0} B`)}</small><button data-photo-open>${esc(i18n.t('open'))}</button>`:empty(error?'warning':'pictures',error||i18n.t('noPhotos'))}</div>${list.length?`<footer><button data-photo-prev ${selected<=0?'disabled':''}>${icon('back',13)}</button><span>${selected+1} / ${list.length}</span><button data-photo-next ${selected>=list.length-1?'disabled':''}>${icon('chevron',13)}</button></footer>`:''}`,fullAppButton(app.id,i18n));bindFullApp(root,app.id,context);root.querySelector('[data-photo-prev]')?.addEventListener('click',()=>{selected=Math.max(0,selected-1);draw()});root.querySelector('[data-photo-next]')?.addEventListener('click',()=>{selected=Math.min(list.length-1,selected+1);draw()});root.querySelector('[data-photo-open]')?.addEventListener('click',()=>shell.open('preview',`${path}/${item.name}`))};const load=async()=>{try{items=await system.list(path,{fresh:true,priority:true});selected=Math.min(selected,Math.max(0,images().length-1));error=''}catch(reason){error=reason.message}draw()};const off=kernel.bus.on('filesystem:changed',detail=>{if(detail?.path===path)load()});if(system.ready)load();else{error=i18n.t('startMachine');draw()}return()=>off()}
};

export const trashActivity={
  mount(root,context){const{app,system,i18n,kernel}=context,path='/home/aeris/.local/share/Trash/files';let items=[],loading=true,error='';const draw=()=>{root.innerHTML=appShell(app,context,`<div class="activity-file-list">${loading?`<div class="activity-loading"><i></i>${esc(i18n.t('loading'))}</div>`:error?empty('warning',error):items.length?items.map(item=>`<article><span>${icon(item.type==='directory'?'folder':'document',17)}</span><span><strong>${esc(item.name)}</strong><small>${esc(item.type)}</small></span></article>`).join(''):empty('delete',i18n.t('trashIsEmpty'),i18n.t('trashEmptyCopy'))}</div>`,fullAppButton(app.id,i18n));bindFullApp(root,app.id,context)};const load=async()=>{loading=true;draw();try{items=await system.list(path,{fresh:true,priority:true});error=''}catch(reason){error=reason.message}finally{loading=false;draw()}};const off=kernel.bus.on('filesystem:changed',detail=>{if(detail?.path===path)load()});if(system.ready)load();else{loading=false;error=i18n.t('startMachine');draw()}return()=>off()}
};

export const documentActivity={
  mount(root,context,target={}){const{app,system,i18n,kernel}=context;let path=target.path||target.params?.path||target.result?.path||'',content='',loading=false,error='';const editable=app.id==='textedit';
    const draw=()=>{root.innerHTML=appShell(app,context,`<div class="activity-document">${path?`<code>${esc(path)}</code>${loading?`<div class="activity-loading"><i></i>${esc(i18n.t('opening'))}</div>`:error?empty('warning',error):editable?`<textarea data-document-content>${esc(content)}</textarea>`:`<pre>${esc(content)}</pre>`}`:empty(app.icon,i18n.t('noFileSelected'))}</div>${editable&&path?`<footer><button data-document-save>${icon('check',13)} ${esc(i18n.t('save'))}</button></footer>`:''}`,fullAppButton(app.id,i18n));bindFullApp(root,app.id,{...context,openFullApp:()=>context.openFullApp(app.id,path)});root.querySelector('[data-document-save]')?.addEventListener('click',async()=>{content=root.querySelector('[data-document-content]').value;await system.writeChunked(path,content,{priority:true})})};const load=async()=>{if(!path)return draw();loading=true;draw();try{content=await system.read(path,{priority:true});error=''}catch(reason){error=reason.message}finally{loading=false;draw()}};const off=kernel.bus.on('filesystem:changed',detail=>{if(detail?.path===path)load()});if(system.ready)load();else{error=i18n.t('startMachine');draw()}return()=>off()}
};
