import {icon} from '../../icons.js';
import {esc,bindFullApp} from './shared.js';

const time=value=>{const seconds=Math.max(0,Number(value)||0);return`${Math.floor(seconds/60)}:${String(Math.floor(seconds%60)).padStart(2,'0')}`};

export const musicActivity={
  mount(root,context){
    const{app,music,i18n,kernel}=context;
    let category='all';
    const draw=()=>{const state=music.snapshot(),current=state.current,categories=[{id:'all',label:i18n.t('allSongs')},...state.categories.map(name=>({id:name,label:name}))],tracks=state.tracks.filter(track=>category==='all'?track.category==='Library':track.category===category);if(!categories.some(item=>item.id===category))category='all';root.innerHTML=`<div class="activity-surface activity-music-edge"><main><div class="activity-music ${state.playing?'is-playing':''}"><div class="activity-music-ambient"></div><header><span>${icon('music',16)}</span><strong>${esc(i18n.t('music'))}</strong><button data-activity-full-app="music">${icon('maximize',13)}</button></header><div class="activity-music-body"><aside><div>${tracks.length?tracks.map(track=>`<button data-activity-music-track="${esc(track.id)}" class="${current?.id===track.id?'selected':''}"><span>${current?.id===track.id&&state.playing?icon('volume',11):icon('music',11)}</span><span><strong>${esc(track.title)}</strong><small>${esc(track.artist)}</small></span></button>`).join(''):`<p>${esc(i18n.t('noMusic'))}</p>`}</div><label>${icon('folder',12)}<select data-activity-music-category>${categories.map(item=>`<option value="${esc(item.id)}" ${item.id===category?'selected':''}>${esc(item.label)}</option>`).join('')}</select>${icon('chevron',10)}</label></aside><section><div class="activity-music-record"><i></i><b>${icon('music',35)}</b></div><small>${esc(current?.category==='Library'?i18n.t('allSongs'):current?.category||i18n.t('localMusic'))}</small><h2>${esc(current?.title||i18n.t('chooseSong'))}</h2><p>${esc(current?.artist||i18n.t('musicEmptyCopy'))}</p><input data-activity-music-seek type="range" min="0" max="${state.duration||1}" step=".1" value="${state.currentTime}"><div class="activity-music-time"><time>${time(state.currentTime)}</time><time>${time(state.duration)}</time></div><nav><div class="activity-music-volume"><button title="${i18n.t('volume')}">${icon('volume',15)}</button><span><input data-activity-music-volume type="range" min="0" max="1" step=".01" value="${state.volume}"></span></div><button data-activity-music-shuffle class="${state.shuffle?'active':''}" title="${i18n.t('shuffle')}">${icon('shuffle',15)}</button><button data-activity-music-previous>${icon('previous',18)}</button><button class="primary" data-activity-music-toggle ${!current&&!state.tracks.length?'disabled':''}>${icon(state.playing?'pause':'play',22)}</button><button data-activity-music-next>${icon('next',18)}</button><button data-activity-music-repeat class="${state.repeat!=='off'?'active':''}" title="${i18n.t('repeat')}">${icon('repeat',15)}${state.repeat==='one'?'<b>1</b>':''}</button></nav></section></div><footer><span>${tracks.length} ${esc(i18n.t('songs'))}</span><button data-activity-music-library>${esc(i18n.t('openMusicFolder'))}</button></footer></div></main></div>`;bind()};
    const bind=()=>{bindFullApp(root,app.id,context);root.querySelector('[data-activity-music-category]')?.addEventListener('change',event=>{category=event.target.value;draw()});root.querySelectorAll('[data-activity-music-track]').forEach(button=>button.onclick=()=>music.play(button.dataset.activityMusicTrack).catch(()=>{}));root.querySelector('[data-activity-music-toggle]')?.addEventListener('click',()=>music.toggle());root.querySelector('[data-activity-music-next]')?.addEventListener('click',()=>music.next());root.querySelector('[data-activity-music-previous]')?.addEventListener('click',()=>music.previous());root.querySelector('[data-activity-music-shuffle]')?.addEventListener('click',()=>music.toggleShuffle());root.querySelector('[data-activity-music-repeat]')?.addEventListener('click',()=>music.cycleRepeat());root.querySelector('[data-activity-music-seek]')?.addEventListener('input',event=>music.seek(event.target.value));root.querySelector('[data-activity-music-volume]')?.addEventListener('input',event=>music.setVolume(event.target.value));root.querySelector('[data-activity-music-library]')?.addEventListener('click',()=>context.openFullApp(app.id))};
    const off=kernel.bus.on('music:changed',draw),offTime=kernel.bus.on('music:time',state=>{const seek=root.querySelector('[data-activity-music-seek]');if(seek)seek.value=state.currentTime;const first=root.querySelector('.activity-music-time time');if(first)first.textContent=time(state.currentTime)}),offVolume=kernel.bus.on('music:volume',state=>{const volume=root.querySelector('[data-activity-music-volume]');if(volume)volume.value=state.volume});draw();return()=>{off();offTime();offVolume()};
  }
};
