import { icon } from '../../icons.js';
import { createEvent,dateKey,migrate as migrateCalendar,moveEvent,parseLocal } from '../calendar/model.js';
import { eventEditor,readEventForm } from '../calendar/editor.js';
import { monthView } from '../calendar/views.js';
import { holidaysForYear } from '../calendar/holidays.js';
import { appShell,bindFullApp,empty,esc,fullAppButton } from './shared.js';

export const calendarActivity={
  mount(root,context,target={}){
    const {app,userdata,i18n,kernel,dialog}=context;
    const initial=target.date||target.params?.date||target.result?.start?.slice?.(0,10)||dateKey(new Date());
    let state=migrateCalendar(null),selected=initial,cursor=parseLocal(`${initial}T12:00`),editing=null,draggedId='';
    const save=()=>userdata.save('calendar',state,{source:'calendar-activity'});
    const holidayEvents=()=>[-1,0,1].flatMap(offset=>holidaysForYear(cursor.getFullYear()+offset,i18n.settings.get('region'),i18n.locale));
    const displayedEvents=()=>[...state.events,...holidayEvents()];
    const eventFor=id=>displayedEvents().find(item=>item.id===id);
    const defaultCalendar=()=>state.calendars.find(item=>!item.readOnly&&item.visible!==false)||state.calendars.find(item=>!item.readOnly);
    const title=()=>new Intl.DateTimeFormat(i18n.t('dateFormat'),{month:'long',year:'numeric'}).format(cursor);
    const draw=()=>{root.innerHTML=`<div class="activity-surface activity-calendar activity-calendar-edge"><main><div class="calendar-pro activity-calendar-pro"><div class="calendar-toolbar"><div class="calendar-nav"><button data-calendar-shift="-1" aria-label="${esc(i18n.t('back'))}">${icon('back',13)}</button><button data-calendar-today>${esc(i18n.t('today'))}</button><button data-calendar-shift="1" aria-label="${esc(i18n.t('forward'))}">${icon('chevron',13)}</button></div><h1>${esc(title())}</h1><div class="activity-calendar-actions"><button data-calendar-add class="calendar-new-event" aria-label="${esc(i18n.t('newEvent'))}">${icon('plus',13)}</button>${fullAppButton(app.id,i18n)}</div></div><main class="calendar-content"><div class="activity-calendar-month">${monthView(cursor,displayedEvents(),state.calendars,i18n,selected)}</div></main></div></main></div>`;bind();if(editing)showEditor(editing)};
    const openEditor=event=>{if(!event||event.readOnly)return;editing={...event,persisted:state.events.some(item=>item.id===event.id)};showEditor(editing)};
    const addEvent=()=>{const start=parseLocal(`${selected}T09:00`);openEditor(createEvent(start,defaultCalendar()?.id||'personal'))};
    const showEditor=event=>{root.querySelector('.calendar-editor-layer')?.remove();root.querySelector('.activity-surface')?.insertAdjacentHTML('beforeend',eventEditor(event,state.calendars,i18n));const layer=root.querySelector('.calendar-editor-layer'),form=layer?.querySelector('[data-event-form]');if(!layer||!form)return;const allDay=form.elements.allDay,syncAllDay=()=>{form.elements.startTime.disabled=allDay.checked;form.elements.endTime.disabled=allDay.checked;form.closest('.calendar-quick-card').classList.toggle('is-all-day',allDay.checked)};allDay.onchange=syncAllDay;syncAllDay();const close=()=>{editing=null;layer.classList.add('closing');setTimeout(()=>layer.remove(),120)};layer.querySelectorAll('[data-editor-cancel]').forEach(button=>button.onclick=close);const commit=async()=>{const updated=readEventForm(form,event);if(!updated.title)return form.elements.title.focus();const current=state.events.find(item=>item.id===updated.id);if(current)Object.assign(current,updated);else state.events.push(updated);editing=null;await save();draw()};form.onsubmit=submit=>{submit.preventDefault();commit()};layer.querySelector('[data-editor-save]').onclick=commit;layer.querySelector('[data-editor-delete]')?.addEventListener('click',async()=>{if(!await dialog.confirm({title:i18n.t('deleteEvent'),message:i18n.t('deleteEventConfirm'),confirmLabel:i18n.t('delete'),danger:true}))return;state.events=state.events.filter(item=>item.id!==event.id);editing=null;await save();draw()});requestAnimationFrame(()=>form.elements.title.focus())};
    const bind=()=>{bindFullApp(root,app.id,context);root.querySelectorAll('[data-calendar-shift]').forEach(button=>button.onclick=()=>{cursor=new Date(cursor.getFullYear(),cursor.getMonth()+Number(button.dataset.calendarShift),1);selected=dateKey(cursor);draw()});root.querySelector('[data-calendar-today]').onclick=()=>{cursor=new Date();selected=dateKey(cursor);draw()};root.querySelector('[data-calendar-add]').onclick=addEvent;root.querySelectorAll('[data-select-date]').forEach(button=>button.onclick=()=>{selected=button.dataset.selectDate;const date=parseLocal(`${selected}T12:00`);if(date.getMonth()!==cursor.getMonth()){cursor=date;draw()}else root.querySelectorAll('.calendar-month-day').forEach(day=>day.classList.toggle('selected',day.dataset.calendarDate===selected))});root.querySelectorAll('[data-calendar-date]').forEach(day=>day.ondblclick=event=>{if(event.target.closest('[data-event]'))return;selected=day.dataset.calendarDate;addEvent()});root.querySelectorAll('[data-event]').forEach(button=>{button.onclick=event=>{event.stopPropagation();openEditor(eventFor(button.dataset.event))};button.ondragstart=()=>{draggedId=button.dataset.event}});root.querySelectorAll('[data-drop-date]').forEach(day=>{day.ondragover=event=>{event.preventDefault();day.classList.add('drag-over')};day.ondragleave=()=>day.classList.remove('drag-over');day.ondrop=async event=>{event.preventDefault();day.classList.remove('drag-over');const item=state.events.find(value=>value.id===draggedId);if(!item)return;moveEvent(item,day.dataset.dropDate);draggedId='';selected=day.dataset.dropDate;await save();draw()}})};
    const off=kernel.bus.on('userdata:change',async detail=>{if(detail?.name!=='calendar'||detail.source==='calendar-activity'){return}state=migrateCalendar(await userdata.load('calendar',null));draw()});userdata.load('calendar',null).then(value=>{state=migrateCalendar(value);draw()});draw();return()=>off();
  }
};

export const remindersActivity={
  mount(root,context){const{app,userdata,i18n,kernel,dialog}=context;let items=[];const today=dateKey(new Date());const shown=()=>items.filter(item=>!item.done&&(!item.due||item.due>=today)).sort((a,b)=>(a.due||'9999').localeCompare(b.due||'9999'));
    const draw=()=>{const values=shown();root.innerHTML=appShell(app,context,`<div class="activity-list">${values.length?values.slice(0,30).map(item=>`<label><input type="checkbox" data-reminder-done="${esc(item.id)}"><span><strong>${esc(item.title)}</strong><small>${esc(item.due?[item.due,item.dueTime].filter(Boolean).join(' '):i18n.t('noDueDate'))}</small></span>${item.priority?'<b>!</b>':''}</label>`).join(''):empty('reminder',i18n.t('noReminders'))}</div><footer><button data-reminder-add>${icon('plus',13)} ${esc(i18n.t('newReminder'))}</button></footer>`,fullAppButton(app.id,i18n));bind()};
    const save=()=>userdata.save('reminders',items,{source:'reminders-activity'});const bind=()=>{bindFullApp(root,app.id,context);root.querySelectorAll('[data-reminder-done]').forEach(input=>input.onchange=async()=>{const item=items.find(value=>value.id===input.dataset.reminderDone);if(item){item.done=true;await save();draw()}});root.querySelector('[data-reminder-add]')?.addEventListener('click',async()=>{const title=await dialog.prompt({title:i18n.t('newReminder'),placeholder:i18n.t('reminderTitle')});if(!title)return;items.unshift({id:crypto.randomUUID(),title,done:false,due:'',dueTime:'',notify:false,priority:false,createdAt:Date.now()});await save();draw()})};
    const off=kernel.bus.on('userdata:change',async detail=>{if(detail?.name==='reminders'&&detail.source!=='reminders-activity'){items=await userdata.load('reminders',[]);draw()}});userdata.load('reminders',[]).then(value=>{items=value;draw()});draw();return()=>off()}
};

export const notesActivity={
  mount(root,context,target={}){const{app,userdata,i18n,kernel,dialog}=context;let notes=[],selectedId=target.result?.id||'',timer=0;const selected=()=>notes.find(note=>note.id===selectedId)||notes[0];
    const draw=()=>{const note=selected();selectedId=note?.id||'';root.innerHTML=appShell(app,context,`<div class="activity-notes">${notes.length?`<nav>${notes.slice(0,20).map(item=>`<button class="${item.id===selectedId?'selected':''}" data-note-id="${esc(item.id)}"><strong>${esc(item.title)}</strong><small>${esc((item.content||'').replace(/\s+/g,' ').slice(0,48))}</small></button>`).join('')}</nav><section><input data-note-title value="${esc(note.title)}"><textarea data-note-content placeholder="${esc(i18n.t('writeNote'))}">${esc(note.content||'')}</textarea><small data-note-state>${esc(i18n.t('saved'))}</small></section>`:empty('note',i18n.t('noNotes'))}</div><footer><button data-note-add>${icon('plus',13)} ${esc(i18n.t('newNote'))}</button></footer>`,fullAppButton(app.id,i18n));bind()};
    const save=async()=>{const note=selected(),title=root.querySelector('[data-note-title]'),content=root.querySelector('[data-note-content]');if(!note||!title||!content)return;note.title=title.value.trim()||i18n.t('untitledNote');note.content=content.value;note.updatedAt=Date.now();await userdata.save('notes',notes,{source:'notes-activity'});root.querySelector('[data-note-state]')?.replaceChildren(i18n.t('saved'))};const schedule=()=>{root.querySelector('[data-note-state]')?.replaceChildren(i18n.t('edited'));clearTimeout(timer);timer=setTimeout(save,600)};
    const bind=()=>{bindFullApp(root,app.id,context);root.querySelectorAll('[data-note-id]').forEach(button=>button.onclick=async()=>{await save();selectedId=button.dataset.noteId;draw()});root.querySelector('[data-note-title]')?.addEventListener('input',schedule);root.querySelector('[data-note-content]')?.addEventListener('input',schedule);root.querySelector('[data-note-add]')?.addEventListener('click',async()=>{const title=await dialog.prompt({title:i18n.t('newNote'),placeholder:i18n.t('noteTitle')});if(title===null)return;const note={id:crypto.randomUUID(),title:title||i18n.t('untitledNote'),content:'',pinned:false,updatedAt:Date.now()};notes.unshift(note);selectedId=note.id;await userdata.save('notes',notes,{source:'notes-activity'});draw()})};
    const off=kernel.bus.on('userdata:change',async detail=>{if(detail?.name==='notes'&&detail.source!=='notes-activity'){notes=await userdata.load('notes',[]);draw()}});userdata.load('notes',[]).then(value=>{notes=value;draw()});draw();return()=>{off();clearTimeout(timer);save()}}
};

export const contactsActivity={
  mount(root,context,target={}){const{app,userdata,i18n,kernel}=context;let contacts=[],query=target.params?.query||'';const draw=()=>{const shown=contacts.filter(item=>`${item.name} ${item.email} ${item.phone}`.toLowerCase().includes(query.toLowerCase()));root.innerHTML=appShell(app,context,`<label class="activity-search">${icon('search',13)}<input data-contact-search value="${esc(query)}" placeholder="${esc(i18n.t('search'))}"></label><div class="activity-contact-list">${shown.length?shown.slice(0,40).map(item=>`<article><span>${esc(item.name?.split(/\s+/).map(value=>value[0]).slice(0,2).join('').toUpperCase())}</span><div><strong>${esc(item.name)}</strong><small>${esc(item.email||item.phone||'')}</small></div></article>`).join(''):empty('contacts',i18n.t('noSearchResults'))}</div>`,fullAppButton(app.id,i18n));bindFullApp(root,app.id,context);const input=root.querySelector('[data-contact-search]');if(input)input.oninput=()=>{query=input.value;draw();requestAnimationFrame(()=>root.querySelector('[data-contact-search]')?.focus())}};const off=kernel.bus.on('userdata:change',async detail=>{if(detail?.name==='contacts'){contacts=await userdata.load('contacts',[]);draw()}});userdata.load('contacts',[]).then(value=>{contacts=value;draw()});draw();return()=>off()}
};
