import { icon } from '../../icons.js';
import {calculateExpression as calculate,calculatorContentMarkup} from '../calculator/view.js';
import {mountClockView} from '../clock/view.js';
import { weatherDetailMarkup,weatherEsc,weatherViewData } from '../weather/view.js';
import { appShell,bindFullApp,empty,esc,fullAppButton } from './shared.js';

export const weatherActivity={
  mount(root,context,target={}){
    const{app,weather,i18n,kernel}=context;let lookup=null,searchOpen=false,searchQuery='',results=[],searchTimer=0,searchSequence=0,searching=false,composing=false;
    const value=()=>lookup||weather.snapshot();
    const resultsMarkup=()=>searching?`<div class="weather-searching"><i></i>${esc(i18n.t('searching'))}</div>`:results.map((place,index)=>`<button data-weather-place="${index}"><span><strong>${weatherEsc(place.name)}</strong><small>${weatherEsc([place.admin1,place.country].filter(Boolean).join(', '))}</small></span><b>${weatherEsc(place.country_code||'')}</b></button>`).join('');
    const searchMarkup=()=>`<section class="weather-search"><div><label>${icon('search',16)}<input value="${weatherEsc(searchQuery)}" placeholder="${weatherEsc(i18n.t('searchCity'))}" autocomplete="off" spellcheck="false"><button data-weather-close>×</button></label><div data-weather-results>${resultsMarkup()}</div></div></section>`;
    const draw=()=>{const snapshot=value(),{condition}=weatherViewData(snapshot,i18n),popOut=`<button data-activity-full-app="${esc(app.id)}" title="${esc(i18n.t('openInApp'))}">${icon('maximize',13)}</button>`;root.innerHTML=`<div class="activity-surface activity-weather-edge"><main><div class="weather-app weather-${condition.key} activity-weather-app"><main>${weatherDetailMarkup(snapshot,i18n,{extraActions:popOut})}</main>${searchOpen?searchMarkup():''}</div></main></div>`;bind()};
    const bindPlaces=()=>root.querySelectorAll('[data-weather-place]').forEach(button=>button.onclick=()=>{const place=results[Number(button.dataset.weatherPlace)];if(!place)return;lookup=null;searchOpen=false;weather.select(place).catch(()=>{});draw()});
    const updateResults=()=>{const container=root.querySelector('[data-weather-results]');if(!container)return;container.innerHTML=resultsMarkup();bindPlaces()};
    const runSearch=()=>{clearTimeout(searchTimer);const query=searchQuery.trim(),sequence=++searchSequence;if(query.length<2){results=[];searching=false;updateResults();return}searchTimer=setTimeout(async()=>{searching=true;updateResults();try{const next=await weather.search(query);if(sequence!==searchSequence)return;results=next}catch{if(sequence!==searchSequence)return;results=[]}finally{if(sequence===searchSequence){searching=false;updateResults()}}},280)};
    const openSearch=()=>{searchOpen=true;searchQuery='';results=[];searching=false;draw();requestAnimationFrame(()=>root.querySelector('.weather-search input')?.focus())};
    const closeSearch=()=>{clearTimeout(searchTimer);searchSequence++;searchOpen=false;draw()};
    const bind=()=>{bindFullApp(root,app.id,context);root.querySelectorAll('[data-weather-search]').forEach(button=>button.onclick=openSearch);root.querySelector('[data-weather-close]')?.addEventListener('click',closeSearch);root.querySelector('[data-weather-refresh]')?.addEventListener('click',()=>{lookup=null;weather.refresh(true).catch(()=>{})});const input=root.querySelector('.weather-search input');if(input){input.oncompositionstart=()=>{composing=true};input.oncompositionend=()=>{composing=false;searchQuery=input.value;runSearch()};input.oninput=()=>{searchQuery=input.value;if(!composing)runSearch()}}bindPlaces()};
    const off=kernel.bus.on('weather:update',()=>{if(!lookup&&!searchOpen)draw()});if(target.params?.location)weather.lookup(target.params.location).then(next=>{lookup=next;draw()}).catch(()=>{});else weather.refresh(false).catch(()=>{});draw();return()=>{clearTimeout(searchTimer);off()}
  }
};

export const monitorActivity={mount(root,context){const{app,metrics,i18n,kernel}=context;const draw=()=>{const value=metrics.snapshot(),used=(value.usedKb/1024).toFixed(1),total=(value.totalKb/1024).toFixed(0);root.innerHTML=appShell(app,context,value.ready?`<div class="activity-gauges"><article><span><i style="--value:${Number(value.percent)||0}%"></i></span><strong>${Math.round(Number(value.percent)||0)}%</strong><small>${esc(i18n.t('memory'))}</small></article><article><span><i style="--value:${Math.min(100,(Number(value.loadAverage)||0)*50)}%"></i></span><strong>${esc(value.loadAverage??'—')}</strong><small>${esc(i18n.t('load'))}</small></article></div><dl class="activity-facts"><div><dt>${esc(i18n.t('uptime'))}</dt><dd>${Math.floor((value.uptimeSeconds||0)/60)} min</dd></div><div><dt>${esc(i18n.t('memory'))}</dt><dd>${esc(used)} / ${esc(total)} MB</dd></div></dl>`:empty('memory',i18n.t('waitingForMetrics')),fullAppButton(app.id,i18n));bindFullApp(root,app.id,context)};const off=kernel.bus.on('metrics:update',draw);metrics.refresh().catch(()=>{});draw();return()=>off()}};

export const settingsActivity={mount(root,context){const{app,settings,i18n,kernel}=context;const draw=()=>{root.innerHTML=appShell(app,context,`<div class="activity-settings"><button data-setting-theme><span>${icon(settings.get('theme')==='dark'?'moon':'sun',18)}</span><span><strong>${esc(i18n.t('appearance'))}</strong><small>${esc(i18n.t(settings.get('theme')))}</small></span></button><button data-setting-motion><span>${icon('accessibility',18)}</span><span><strong>${esc(i18n.t('reduceMotion'))}</strong><small>${esc(i18n.t(settings.get('reduceMotion')?'on':'off'))}</small></span></button><button data-setting-locale><span>${icon('globe',18)}</span><span><strong>${esc(i18n.t('language'))}</strong><small>${esc(settings.get('locale')==='zh'?'中文':'English')}</small></span></button></div>`,fullAppButton(app.id,i18n));bindFullApp(root,app.id,context);root.querySelector('[data-setting-theme]').onclick=()=>settings.set('theme',settings.get('theme')==='dark'?'light':'dark');root.querySelector('[data-setting-motion]').onclick=()=>settings.set('reduceMotion',!settings.get('reduceMotion'));root.querySelector('[data-setting-locale]').onclick=()=>settings.set('locale',settings.get('locale')==='zh'?'en':'zh')};const off=kernel.bus.on('settings:change',draw);draw();return()=>off()}};

export const calculatorActivity={mount(root,context){const{app,i18n}=context;let expression='',history=[],scientific=false;const numeric=()=>{try{return calculate(expression.replace(/×/g,'*').replace(/÷/g,'/').replace(/−/g,'-'))}catch{return Number(expression)||0}};const draw=()=>{const popOut=`<button data-activity-full-app="${esc(app.id)}" title="${esc(i18n.t('openInApp'))}">${icon('maximize',13)}</button>`;root.innerHTML=`<div class="activity-surface activity-calculator-edge"><main><div class="calculator-pro activity-calculator-pro" tabindex="0">${calculatorContentMarkup({i18n,expression,history,scientific,extraActions:popOut})}</div></main></div>`;bind();requestAnimationFrame(()=>root.querySelector('.activity-calculator-pro')?.focus())};const apply=key=>{if(key==='C')expression='';else if(key==='⌫')expression=expression.slice(0,-1);else if(key==='='){const source=expression;try{expression=String(calculate(source.replace(/×/g,'*').replace(/÷/g,'/').replace(/−/g,'-')));history.unshift({expression:source,result:expression});history=history.slice(0,12)}catch{expression=i18n.t('calculatorError')}}else{if(expression===i18n.t('calculatorError'))expression='';expression+=key}draw()};const unary=operation=>{const value=numeric(),functions={sin:Math.sin,cos:Math.cos,tan:Math.tan,sqrt:Math.sqrt,square:number=>number**2,inverse:number=>1/number},result=functions[operation](value);if(Number.isFinite(result)){history.unshift({expression:`${operation}(${value})`,result:String(result)});expression=String(result)}else expression=i18n.t('calculatorError');draw()};const bind=()=>{bindFullApp(root,app.id,context);root.querySelectorAll('[data-key]').forEach(button=>button.onclick=()=>apply(button.dataset.key));root.querySelectorAll('[data-unary]').forEach(button=>button.onclick=()=>unary(button.dataset.unary));root.querySelectorAll('[data-calc-mode]').forEach(button=>button.onclick=()=>{scientific=button.dataset.calcMode==='scientific';draw()});root.querySelectorAll('[data-history]').forEach(button=>button.onclick=()=>{expression=button.dataset.history;draw()});root.querySelector('[data-calc-clear-history]').onclick=()=>{history=[];draw()}};const keydown=event=>{const map={'*':'×','/':'÷','-':'−','Enter':'=','=':'=','Escape':'C','Backspace':'⌫'},key=map[event.key]||event.key;if(!/^[0-9.+()%]$/.test(key)&&!['×','÷','−','=','C','⌫'].includes(key))return;event.preventDefault();apply(key)};root.addEventListener('keydown',keydown);draw();return()=>root.removeEventListener('keydown',keydown)}};

export const clockActivity={mount(root,context){const{app,i18n}=context,popOut=`<button data-activity-full-app="${esc(app.id)}" title="${esc(i18n.t('openInApp'))}">${icon('maximize',13)}</button>`;root.innerHTML='<div class="activity-surface activity-clock-edge"><main><div data-clock-activity-host></div></main></div>';const host=root.querySelector('[data-clock-activity-host]');return mountClockView(host,i18n,{compact:true,extraActions:popOut,bindExtra:()=>bindFullApp(root,app.id,context)})}};

export const machineActivity={mount(root,context){const{app,machine,system,settings,i18n,kernel}=context;const draw=()=>{const net=system.networkState;root.innerHTML=appShell(app,context,`<div class="activity-machine"><span class="machine-mark">${icon('logo',38)}</span><div><strong>Aeris Computer</strong><small>v86 · x86 · ${settings.get('memory')} MB</small><b class="status-${esc(machine.status)}"><i></i>${esc(i18n.t(machine.status==='running'?'running':machine.status==='booting'?'booting':'stopped'))}</b></div></div><dl class="activity-facts"><div><dt>${esc(i18n.t('network'))}</dt><dd>${esc(i18n.t(net.status==='connected'?'connected':'offline'))}</dd></div><div><dt>${esc(i18n.t('ipAddress'))}</dt><dd>${esc(net.address||'—')}</dd></div></dl>`,fullAppButton(app.id,i18n));bindFullApp(root,app.id,context)};const offStatus=kernel.bus.on('machine:status',draw),offNetwork=kernel.bus.on('network:change',draw);draw();return()=>{offStatus();offNetwork()}}};

export const diskActivity={mount(root,context){const{app,system,i18n,kernel}=context;let data=null,error='';const draw=()=>{root.innerHTML=appShell(app,context,data?`<div class="activity-disk"><span>${icon('disk',35)}</span><div><strong>Aeris Linux</strong><small>${esc(data.device)} · ${esc(data.mount)}</small></div></div><div class="activity-capacity"><i><span style="width:${data.percent}%"></span></i><strong>${data.percent}% ${esc(i18n.t('used').toLowerCase())}</strong><small>${esc(data.used)} / ${esc(data.size)}</small></div>`:empty(error?'warning':'disk',error||i18n.t('readingStorage')),fullAppButton(app.id,i18n));bindFullApp(root,app.id,context)};const load=async()=>{if(!system.ready){error=i18n.t('startMachine');return draw()}try{const {output}=await system.exec("df -hP / | tail -1",12000),row=output.trim().split(/\s+/);data={device:row[0],size:row[1],used:row[2],percent:parseInt(row[4])||0,mount:row[5]};error=''}catch(reason){error=reason.message}draw()};const off=kernel.bus.on('guest:ready',load);load();return()=>off()}};

export const terminalActivity={mount(root,context,target={}){const{app,i18n}=context,command=target.params?.command||'',output=target.result?.output||target.output||'',phase=target.phase||'';root.innerHTML=appShell(app,context,`<div class="activity-terminal"><header><i></i><i></i><i></i><span>${esc(i18n.t('terminal'))}</span></header><pre>${command?`<code>❯ ${esc(command)}</code>\n`:''}${esc(output||i18n.t(phase==='running'?'agentWorking':'activityOpenFullAppCopy'))}</pre></div>`,fullAppButton(app.id,i18n));bindFullApp(root,app.id,context);return()=>{}}};

export const compactStatusActivity={mount(root,context){const{app,i18n}=context;root.innerHTML=appShell(app,context,empty(app.icon,i18n.t(app.title),i18n.t('activityOpenFullAppCopy')),fullAppButton(app.id,i18n));bindFullApp(root,app.id,context);return()=>{}}};
