import { icon } from '../../icons.js';
import { appShell,bindFullApp,empty,esc,fullAppButton } from './shared.js';

export const weatherActivity={mount(root,context,target={}){const{app,weather,i18n,kernel}=context;let lookup=null;const draw=()=>{const value=lookup||weather.snapshot(),current=value.data?.current||{},units=value.data?.current_units||{};root.innerHTML=appShell(app,context,value.location?`<div class="activity-weather"><span>${icon('sun',40)}</span><div><small>${esc([value.location.name,value.location.country].filter(Boolean).join(', '))}</small><strong>${esc(current.temperature_2m??'—')}${esc(units.temperature_2m||'°')}</strong><p>${esc(i18n.t('feelsLike'))} ${esc(current.apparent_temperature??'—')}${esc(units.apparent_temperature||'°')}</p></div></div><dl class="activity-facts"><div><dt>${esc(i18n.t('humidity'))}</dt><dd>${esc(current.relative_humidity_2m??'—')}%</dd></div><div><dt>${esc(i18n.t('wind'))}</dt><dd>${esc(current.wind_speed_10m??'—')} ${esc(units.wind_speed_10m||'')}</dd></div></dl><footer><button data-weather-refresh>${icon('refresh',13)} ${esc(i18n.t('refresh'))}</button></footer>`:empty('sun',i18n.t('weatherUnavailable')),fullAppButton(app.id,i18n));bindFullApp(root,app.id,context);root.querySelector('[data-weather-refresh]')?.addEventListener('click',()=>{lookup=null;weather.refresh(true).catch(()=>{})})};const off=kernel.bus.on('weather:update',draw);if(target.params?.location)weather.lookup(target.params.location).then(value=>{lookup=value;draw()}).catch(()=>{});else weather.refresh(false).catch(()=>{});draw();return()=>off()}};

export const monitorActivity={mount(root,context){const{app,metrics,i18n,kernel}=context;const draw=()=>{const value=metrics.snapshot(),used=(value.usedKb/1024).toFixed(1),total=(value.totalKb/1024).toFixed(0);root.innerHTML=appShell(app,context,value.ready?`<div class="activity-gauges"><article><span><i style="--value:${Number(value.percent)||0}%"></i></span><strong>${Math.round(Number(value.percent)||0)}%</strong><small>${esc(i18n.t('memory'))}</small></article><article><span><i style="--value:${Math.min(100,(Number(value.loadAverage)||0)*50)}%"></i></span><strong>${esc(value.loadAverage??'—')}</strong><small>${esc(i18n.t('load'))}</small></article></div><dl class="activity-facts"><div><dt>${esc(i18n.t('uptime'))}</dt><dd>${Math.floor((value.uptimeSeconds||0)/60)} min</dd></div><div><dt>${esc(i18n.t('memory'))}</dt><dd>${esc(used)} / ${esc(total)} MB</dd></div></dl>`:empty('memory',i18n.t('waitingForMetrics')),fullAppButton(app.id,i18n));bindFullApp(root,app.id,context)};const off=kernel.bus.on('metrics:update',draw);metrics.refresh().catch(()=>{});draw();return()=>off()}};

export const settingsActivity={mount(root,context){const{app,settings,i18n,kernel}=context;const draw=()=>{root.innerHTML=appShell(app,context,`<div class="activity-settings"><button data-setting-theme><span>${icon(settings.get('theme')==='dark'?'moon':'sun',18)}</span><span><strong>${esc(i18n.t('appearance'))}</strong><small>${esc(i18n.t(settings.get('theme')))}</small></span></button><button data-setting-motion><span>${icon('accessibility',18)}</span><span><strong>${esc(i18n.t('reduceMotion'))}</strong><small>${esc(i18n.t(settings.get('reduceMotion')?'on':'off'))}</small></span></button><button data-setting-locale><span>${icon('globe',18)}</span><span><strong>${esc(i18n.t('language'))}</strong><small>${esc(settings.get('locale')==='zh'?'中文':'English')}</small></span></button></div>`,fullAppButton(app.id,i18n));bindFullApp(root,app.id,context);root.querySelector('[data-setting-theme]').onclick=()=>settings.set('theme',settings.get('theme')==='dark'?'light':'dark');root.querySelector('[data-setting-motion]').onclick=()=>settings.set('reduceMotion',!settings.get('reduceMotion'));root.querySelector('[data-setting-locale]').onclick=()=>settings.set('locale',settings.get('locale')==='zh'?'en':'zh')};const off=kernel.bus.on('settings:change',draw);draw();return()=>off()}};

export const calculatorActivity={mount(root,context){const{app,i18n}=context;let expression='',result='0';const calculate=()=>{try{if(!/^[\d\s+\-*/%().]+$/.test(expression))throw new Error();const value=Function(`"use strict";return (${expression||0})`)();result=Number.isFinite(value)?String(value):'Error'}catch{result='Error'}};const draw=()=>{root.innerHTML=appShell(app,context,`<div class="activity-calculator"><input data-calc-expression value="${esc(expression)}" placeholder="24 * (7 + 3)"><output>${esc(result)}</output><div>${['7','8','9','/','4','5','6','*','1','2','3','-','0','.','%','+'].map(value=>`<button data-calc-key="${value}">${value}</button>`).join('')}<button data-calc-clear>C</button><button class="equals" data-calc-equals>=</button></div></div>`,fullAppButton(app.id,i18n));bindFullApp(root,app.id,context);const input=root.querySelector('[data-calc-expression]');input.oninput=()=>expression=input.value;input.onkeydown=event=>{if(event.key==='Enter'){expression=input.value;calculate();draw()}};root.querySelectorAll('[data-calc-key]').forEach(button=>button.onclick=()=>{expression+=button.dataset.calcKey;draw();root.querySelector('[data-calc-expression]')?.focus()});root.querySelector('[data-calc-clear]').onclick=()=>{expression='';result='0';draw()};root.querySelector('[data-calc-equals]').onclick=()=>{calculate();draw()}};draw();return()=>{}}};

export const clockActivity={mount(root,context){const{app,i18n}=context;const draw=()=>{const now=new Date();root.innerHTML=appShell(app,context,`<div class="activity-clock"><time>${esc(new Intl.DateTimeFormat(i18n.t('dateFormat'),{hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(now))}</time><strong>${esc(new Intl.DateTimeFormat(i18n.t('dateFormat'),{weekday:'long',month:'long',day:'numeric'}).format(now))}</strong><small>${esc(Intl.DateTimeFormat().resolvedOptions().timeZone)}</small></div>`,fullAppButton(app.id,i18n));bindFullApp(root,app.id,context)};const timer=setInterval(draw,1000);draw();return()=>clearInterval(timer)}};

export const machineActivity={mount(root,context){const{app,machine,system,settings,i18n,kernel}=context;const draw=()=>{const net=system.networkState;root.innerHTML=appShell(app,context,`<div class="activity-machine"><span class="machine-mark">${icon('logo',38)}</span><div><strong>Aeris Computer</strong><small>v86 · x86 · ${settings.get('memory')} MB</small><b class="status-${esc(machine.status)}"><i></i>${esc(i18n.t(machine.status==='running'?'running':machine.status==='booting'?'booting':'stopped'))}</b></div></div><dl class="activity-facts"><div><dt>${esc(i18n.t('network'))}</dt><dd>${esc(i18n.t(net.status==='connected'?'connected':'offline'))}</dd></div><div><dt>${esc(i18n.t('ipAddress'))}</dt><dd>${esc(net.address||'—')}</dd></div></dl>`,fullAppButton(app.id,i18n));bindFullApp(root,app.id,context)};const offStatus=kernel.bus.on('machine:status',draw),offNetwork=kernel.bus.on('network:change',draw);draw();return()=>{offStatus();offNetwork()}}};

export const diskActivity={mount(root,context){const{app,system,i18n,kernel}=context;let data=null,error='';const draw=()=>{root.innerHTML=appShell(app,context,data?`<div class="activity-disk"><span>${icon('disk',35)}</span><div><strong>Aeris Linux</strong><small>${esc(data.device)} · ${esc(data.mount)}</small></div></div><div class="activity-capacity"><i><span style="width:${data.percent}%"></span></i><strong>${data.percent}% ${esc(i18n.t('used').toLowerCase())}</strong><small>${esc(data.used)} / ${esc(data.size)}</small></div>`:empty(error?'warning':'disk',error||i18n.t('readingStorage')),fullAppButton(app.id,i18n));bindFullApp(root,app.id,context)};const load=async()=>{if(!system.ready){error=i18n.t('startMachine');return draw()}try{const {output}=await system.exec("df -hP / | tail -1",12000),row=output.trim().split(/\s+/);data={device:row[0],size:row[1],used:row[2],percent:parseInt(row[4])||0,mount:row[5]};error=''}catch(reason){error=reason.message}draw()};const off=kernel.bus.on('guest:ready',load);load();return()=>off()}};

export const terminalActivity={mount(root,context,target={}){const{app,i18n}=context,command=target.params?.command||'',output=target.result?.output||target.output||'',phase=target.phase||'';root.innerHTML=appShell(app,context,`<div class="activity-terminal"><header><i></i><i></i><i></i><span>${esc(i18n.t('terminal'))}</span></header><pre>${command?`<code>❯ ${esc(command)}</code>\n`:''}${esc(output||i18n.t(phase==='running'?'agentWorking':'activityOpenFullAppCopy'))}</pre></div>`,fullAppButton(app.id,i18n));bindFullApp(root,app.id,context);return()=>{}}};

export const compactStatusActivity={mount(root,context){const{app,i18n}=context;root.innerHTML=appShell(app,context,empty(app.icon,i18n.t(app.title),i18n.t('activityOpenFullAppCopy')),fullAppButton(app.id,i18n));bindFullApp(root,app.id,context);return()=>{}}};
