import{Type}from'@earendil-works/pi-ai';
import{validateThemePackage}from'../platform/themes/ThemePackage.js';

const result=(text,details={})=>({content:[{type:'text',text}],details});
const required=(input,key)=>{const value=String(input[key]||'').trim();if(!value)throw new Error(`Theme Studio requires ${key}.`);return value};

export class ThemeStudioService{
  constructor(themeRuntime){this.themeRuntime=themeRuntime;this.approvalService=null;this.drafts=new Map()}
  start(){}
  setApprovalService(service){this.approvalService=service}
  tool(){const optional=description=>Type.Optional(Type.String({description}));return{name:'aeris_theme_studio',label:'Aeris Theme Studio',description:'Create, inspect, validate, preview, install, update, apply, list, and uninstall declarative Aeris system themes. Available after loading the create-theme skill.',parameters:Type.Object({type:Type.Union(['validate','install','update','list','inspect','preview','stop_preview','apply','uninstall'].map(value=>Type.Literal(value))),draftId:optional('Validated draft id.'),id:optional('Installed theme id.'),packageJson:optional('Complete declarative theme package as JSON for validate.')},{additionalProperties:false}),executionMode:'sequential',execute:async(toolCallId,input,signal,onUpdate)=>{
    if(input.type==='list'){const themes=this.themeRuntime.list();return result(JSON.stringify(themes.map(item=>({id:item.manifest.id,name:item.manifest.name,version:item.manifest.version,author:item.manifest.author,baseMode:item.manifest.baseMode,source:item.source,active:item.active})),null,2),{skillId:'create-theme',operation:'list',phase:'completed',result:{themes}})}
    if(input.type==='inspect'){const id=required(input,'id'),theme=this.themeRuntime.get(id);if(!theme)throw new Error(`Theme is not installed: ${id}`);return result(JSON.stringify(theme,null,2),{skillId:'create-theme',operation:'inspect',phase:'completed',result:{id,manifest:theme.manifest}})}
    if(input.type==='stop_preview'){const theme=this.themeRuntime.stopPreview();return result(`Stopped theme preview. Restored ${theme.id}.`,{skillId:'create-theme',operation:'stop_preview',phase:'completed',result:theme})}
    if(input.type==='apply'){const id=required(input,'id'),theme=this.themeRuntime.apply(id);return result(`Applied “${theme.name.en}” (${theme.id}).`,{skillId:'create-theme',operation:'apply',phase:'completed',result:theme})}
    if(input.type==='preview'){const draft=this.#draft(input),theme=this.themeRuntime.preview(draft.package);return result(`Previewing “${theme.name.en}” (${theme.id}). The preview is temporary until installed and applied, or stopped.`,{skillId:'create-theme',operation:'preview',phase:'completed',result:theme})}
    if(input.type==='install'||input.type==='update'){const draft=this.#draft(input),id=draft.package.manifest.id,current=this.themeRuntime.list().find(item=>item.manifest.id===id);if(input.type==='install'&&current)throw new Error(`Theme is already installed: ${id}`);if(input.type==='update'&&!current)throw new Error(`Theme is not installed: ${id}`);if(current?.source==='bundled')throw new Error('Bundled themes cannot be updated.');const outcome=await this.#approve({toolCallId,draft,operation:input.type,signal,onUpdate,message:`${input.type==='install'?'Install':'Update'} “${draft.package.manifest.name.en}” (${id}) ${draft.package.manifest.version}?`,execute:()=>this.themeRuntime.install(draft.package,{replace:input.type==='update'})});if(!outcome.approved)return result(`The user denied the theme ${input.type} request.`,{...outcome.state,skillId:'create-theme'});this.drafts.delete(draft.id);return result(`${input.type==='install'?'Installed':'Updated'} “${draft.package.manifest.name.en}” (${id}).`,{...outcome.state,skillId:'create-theme',result:{id,manifest:outcome.value}})}
    if(input.type==='uninstall'){const id=required(input,'id'),record=this.themeRuntime.list().find(item=>item.manifest.id===id);if(!record)throw new Error(`Theme is not installed: ${id}`);if(record.source==='bundled')throw new Error('Bundled themes cannot be uninstalled.');const draft={package:this.themeRuntime.get(id)},outcome=await this.#approve({toolCallId,draft,operation:'uninstall',signal,onUpdate,message:`Uninstall “${record.manifest.name.en}” (${id})?`,execute:()=>this.themeRuntime.uninstall(id)});if(!outcome.approved)return result('The user denied the theme uninstall request.',{...outcome.state,skillId:'create-theme'});return result(`Uninstalled “${record.manifest.name.en}” (${id}).`,{...outcome.state,skillId:'create-theme',result:{id,uninstalled:true}})}
    let source;try{source=JSON.parse(required(input,'packageJson'))}catch{throw new Error('packageJson must be valid JSON.')}const theme=validateThemePackage(source),draftId=crypto.randomUUID();this.drafts.set(draftId,{id:draftId,package:theme,createdAt:Date.now()});return result(`Validated ${theme.manifest.id} ${theme.manifest.version}. Manifest, semantic tokens, typography, shape, material, motion, wallpaper, localization, and security constraints passed. Use preview with draftId “${draftId}” before requesting installation.`,{skillId:'create-theme',operation:'validate',phase:'completed',result:{draftId,manifest:theme.manifest,tokens:theme.tokens}})
  }}}
  #draft(input){const draft=this.drafts.get(String(input.draftId||''));if(!draft)throw new Error('The validated Theme Studio draft was not found. Validate the complete theme again.');return draft}
  async #approve({toolCallId,draft,operation,signal,onUpdate,message,execute}){if(!this.approvalService)throw new Error('Aeris approval service is unavailable.');return this.approvalService.runProtected({toolCallId,name:'aeris_theme_studio',label:`${operation[0].toUpperCase()+operation.slice(1)} ${draft.package.manifest.name.en}`,operation,params:{id:draft.package.manifest.id,version:draft.package.manifest.version},approvalMessage:message},signal,onUpdate,execute)}
}
