import{validateThemePackage,themeCssVariables}from'../platform/themes/ThemePackage.js';

const STORAGE_KEY='aeris.theme-runtime.packages.v1',clone=value=>structuredClone(value);
export class ThemeRuntimeService{
  constructor({settings,storage=globalThis.localStorage,bundledThemes=[]}={}){this.settings=settings;this.storage=storage;this.bundledThemes=bundledThemes;this.themes=new Map();this.previewTheme=null;this.previewPrevious='';}
  async prepare(){let records=[];try{records=JSON.parse(this.storage?.getItem(STORAGE_KEY)||'[]')}catch{}for(const source of this.bundledThemes){const value=validateThemePackage(source);this.themes.set(value.manifest.id,{package:value,source:'bundled'})}for(const record of Array.isArray(records)?records:[]){try{const value=validateThemePackage(record.package);if(!this.themes.has(value.manifest.id))this.themes.set(value.manifest.id,{package:value,source:'user'})}catch(error){console.warn('Skipped invalid Aeris theme package.',error)}}this.#persist();const selected=this.themes.has(this.settings.get('theme'))?this.settings.get('theme'):'light';this.apply(selected,{persist:false,emit:false})}
  start(){this.off=this.kernel.bus.on('settings:change',({key,value})=>{if(key==='theme'&&this.themes.has(value)&&value!==this.currentId())this.apply(value,{persist:false})})}
  stop(){this.off?.()}
  list(){return[...this.themes.values()].map(record=>({manifest:clone(record.package.manifest),tokens:clone(record.package.tokens),wallpaper:clone(record.package.wallpaper),source:record.source,active:record.package.manifest.id===this.currentId()}))}
  get(id){const record=this.themes.get(String(id));return record?clone(record.package):null}
  currentId(){return this.previewTheme?.manifest.id||document.documentElement.dataset.themeId||this.settings.get('theme')||'light'}
  snapshot(){const value=this.previewTheme||this.get(this.currentId())||this.get('light');return value?{id:value.manifest.id,version:value.manifest.version,name:clone(value.manifest.name),baseMode:value.manifest.baseMode,tokens:clone(value.tokens),wallpaper:clone(value.wallpaper),variables:themeCssVariables(value),preview:Boolean(this.previewTheme)}:null}
  apply(id,{persist=true,emit=true}={}){const record=this.themes.get(String(id));if(!record)throw new Error(`Theme is not installed: ${id}`);this.previewTheme=null;this.#applyPackage(record.package);if(persist&&this.settings.get('theme')!==id)this.settings.set('theme',id);if(emit)this.kernel?.bus.emit('theme:changed',this.snapshot());return this.snapshot()}
  preview(source){const value=validateThemePackage(source);if(!this.previewTheme)this.previewPrevious=this.settings.get('theme');this.previewTheme=value;this.#applyPackage(value);this.kernel?.bus.emit('theme:changed',this.snapshot());return this.snapshot()}
  stopPreview(){if(!this.previewTheme)return this.snapshot();const previous=this.previewPrevious||this.settings.get('theme');this.previewTheme=null;this.previewPrevious='';return this.apply(this.themes.has(previous)?previous:'light',{persist:false})}
  install(source,{replace=false}={}){const value=validateThemePackage(source),id=value.manifest.id,current=this.themes.get(id),wasActive=this.settings.get('theme')===id;if(current&&!replace)throw new Error(`Theme is already installed: ${id}`);if(current?.source==='bundled')throw new Error('Bundled themes cannot be replaced.');this.themes.set(id,{package:value,source:'user'});this.#persist();if(wasActive)this.apply(id,{persist:false});this.kernel?.bus.emit(current?'theme:updated':'theme:installed',{id,manifest:clone(value.manifest)});return clone(value.manifest)}
  uninstall(id){const record=this.themes.get(String(id));if(!record)return false;if(record.source==='bundled')throw new Error('Bundled themes cannot be uninstalled.');if(this.currentId()===id)this.apply('light');this.themes.delete(String(id));this.#persist();this.kernel?.bus.emit('theme:uninstalled',{id:String(id)});return true}
  #applyPackage(value){const root=document.documentElement,variables=themeCssVariables(value);root.dataset.theme=value.manifest.baseMode;root.dataset.themeId=value.manifest.id;root.dataset.themeMotion=value.tokens.motion.scale===0?'none':'full';root.style.colorScheme=value.manifest.baseMode;for(const [key,token]of Object.entries(variables))root.style.setProperty(key,token);root.style.fontFamily=value.tokens.typography.uiFont;root.style.fontSize=`calc(16px * ${value.tokens.typography.scale})`;document.querySelector('meta[name="theme-color"]')?.setAttribute('content',value.tokens.colors.surface)}
  #persist(){this.storage?.setItem(STORAGE_KEY,JSON.stringify([...this.themes.values()].filter(record=>record.source==='user').map(record=>({source:'user',package:record.package}))))}
}
