import{Type}from'@earendil-works/pi-ai';
import{validateWidgetPackage}from'../platform/widgets/WidgetPackage.js';

const textResult=(text,details={})=>({content:[{type:'text',text}],details});
const required=(input,key)=>{const value=String(input[key]||'').trim();if(!value)throw new Error(`Widget Studio requires ${key}.`);return value};
const parseObject=(value,label,fallback={})=>{if(value==null||value==='')return structuredClone(fallback);try{const parsed=typeof value==='string'?JSON.parse(value):value;if(!parsed||typeof parsed!=='object'||Array.isArray(parsed))throw new Error();return parsed}catch{throw new Error(`${label} must be a JSON object.`)}};
const list=value=>[...new Set(String(value||'').split(',').map(item=>item.trim()).filter(Boolean))];

export class WidgetStudioService{
  constructor(widgetRuntime){this.widgetRuntime=widgetRuntime;this.approvalService=null;this.drafts=new Map()}
  start(){}
  setApprovalService(service){this.approvalService=service}
  tool(){const optional=description=>Type.Optional(Type.String({description}));return{
    name:'future_widget_studio',label:'Future Widget Studio',description:'Inspect source, validate, install, update, list, and uninstall sandboxed Future desktop widget packages. This tool is available only after loading the create-widget skill.',
    parameters:Type.Object({
      type:Type.Union([Type.Literal('validate'),Type.Literal('install'),Type.Literal('update'),Type.Literal('list'),Type.Literal('inspect'),Type.Literal('uninstall')],{description:'Widget Studio operation.'}),
      draftId:optional('Validated draft id returned by validate.'),path:optional('For inspect, an exact package file path. Omit to inspect the complete package.'),
      id:optional('Lowercase widget id using letters, numbers, and hyphens.'),version:optional('Semantic version such as 1.0.0.'),
      nameEn:optional('English widget name.'),nameZh:optional('Chinese widget name.'),descriptionEn:optional('English widget description.'),descriptionZh:optional('Chinese widget description.'),icon:optional('Future icon id.'),
      sizes:optional('Comma-separated supported sizes: small, medium, large.'),defaultSize:optional('Default size included in sizes.'),permissions:optional('Comma-separated capabilities: storage, app.open, calendar.read, reminders.read, weather.read, metrics.read, music.read, music.control.'),
      refreshMode:optional('event or interval.'),refreshInterval:optional('Interval seconds from 60 to 3600 when refreshMode is interval.'),initialStateJson:optional('Initial state as a JSON object string.'),
      localeEnJson:optional('English translation dictionary as a JSON object string.'),localeZhJson:optional('Chinese translation dictionary as a JSON object string.'),
      widgetHtml:optional('Widget content HTML fragment without outer desktop chrome.'),widgetCss:optional('Widget content CSS using Future design variables.'),widgetJavaScript:optional('Widget JavaScript using FutureWidget SDK.'),
    },{additionalProperties:false}),executionMode:'sequential',
    execute:async(toolCallId,input,signal,onUpdate)=>{
      if(input.type==='list'){const widgets=this.widgetRuntime.list().map(item=>({id:item.manifest.id,name:item.manifest.name,version:item.manifest.version,sizes:item.manifest.sizes,source:item.source}));return textResult(widgets.length?JSON.stringify(widgets,null,2):'No extension widgets are installed.',{skillId:'create-widget',operation:'list',phase:'completed',result:{widgets}})}
      if(input.type==='inspect'){const widgetId=required(input,'id'),record=this.widgetRuntime.list().find(item=>item.manifest.id===widgetId),widgetPackage=this.widgetRuntime.get(widgetId);if(!record||!widgetPackage)throw new Error(`Extension widget is not installed: ${widgetId}`);const path=String(input.path||'').trim();if(path){if(typeof widgetPackage.files[path]!=='string')throw new Error(`Widget package file was not found: ${path}`);return textResult(widgetPackage.files[path],{skillId:'create-widget',operation:'inspect',phase:'completed',result:{widgetId,path,bytes:new TextEncoder().encode(widgetPackage.files[path]).length,source:record.source}})}return textResult(JSON.stringify(widgetPackage,null,2),{skillId:'create-widget',operation:'inspect',phase:'completed',result:{widgetId,manifest:widgetPackage.manifest,files:Object.fromEntries(Object.entries(widgetPackage.files).map(([name,content])=>[name,{bytes:new TextEncoder().encode(content).length}])),source:record.source}})}
      if(input.type==='install'){const draft=this.#draft(input,'Validate the widget again.');if(this.widgetRuntime.get(draft.package.manifest.id))throw new Error(`Widget is already installed: ${draft.package.manifest.id}`);const outcome=await this.#approve({toolCallId,draft,operation:'install',signal,onUpdate,execute:()=>this.widgetRuntime.install(draft.package),message:`Install “${draft.package.manifest.name.en}” (${draft.package.manifest.id})?\n\nRequested permissions:\n${this.#permissionSummary(draft.package.manifest.permissions)}\n\nThe validated widget will be available in the desktop widget gallery.`});if(!outcome.approved)return textResult('The user denied the widget installation request.',{...outcome.state,skillId:'create-widget'});this.drafts.delete(draft.id);return textResult(`Installed “${outcome.value.name.en}” (${outcome.value.id}). It is now available in the desktop widget gallery.`,{...outcome.state,skillId:'create-widget',result:{widgetId:outcome.value.id,manifest:outcome.value}})}
      if(input.type==='update'){const draft=this.#draft(input,'Inspect and validate the widget again.'),widgetId=draft.package.manifest.id,record=this.widgetRuntime.list().find(item=>item.manifest.id===widgetId);if(!record)throw new Error(`Extension widget is not installed: ${widgetId}`);if(record.source==='bundled')throw new Error(`Bundled widget cannot be updated: ${widgetId}`);const outcome=await this.#approve({toolCallId,draft,operation:'update',signal,onUpdate,execute:()=>this.widgetRuntime.install(draft.package,{replace:true,preserveState:true}),message:`Update “${record.manifest.name.en||widgetId}” (${widgetId}) to ${draft.package.manifest.version}?\n\nRequested permissions:\n${this.#permissionSummary(draft.package.manifest.permissions)}\n\nExisting widget state and desktop placement will be preserved.`});if(!outcome.approved)return textResult('The user denied the widget update request.',{...outcome.state,skillId:'create-widget'});this.drafts.delete(draft.id);return textResult(`Updated “${record.manifest.name.en||widgetId}” to ${draft.package.manifest.version}. Its state and desktop placement were preserved.`,{...outcome.state,skillId:'create-widget',result:{widgetId,updated:true,manifest:outcome.value}})}
      if(input.type==='uninstall'){const widgetId=required(input,'id'),record=this.widgetRuntime.list().find(item=>item.manifest.id===widgetId);if(!record)throw new Error(`Extension widget is not installed: ${widgetId}`);if(record.source==='bundled')throw new Error(`Bundled widget cannot be uninstalled: ${widgetId}`);const draft={package:{manifest:record.manifest}},outcome=await this.#approve({toolCallId,draft,operation:'uninstall',signal,onUpdate,execute:()=>this.widgetRuntime.uninstall(widgetId),message:`Uninstall “${record.manifest.name.en||widgetId}” (${widgetId})?\n\nIts package, desktop instances, and saved widget state will be permanently removed.`});if(!outcome.approved)return textResult('The user denied the widget uninstall request.',{...outcome.state,skillId:'create-widget'});return textResult(`Uninstalled “${record.manifest.name.en||widgetId}” (${widgetId}).`,{...outcome.state,skillId:'create-widget',result:{widgetId,uninstalled:true}})}
      this.#assertDesign(input);const widgetPackage=validateWidgetPackage(this.#package(input)),draftId=crypto.randomUUID();this.drafts.set(draftId,{id:draftId,createdAt:Date.now(),package:widgetPackage});return textResult(`Validated ${widgetPackage.manifest.id} ${widgetPackage.manifest.version}. Package structure, sizes, permissions, locales, source restrictions, JavaScript, and Future design requirements passed. Use type “install” with draftId “${draftId}” to request installation.`,{skillId:'create-widget',operation:'validate',phase:'completed',result:{draftId,manifest:widgetPackage.manifest}})
    },
  }}
  #draft(input,hint){const draft=this.drafts.get(String(input.draftId||''));if(!draft)throw new Error(`The validated Widget Studio draft was not found. ${hint}`);return draft}
  #permissionSummary(permissions){const labels={storage:'Save widget preferences','app.open':'Open Future applications','calendar.read':'Read calendar events','reminders.read':'Read reminders','weather.read':'Read weather data','metrics.read':'Read system metrics','music.read':'Read the music library and current playback','music.control':'Control music playback and volume'};return permissions.length?permissions.map(permission=>`• ${labels[permission]||permission}`).join('\n'):'• No additional access'}
  async #approve({toolCallId,draft,operation,signal,onUpdate,execute,message}){if(!this.approvalService)throw new Error('Future approval service is unavailable.');const manifest=draft.package.manifest;return this.approvalService.runProtected({toolCallId,name:'future_widget_studio',label:`${operation[0].toUpperCase()+operation.slice(1)} ${manifest.name.en||manifest.id}`,operation,params:{id:manifest.id,version:manifest.version},approvalMessage:message},signal,onUpdate,execute)}
  #assertDesign(input){const css=String(input.widgetCss||''),requiredTokens=['--text','--accent'],missing=requiredTokens.filter(token=>!new RegExp(`var\\(\\s*${token.replace('--','\\-\\-')}`).test(css));if(missing.length)throw new Error(`Widget CSS must use Future design tokens: ${missing.join(', ')}.`);if(/(?:animation|transition)\s*:/i.test(css)&&!/@media\s*\(\s*prefers-reduced-motion\s*:\s*reduce\s*\)/i.test(css))throw new Error('Widget CSS uses motion without a prefers-reduced-motion fallback.');const script=String(input.widgetJavaScript||'');if(!/\bFutureWidget\s*\.\s*environment\s*\.\s*subscribe\s*\(/.test(script))throw new Error('Widget must subscribe to FutureWidget.environment so size, theme, and locale changes apply immediately.');if(/\bFutureWidget\s*\.\s*data\s*\.\s*subscribe\s*\(/.test(script)&&!/\bFutureWidget\s*\.\s*errors\s*\.\s*subscribe\s*\(/.test(script))throw new Error('Widgets with live data subscriptions must subscribe to FutureWidget.errors and render subscription failures instead of remaining blank.')}
  #package(input){const id=required(input,'id'),nameEn=required(input,'nameEn'),nameZh=required(input,'nameZh'),sizes=list(input.sizes||'medium'),defaultSize=String(input.defaultSize||sizes[0]||'medium'),refreshMode=String(input.refreshMode||'event');return{manifest:{formatVersion:1,sdkVersion:'1',id,version:String(input.version||'1.0.0'),name:{en:nameEn,zh:nameZh},description:{en:required(input,'descriptionEn'),zh:required(input,'descriptionZh')},icon:String(input.icon||'grid'),sizes,defaultSize,permissions:list(input.permissions),refresh:{mode:refreshMode,interval:Number(input.refreshInterval)||300},initialState:parseObject(input.initialStateJson,'initialStateJson',{}),entry:{html:'widget.html',css:'widget.css',script:'widget.js'}},files:{'locales/en.json':JSON.stringify(parseObject(input.localeEnJson,'localeEnJson',{title:nameEn})),'locales/zh.json':JSON.stringify(parseObject(input.localeZhJson,'localeZhJson',{title:nameZh})),'widget.html':required(input,'widgetHtml'),'widget.css':required(input,'widgetCss'),'widget.js':required(input,'widgetJavaScript')}}}
}
