import { icon } from '../../icons.js';
const esc=value=>String(value).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/"/g,'&quot;');
const pad=value=>String(value).padStart(2,'0');
const today=()=>{const date=new Date();return `${date.getFullYear()}-${pad(date.getMonth()+1)}-${pad(date.getDate())}`};
export default{
  id:'reminders',title:'reminders',icon:'reminder',color:'violet',width:860,height:570,singleInstance:true,
  mount(root,{userdata,dialog,i18n}){
    let items=[],filter='today',query='';const save=()=>userdata.save('reminders',items);
    const filtered=()=>items.filter(item=>{if(filter==='today'&&item.due!==today())return false;if(filter==='scheduled'&&!item.due)return false;if(filter==='completed'&&!item.done)return false;if(filter!=='completed'&&item.done)return false;return item.title.toLowerCase().includes(query.toLowerCase())}).sort((a,b)=>(a.done-b.done)||String(a.due||'9999').localeCompare(String(b.due||'9999')));
    const askSchedule=async item=>{const hadDue=!!item.due,due=await dialog.prompt({title:i18n.t('dueDate'),message:i18n.t('optionalDateHint'),value:item.due||'',placeholder:'YYYY-MM-DD',validate:value=>!value||/^\d{4}-\d{2}-\d{2}$/.test(value)?'':i18n.t('invalidDate')});if(due===null)return false;let dueTime='';if(due){dueTime=await dialog.prompt({title:i18n.t('reminderTime'),message:i18n.t('reminderTimeHint'),value:item.dueTime||'09:00',placeholder:'HH:MM',validate:value=>/^([01]\d|2[0-3]):[0-5]\d$/.test(value)?'':i18n.t('invalidTime')});if(dueTime===null)return false}item.due=due||'';item.dueTime=dueTime||'';item.notify=Boolean(due)&&(hadDue?item.notify!==false:true);return true};
    const add=async()=>{const title=await dialog.prompt({title:i18n.t('newReminder'),placeholder:i18n.t('reminderTitle')});if(!title)return;const item={id:crypto.randomUUID(),title:title.trim(),done:false,due:filter==='today'?today():'',dueTime:'09:00',notify:true,priority:false,createdAt:Date.now()};if(!await askSchedule(item))return;items.push(item);await save();render()};
    const render=()=>{const shown=filtered(),counts={today:items.filter(item=>!item.done&&item.due===today()).length,scheduled:items.filter(item=>!item.done&&item.due).length,all:items.filter(item=>!item.done).length,completed:items.filter(item=>item.done).length};root.innerHTML=`<div class="system-app reminders-pro"><aside class="reminders-nav"><header><strong>${i18n.t('reminders')}</strong><button data-reminder-add aria-label="${i18n.t('newReminder')}">${icon('plus',15)}</button></header><div class="reminder-smart-lists">${[['today','calendar'],['scheduled','clock'],['all','reminder'],['completed','check']].map(([key,glyph])=>`<button data-reminder-filter="${key}" class="${filter===key?'selected':''}"><span>${icon(glyph,17)}</span><strong>${i18n.t(key)}</strong><b>${counts[key]}</b></button>`).join('')}</div><section><small>${i18n.t('myLists')}</small><button class="selected"><i></i><span>${i18n.t('reminders')}</span></button></section></aside><section class="reminders-content"><div class="app-commandbar"><h2>${i18n.t(filter)}</h2><div class="toolbar-spacer"></div><label class="app-search">${icon('search',14)}<input data-reminder-search value="${esc(query)}" placeholder="${i18n.t('search')}"></label>${filter==='completed'&&shown.length?`<button data-clear-completed>${i18n.t('clearCompleted')}</button>`:''}<button class="primary-action" data-reminder-add>${icon('plus',14)} ${i18n.t('newReminder')}</button></div><div class="reminder-list-pro">${shown.length?shown.map(item=>`<article class="${item.done?'done':''}"><input type="checkbox" data-reminder="${item.id}" ${item.done?'checked':''}><button class="reminder-title" data-reminder-edit="${item.id}"><strong>${esc(item.title)}</strong><small>${item.due?`${new Intl.DateTimeFormat(i18n.t('dateFormat'),{month:'short',day:'numeric'}).format(new Date(`${item.due}T12:00:00`))}${item.dueTime?` · ${item.dueTime}`:''}`:i18n.t('noDueDate')}</small></button>${item.due?`<button class="reminder-alert-icon ${item.notify?'active':''}" data-reminder-notify="${item.id}" title="${i18n.t(item.notify?'notificationEnabled':'notificationDisabled')}">${icon('bell',13)}</button>`:'<span></span>'}<button class="reminder-priority ${item.priority?'active':''}" data-reminder-priority="${item.id}" aria-label="${i18n.t('priority')}">!</button><button data-reminder-delete="${item.id}" aria-label="${i18n.t('delete')}">${icon('close',13)}</button></article>`).join(''):`<div class="empty-state">${icon('reminder',32)}<span>${i18n.t(query?'noSearchResults':'noReminders')}</span></div>`}</div><footer class="app-statusbar"><span>${i18n.t('remainingCount').replace('{count}',items.filter(item=>!item.done).length)}</span><span>${i18n.t('localAccount')}</span></footer></section></div>`;
      root.querySelectorAll('[data-reminder-filter]').forEach(button=>button.onclick=()=>{filter=button.dataset.reminderFilter;render()});root.querySelectorAll('[data-reminder-add]').forEach(button=>button.onclick=add);root.querySelector('[data-reminder-search]').oninput=event=>{query=event.target.value;render();requestAnimationFrame(()=>{const input=root.querySelector('[data-reminder-search]');input?.focus();input?.setSelectionRange(query.length,query.length)})};root.querySelectorAll('[data-reminder]').forEach(input=>input.onchange=async()=>{items.find(item=>item.id===input.dataset.reminder).done=input.checked;await save();render()});root.querySelectorAll('[data-reminder-edit]').forEach(button=>button.onclick=async()=>{const item=items.find(entry=>entry.id===button.dataset.reminderEdit),draft={...item},title=await dialog.prompt({title:i18n.t('editReminder'),value:item.title,placeholder:i18n.t('reminderTitle')});if(!title)return;draft.title=title.trim();if(!await askSchedule(draft))return;Object.assign(item,draft);await save();render()});root.querySelectorAll('[data-reminder-notify]').forEach(button=>button.onclick=async()=>{const item=items.find(entry=>entry.id===button.dataset.reminderNotify);item.notify=!item.notify;await save();render()});root.querySelectorAll('[data-reminder-priority]').forEach(button=>button.onclick=async()=>{const item=items.find(entry=>entry.id===button.dataset.reminderPriority);item.priority=!item.priority;await save();render()});root.querySelectorAll('[data-reminder-delete]').forEach(button=>button.onclick=async()=>{items=items.filter(item=>item.id!==button.dataset.reminderDelete);await save();render()});root.querySelector('[data-clear-completed]')?.addEventListener('click',async()=>{items=items.filter(item=>!item.done);await save();render()})};
    userdata.load('reminders',[]).then(value=>{items=value.map(item=>({...item,due:item.due||'',dueTime:item.dueTime||'',notify:item.notify!==false&&!!item.due,priority:!!item.priority}));render()});render();return()=>{};
  }
};
