export const systemFeaturePacks={
  en:{
    tasksManagedByAeris:'Tasks and action receipts are managed by Aeris',noActiveTasks:'No active tasks',
    taskCenter:'Task Center',taskCenterCopy:'Agent work across your computer',tasks:'Tasks',automations:'Automations',operationHistory:'Operation History',taskCenterPrivacy:'Tasks, automations, and action receipts stay on this computer.',tasksPageCopy:'Live and recent Agent work',automationsPageCopy:'Run Agent work from system events',historyPageCopy:'Review and reverse system changes',activeTasks:'Active tasks',waitingForYou:'Waiting for you',enabledAutomations:'Enabled automations',availableUndos:'Available undos',all:'All',active:'Active',completed:'Completed',enabled:'Enabled',disabled:'Disabled',noSystemTasks:'No system tasks',noSystemTasksCopy:'Agent conversations and background automations will appear here.',noAutomations:'No automations yet',noAutomationsCopy:'Connect a system event to an Agent instruction.',noOperations:'No recorded operations',noOperationsCopy:'Changes made through Agent tools will produce action receipts here.',agentTask:'Agent task',conversation:'Conversation',automation:'Automation',cancelTask:'Cancel task',retryTask:'Retry task',newAutomation:'New Automation',newAutomationCopy:'Choose a system event and the work Aeris should perform.',automationName:'Name',automationNamePlaceholder:'Morning briefing',trigger:'Trigger',agentInstruction:'Agent instruction',agentInstructionPlaceholder:'Summarize today’s calendar, reminders, and weather, then notify me.',automationAgentCopy:'This instruction runs as a private background Agent conversation.',createAutomation:'Create Automation',automationRequired:'Enter a name and Agent instruction.',automationDaily:'Every day',automationInterval:'On an interval',automationEvery:'Every',automationAppOpened:'When an app opens',automationFileChanged:'When a folder changes',automationNetworkOnline:'When the network connects',automationMemoryAbove:'When memory exceeds',minutes:'minutes',intervalMinutes:'Interval in minutes',application:'Application',anyApp:'Any app',watchedPath:'Watched path',memoryThreshold:'Memory threshold',runNow:'Run now',lastRun:'Last run',never:'Never',deleteAutomation:'Delete Automation',deleteAutomationConfirm:'Delete “{name}”?',clearHistory:'Clear History',clearHistoryConfirm:'Clear all operation receipts? This does not reverse the operations.',undo:'Undo',undoOperation:'Undo Operation',undoOperationConfirm:'Reverse “{name}”?',time:'Time',saving:'Saving…',taskStatus_running:'Running',taskStatus_approval:'Waiting for approval',taskStatus_input:'Waiting for input',taskStatus_completed:'Completed',taskStatus_failed:'Failed',taskStatus_cancelled:'Cancelled',taskStatus_never:'Never run',operationStatus_completed:'Completed',operationStatus_undoing:'Undoing',operationStatus_undone:'Undone',operationStatus_undo_failed:'Undo failed'
  },
  zh:{
    tasksManagedByAeris:'任务与操作凭证由 Aeris 管理',noActiveTasks:'没有活跃任务',
    taskCenter:'任务中心',taskCenterCopy:'Agent 在系统中的工作',tasks:'任务',automations:'自动化',operationHistory:'操作记录',taskCenterPrivacy:'任务、自动化与操作凭证只保存在这台电脑中。',tasksPageCopy:'查看 Agent 当前和最近的工作',automationsPageCopy:'由系统事件自动触发 Agent 工作',historyPageCopy:'检查并撤销系统变更',activeTasks:'活跃任务',waitingForYou:'等待你的操作',enabledAutomations:'已启用自动化',availableUndos:'可撤销操作',all:'全部',active:'进行中',completed:'已完成',enabled:'已启用',disabled:'已停用',noSystemTasks:'暂无系统任务',noSystemTasksCopy:'Agent 会话和后台自动化任务会显示在这里。',noAutomations:'还没有自动化',noAutomationsCopy:'将系统事件与一条 Agent 指令连接起来。',noOperations:'暂无操作记录',noOperationsCopy:'Agent 通过工具完成的系统变更会在这里生成操作凭证。',agentTask:'Agent 任务',conversation:'会话',automation:'自动化',cancelTask:'取消任务',retryTask:'重试任务',newAutomation:'新建自动化',newAutomationCopy:'选择系统事件，以及 Aeris 要执行的工作。',automationName:'名称',automationNamePlaceholder:'每日简报',trigger:'触发条件',agentInstruction:'Agent 指令',agentInstructionPlaceholder:'汇总今天的日程、提醒和天气，然后通知我。',automationAgentCopy:'此指令将在一个私有的后台 Agent 会话中执行。',createAutomation:'创建自动化',automationRequired:'请输入名称和 Agent 指令。',automationDaily:'每天',automationInterval:'按时间间隔',automationEvery:'每隔',automationAppOpened:'打开应用时',automationFileChanged:'目录发生变化时',automationNetworkOnline:'网络连接时',automationMemoryAbove:'内存超过阈值时',minutes:'分钟',intervalMinutes:'间隔分钟数',application:'应用',anyApp:'任意应用',watchedPath:'监控路径',memoryThreshold:'内存阈值',runNow:'立即运行',lastRun:'上次运行',never:'从未运行',deleteAutomation:'删除自动化',deleteAutomationConfirm:'删除“{name}”？',clearHistory:'清除记录',clearHistoryConfirm:'清除全部操作凭证？这不会撤销已经执行的操作。',undo:'撤销',undoOperation:'撤销操作',undoOperationConfirm:'撤销“{name}”？',time:'时间',saving:'正在保存…',taskStatus_running:'执行中',taskStatus_approval:'等待审批',taskStatus_input:'等待输入',taskStatus_completed:'已完成',taskStatus_failed:'失败',taskStatus_cancelled:'已取消',taskStatus_never:'从未运行',operationStatus_completed:'已完成',operationStatus_undoing:'正在撤销',operationStatus_undone:'已撤销',operationStatus_undo_failed:'撤销失败'
  }
};
