import { icon } from '../../icons.js';
const esc=value=>String(value).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/"/g,'&quot;');
export default{
  id:'notes',title:'notes',icon:'note',color:'yellow',width:930,height:600,singleInstance:true,
  mount(root,{userdata,dialog,i18n,agentContext,agentEntry}){
    let notes=[],selectedId=null,query='',folder='all',saveTimer=null;const selected=()=>notes.find(note=>note.id===selectedId)||null,persist=()=>userdata.save('notes',notes);
    const visible=()=>notes.filter(note=>(folder!=='pinned'||note.pinned)&&`${note.title} ${note.content}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>(Number(b.pinned)-Number(a.pinned))||(b.updatedAt-a.updatedAt));
    const reportContext=()=>{const note=selected(),editor=root.querySelector('[data-note-content]');if(!note)return;const content=editor?.value??note.content??'',selection=editor&&editor.selectionStart!==editor.selectionEnd?content.slice(editor.selectionStart,editor.selectionEnd):'';agentContext.set({appId:'notes',label:i18n.t('notes'),resource:{kind:'note',id:note.id,uri:`aeris://notes/${note.id}`,name:root.querySelector('[data-note-title]')?.value||note.title,metadata:{updatedAt:note.updatedAt,content:content.slice(0,6000),truncated:content.length>6000}},selection:{text:selection}})};
    const askAeris=()=>{reportContext();agentEntry.open({prompt:i18n.t('askAerisNotePrompt'),source:'notes'})};
    const commit=async()=>{const note=selected(),title=root.querySelector('[data-note-title]'),content=root.querySelector('[data-note-content]');if(!note||!title||!content)return;note.title=title.value.trim()||i18n.t('untitledNote');note.content=content.value;note.updatedAt=Date.now();clearTimeout(saveTimer);await persist()};
    const schedule=()=>{const status=root.querySelector('[data-note-status]');if(status)status.textContent=i18n.t('edited');clearTimeout(saveTimer);saveTimer=setTimeout(async()=>{await commit();const node=root.querySelector('[data-note-status]');if(node)node.textContent=i18n.t('saved')},700);const count=root.querySelector('[data-note-count]');if(count)count.textContent=i18n.t('wordCount').replace('{count}',root.querySelector('[data-note-content]').value.trim()?root.querySelector('[data-note-content]').value.trim().split(/\s+/).length:0)};
    const render=()=>{const note=selected(),shown=visible();root.innerHTML=`<div class="system-app notes-pro"><aside class="notes-folders"><header><strong>${i18n.t('notes')}</strong></header><button data-notes-folder="all" class="${folder==='all'?'selected':''}">${icon('note',16)}<span>${i18n.t('allNotes')}</span><b>${notes.length}</b></button><button data-notes-folder="pinned" class="${folder==='pinned'?'selected':''}">${icon('star',16)}<span>${i18n.t('pinned')}</span><b>${notes.filter(item=>item.pinned).length}</b></button><section><small>${i18n.t('folders')}</small><button class="selected">${icon('folder',16)}<span>${i18n.t('notes')}</span></button></section><footer><span>${icon('lock',13)}</span>${i18n.t('localAccount')}</footer></aside><aside class="notes-browser"><div class="notes-browser-toolbar"><label class="app-search">${icon('search',14)}<input data-notes-search value="${esc(query)}" placeholder="${i18n.t('searchNotes')}"></label><button data-note-new aria-label="${i18n.t('newNote')}">${icon('plus',15)}</button></div><div class="notes-scroll">${shown.length?shown.map(item=>`<button data-note="${item.id}" class="${item.id===selectedId?'selected':''}">${item.pinned?`<i>${icon('star',10)}</i>`:''}<strong>${esc(item.title)}</strong><span>${esc((item.content||'').replace(/\s+/g,' ').slice(0,64))||i18n.t('emptyNote')}</span><small>${new Intl.DateTimeFormat(i18n.t('dateFormat'),{month:'short',day:'numeric'}).format(item.updatedAt)}</small></button>`).join(''):`<div class="empty-state">${i18n.t(query?'noSearchResults':'noNotes')}</div>`}</div></aside><section class="note-editor-pro">${note?`<div class="app-commandbar"><button data-note-pin class="${note.pinned?'active':''}" aria-label="${i18n.t('pinNote')}">${icon('star',15)}</button><button data-note-delete aria-label="${i18n.t('delete')}">${icon('delete',15)}</button><div class="toolbar-spacer"></div><button data-note-ask title="${i18n.t('askAeris')}">${icon('aerisAi',15)} ${i18n.t('askAeris')}</button><span data-note-status>${i18n.t('saved')}</span><button data-note-save>${icon('check',15)} ${i18n.t('save')}</button></div><div class="note-paper"><input data-note-title value="${esc(note.title)}" aria-label="${i18n.t('noteTitle')}"><time>${new Intl.DateTimeFormat(i18n.t('dateFormat'),{dateStyle:'medium',timeStyle:'short'}).format(note.updatedAt)}</time><textarea data-note-content spellcheck="true" placeholder="${i18n.t('writeNote')}">${esc(note.content||'')}</textarea></div><footer class="app-statusbar"><span data-note-count>${i18n.t('wordCount').replace('{count}',note.content.trim()?note.content.trim().split(/\s+/).length:0)}</span><span>${i18n.t('localAccount')}</span></footer>`:`<div class="empty-state">${icon('note',36)}<span>${i18n.t('noNotes')}</span><button data-note-new>${i18n.t('newNote')}</button></div>`}</section></div>`;
      root.querySelectorAll('[data-notes-folder]').forEach(button=>button.onclick=()=>{folder=button.dataset.notesFolder;selectedId=visible()[0]?.id||null;render()});root.querySelector('[data-notes-search]').oninput=event=>{query=event.target.value;render();requestAnimationFrame(()=>{const input=root.querySelector('[data-notes-search]');input?.focus();input?.setSelectionRange(query.length,query.length)})};root.querySelectorAll('[data-note]').forEach(button=>button.onclick=async()=>{await commit();selectedId=button.dataset.note;render()});root.querySelectorAll('[data-note-new]').forEach(button=>button.onclick=async()=>{await commit();const item={id:crypto.randomUUID(),title:i18n.t('untitledNote'),content:'',pinned:false,updatedAt:Date.now()};notes.unshift(item);selectedId=item.id;await persist();render();setTimeout(()=>root.querySelector('[data-note-title]')?.select())});root.querySelector('[data-note-pin]')?.addEventListener('click',async()=>{note.pinned=!note.pinned;note.updatedAt=Date.now();await persist();render()});root.querySelector('[data-note-save]')?.addEventListener('click',async()=>{await commit();render()});root.querySelector('[data-note-ask]')?.addEventListener('click',askAeris);root.querySelector('[data-note-delete]')?.addEventListener('click',async()=>{const approved=await dialog.confirm({title:i18n.t('deleteNote'),message:i18n.t('deleteNoteConfirm').replace('{name}',note.title),confirmLabel:i18n.t('delete'),danger:true});if(!approved)return;notes=notes.filter(item=>item.id!==note.id);selectedId=visible()[0]?.id||null;await persist();render()});root.querySelector('[data-note-title]')?.addEventListener('input',()=>{schedule();reportContext()});const editor=root.querySelector('[data-note-content]');editor?.addEventListener('input',()=>{schedule();reportContext()});editor?.addEventListener('select',reportContext);editor?.addEventListener('mouseup',reportContext);reportContext()};
    const keydown=event=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='s'){event.preventDefault();commit().then(render)}};root.addEventListener('keydown',keydown);userdata.load('notes',null).then(items=>{notes=Array.isArray(items)?items.map(item=>({...item,pinned:!!item.pinned})):[{id:crypto.randomUUID(),title:'Aeris',content:i18n.t('welcomeNote'),pinned:true,updatedAt:Date.now()}];selectedId=notes[0]?.id||null;persist();render()});render();return()=>{clearTimeout(saveTimer);commit();root.removeEventListener('keydown',keydown)};
  }
};
