import {icon} from '../../icons.js';
const fmt=size=>size?`${(size/1048576).toFixed(1)} MB`:'—';
export default{
  id:'machine',title:'machine',icon:'vm',color:'violet',width:1040,height:680,singleInstance:true,
  mount(root,{machine,system,settings,i18n,kernel,dialog}){
    const device=document.querySelector('#guest-screen-persistent'),home=document.querySelector('#device-layer');let page='overview',saved=null,timer=null;
    const stateLabel=()=>i18n.t(machine.status==='running'?'running':machine.status==='booting'?'booting':machine.status==='paused'?'paused':'stopped');
    const sidebar=()=>`<aside class="machine-sidebar"><header><span>${icon('logo',22)}</span><strong>${i18n.t('systemInformation')}</strong></header><nav>${[['overview','info'],['hardware','memory'],['storage','disk'],['network','wifi'],['console','display']].map(([id,glyph])=>`<button data-machine-page="${id}" class="${page===id?'selected':''}">${icon(glyph,16)}<span>${i18n.t(id)}</span></button>`).join('')}</nav><footer><span class="machine-live status-${machine.status}"></span><div><strong>Aeris Computer</strong><small>${stateLabel()}</small></div></footer></aside>`;
    const specs=()=>`<dl class="machine-specs"><div><dt>${i18n.t('modelName')}</dt><dd>Aeris Virtual Computer</dd></div><div><dt>${i18n.t('processor')}</dt><dd>v86 WebAssembly · i686</dd></div><div><dt>${i18n.t('memory')}</dt><dd>${settings.get('memory')} MB</dd></div><div><dt>${i18n.t('startupDisk')}</dt><dd>Aeris Linux</dd></div><div><dt>${i18n.t('serialNumber')}</dt><dd>AERIS-WEB-${String(settings.get('memory')).padStart(4,'0')}</dd></div><div><dt>${i18n.t('systemVersion')}</dt><dd>Aeris 0.5 · Alpine Linux 3.24</dd></div></dl>`;
    const content=()=>{if(page==='overview')return`<main class="machine-overview"><section class="machine-hero"><span class="machine-mark">${icon('logo',70)}</span><div><h1>Aeris</h1><p>${i18n.t('aerisVersion')}</p><span class="machine-status-pill status-${machine.status}"><i></i>${stateLabel()}</span></div></section>${specs()}<div class="machine-actions"><button data-machine="details">${i18n.t('systemReport')}</button><button data-machine="restart">${i18n.t('restart')}</button></div></main>`;
      if(page==='hardware')return`<main class="machine-page"><header><span>${icon('memory',28)}</span><div><h1>${i18n.t('hardware')}</h1><p>${i18n.t('hardwareCopy')}</p></div></header>${specs()}<section class="machine-stat-grid"><article><small>${i18n.t('instructions')}</small><strong data-machine-instructions>${machine.instructionCount().toLocaleString()}</strong></article><article><small>${i18n.t('uptime')}</small><strong data-machine-uptime>00:00:00</strong></article><article><small>${i18n.t('architecture')}</small><strong>32-bit x86</strong></article><article><small>${i18n.t('engine')}</small><strong>v86 / WASM</strong></article></section></main>`;
      if(page==='storage')return`<main class="machine-page"><header><span>${icon('disk',28)}</span><div><h1>${i18n.t('storage')}</h1><p>${i18n.t('storageCopy')}</p></div></header><section class="machine-storage-card"><div class="machine-disk-icon">${icon('disk',40)}</div><div><h2>Aeris Linux</h2><p>Persistent browser disk image</p></div><strong>${fmt(saved?.size)}</strong><i><span style="width:${saved?.size?68:4}%"></span></i><footer><span>${i18n.t('savedSystem')}</span><b>${saved?.updatedAt?new Intl.DateTimeFormat(i18n.t('dateFormat'),{dateStyle:'medium',timeStyle:'short'}).format(saved.updatedAt):i18n.t('notSaved')}</b></footer></section><p class="machine-note">${i18n.t('persistenceDetail')}</p></main>`;
      if(page==='network'){const net=system.networkState;return`<main class="machine-page"><header><span>${icon('wifi',28)}</span><div><h1>${i18n.t('network')}</h1><p>${i18n.t('networkDetailCopy')}</p></div></header><section class="machine-network-card"><header><span>${icon('globe',26)}</span><div><strong>Ethernet</strong><small>virtio-net · eth0</small></div><b class="network-${net.status}"><i></i>${i18n.t(net.status==='connected'?'connected':net.status==='connecting'?'connecting':'offline')}</b></header><dl><div><dt>${i18n.t('ipAddress')}</dt><dd>${net.address||'—'}</dd></div><div><dt>${i18n.t('gateway')}</dt><dd>${net.gateway||'—'}</dd></div><div><dt>${i18n.t('dnsServer')}</dt><dd>${net.dns||'—'}</dd></div></dl><button data-machine="network">${icon('refresh',14)} ${i18n.t('reconnect')}</button></section></main>`}
      return`<main class="machine-console"><div class="app-commandbar"><span class="machine-live status-${machine.status}"></span><strong>${stateLabel()}</strong><div class="toolbar-spacer"></div><button data-machine="start">${icon('play',14)} ${i18n.t('powerOn')}</button><button data-machine="pause">${icon('pause',14)} ${i18n.t(machine.status==='paused'?'resume':'pause')}</button><button data-machine="restart">${icon('refresh',14)} ${i18n.t('restart')}</button><button data-machine="stop">${icon('power',14)} ${i18n.t('powerOff')}</button></div><div class="guest-display-slot"></div><footer><span>Alpine Linux 3.24</span><span>VGA · WebAssembly</span></footer></main>`};
    const draw=()=>{if(page!=='console'){device.hidden=true;home.appendChild(device)}root.innerHTML=`<div class="system-app machine-detail">${sidebar()}<section class="machine-content">${content()}</section></div>`;if(page==='console'){root.querySelector('.guest-display-slot').appendChild(device);device.hidden=false}bind();updateStats()};
    const confirm=async action=>{if(!await dialog.confirm({title:i18n.t(action),message:i18n.t(`${action}MachineCopy`),confirmLabel:i18n.t(action),danger:action==='powerOff'}))return;if(action==='restart')machine.restart();else machine.stop()};
    const bind=()=>{root.querySelectorAll('[data-machine-page]').forEach(button=>button.onclick=()=>{page=button.dataset.machinePage;draw()});root.querySelectorAll('[data-machine]').forEach(button=>button.onclick=()=>{const action=button.dataset.machine;if(action==='start')machine.start();if(action==='pause')machine.status==='paused'?machine.resume():machine.pause();if(action==='restart')confirm('restart');if(action==='stop')confirm('powerOff');if(action==='details'){page='hardware';draw()}if(action==='network')system.ensureNetwork({updateRepositories:false}).catch(()=>{})})};
    const updateStats=()=>{const seconds=Math.floor(machine.uptime()/1000),time=`${String(Math.floor(seconds/3600)).padStart(2,'0')}:${String(Math.floor(seconds%3600/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;root.querySelector('[data-machine-uptime]')?.replaceChildren(time);root.querySelector('[data-machine-instructions]')?.replaceChildren(machine.instructionCount().toLocaleString())};
    const offStatus=kernel.bus.on('machine:status',draw),offNetwork=kernel.bus.on('network:change',()=>{if(page==='network')draw()});machine.persistenceInfo().then(info=>{saved=info;draw()}).catch(()=>{});timer=setInterval(updateStats,1000);draw();return()=>{offStatus();offNetwork();clearInterval(timer);device.hidden=true;home.appendChild(device)}
  }
};
