import {icon} from '../../icons.js';
import './browser.css';
import './automation.css';

const esc=value=>String(value??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const host=url=>{try{return new URL(url).hostname.replace(/^www\./,'')}catch{return''}};
const remoteUrl=url=>/^https?:/i.test(url)?url:'';
const dataUrl=image=>image?.data?`data:${image.mimeType||'image/jpeg'};base64,${image.data}`:'';

export default{
  id:'browser',title:'webBrowser',icon:'browser',color:'blue',width:1120,height:720,singleInstance:true,
  mount(root,{browser,browserAutomation,clipboard,i18n,kernel,agentContext,agentEntry,shell}){
    let panel='',loading=false,view=null,browserError='',destroyed=false,wheelTimer=0,wheelDelta=0,streamOff=null;
    const state=()=>browser.snapshot(),active=()=>browser.active(),home=()=>!remoteUrl(active()?.url);
    const reportContext=()=>{const tab=active();if(!tab)return;agentContext.set({appId:'browser',label:tab.title||i18n.t('webBrowser'),resource:{kind:'webpage',id:tab.id,uri:tab.url,name:tab.title,metadata:{url:tab.url,title:tab.title,host:host(tab.url),readable:browserAutomation.snapshot().state==='ready',source:'browser-use'}}})};
    const automationStatus=()=>{const status=browserAutomation.snapshot(),key=['connecting','ready','failed'].includes(status.state)?status.state:'idle';return`<span class="browser-automation-status ${key}" data-browser-automation-status><i></i>${i18n.t(`browserAutomation_${key}`)}</span>`};
    const errorMarkup=()=>`<aside class="browser-inline-error" data-browser-error data-copyable ${browserError?'':'hidden'}><span>${icon('warning',15)}</span><p data-browser-error-text>${esc(browserError)}</p><button data-browser-copy-error title="${i18n.t('copyError')}">${icon('copy',13)}</button><button data-browser-dismiss-error title="${i18n.t('dismiss')}">${icon('close',11)}</button></aside>`;
    const showError=error=>{browserError=String(error?.message||error||i18n.t('browserAutomation_failed'));const banner=root.querySelector('[data-browser-error]');if(!banner)return;banner.hidden=false;banner.querySelector('[data-browser-error-text]').textContent=browserError};
    const clearError=()=>{browserError='';const banner=root.querySelector('[data-browser-error]');if(banner)banner.hidden=true};
    const panelMarkup=value=>{const s=state(),items=value==='bookmarks'?s.bookmarks:s.history;return`<aside class="browser-library"><header><div><strong>${i18n.t(value==='bookmarks'?'bookmarks':'history')}</strong><small>${i18n.t(value==='bookmarks'?'browserBookmarksCopy':'browserHistoryCopy')}</small></div>${value==='history'&&items.length?`<button data-browser-clear-history>${i18n.t('clear')}</button>`:''}<button data-browser-close-panel>${icon('close',12)}</button></header><div>${items.length?items.map(item=>`<article><button data-browser-library-url="${esc(item.url)}"><span class="browser-site-icon">${esc((host(item.url)[0]||'•').toUpperCase())}</span><span><strong>${esc(item.title||host(item.url))}</strong><small>${esc(item.url)}</small></span></button>${value==='bookmarks'?`<button data-browser-remove-bookmark="${esc(item.id)}" title="${i18n.t('remove')}">${icon('close',10)}</button>`:''}</article>`).join(''):`<div class="browser-library-empty">${icon(value==='bookmarks'?'star':'history',26)}<strong>${i18n.t(value==='bookmarks'?'noBookmarks':'noBrowserHistory')}</strong></div>`}</div></aside>`};
    const remoteMarkup=()=>`<div class="browser-remote-view ${loading||!view?.screenshot?'loading':''}" data-browser-remote tabindex="0"><div class="browser-loading"><i></i><span>${esc(loading?i18n.t('browserConnectingView'):host(active()?.url))}</span></div>${view?.screenshot?`<img data-browser-image src="${dataUrl(view.screenshot)}" alt="${esc(view.title||active()?.title)}" draggable="false">`:''}<span class="browser-remote-hint">${i18n.t('browserRemoteHint')}</span></div>`;
    const draw=()=>{
      const s=state(),tab=active(),isHome=home(),bookmarked=tab?browser.isBookmarked(tab.url):false;
      root.innerHTML=`<div class="system-app aeris-browser ${panel?'has-library':''}"><div class="browser-tabbar"><div class="browser-tabs">${s.tabs.map(item=>`<button class="browser-tab ${item.id===s.activeTabId?'selected':''}" data-browser-tab="${esc(item.id)}"><span class="browser-tab-favicon">${item.url==='about:blank'?icon('browser',12):esc((host(item.url)[0]||'•').toUpperCase())}</span><strong>${esc(item.title||i18n.t('newTab'))}</strong><i data-browser-close-tab="${esc(item.id)}" title="${i18n.t('close')}">${icon('close',9)}</i></button>`).join('')}</div><button data-browser-new-tab title="${i18n.t('newTab')}">${icon('plus',13)}</button></div><div class="browser-navigation"><nav><button data-browser-back title="${i18n.t('back')}">${icon('back',14)}</button><button data-browser-forward title="${i18n.t('forward')}">${icon('chevron',14)}</button><button data-browser-reload title="${i18n.t('refresh')}">${icon('refresh',14)}</button></nav><form data-browser-address><label>${icon(tab?.url?.startsWith('https:')?'lock':'globe',13)}<input value="${esc(isHome?'':tab.url)}" placeholder="${i18n.t('browserAddressPlaceholder')}" autocomplete="off" autocapitalize="off" spellcheck="false"></label></form><nav><button data-browser-bookmark class="${bookmarked?'selected':''}" title="${i18n.t('bookmarkPage')}">${icon('star',14)}</button><button data-browser-panel="history" class="${panel==='history'?'selected':''}" title="${i18n.t('history')}">${icon('history',14)}</button><button data-browser-panel="bookmarks" class="${panel==='bookmarks'?'selected':''}" title="${i18n.t('bookmarks')}">${icon('list',14)}</button><button data-browser-ask title="${i18n.t('askAeris')}">${icon('aerisAi',14)}</button></nav></div><main class="browser-stage">${isHome?`<section class="browser-start"><span>${icon('browser',38)}</span><h1>${i18n.t('browseTheWeb')}</h1><p>${i18n.t('browserNodeCopy')}</p><form data-browser-start-search><label>${icon('search',15)}<input placeholder="${i18n.t('browserAddressPlaceholder')}" autocomplete="off" spellcheck="false"></label></form><div><button data-browser-quick="https://example.com">Example</button><button data-browser-quick="https://wikipedia.org">Wikipedia</button><button data-browser-quick="https://developer.mozilla.org">MDN</button></div></section>`:remoteMarkup()}${panel?panelMarkup(panel):''}${errorMarkup()}</main><footer><span data-browser-view-host>${isHome?i18n.t('newTab'):esc(host(view?.url||tab.url))}</span>${automationStatus()}<span>${i18n.t('browserRemoteRuntime')}</span></footer></div>`;
      bind();reportContext();if(!isHome)ensureStream();
    };
    const updateStatus=()=>{const current=root.querySelector('[data-browser-automation-status]');if(!current)return;const template=document.createElement('template');template.innerHTML=automationStatus();current.replaceWith(template.content.firstElementChild);reportContext()};
    const updateView=result=>{
      if(!result||destroyed)return;view=result;loading=false;
      const image=root.querySelector('[data-browser-image]'),source=dataUrl(result.screenshot);if(image&&source)image.src=source;else if(!home())draw();
      root.querySelector('[data-browser-remote]')?.classList.remove('loading');const hostLabel=root.querySelector('[data-browser-view-host]');if(hostLabel)hostLabel.textContent=host(result.url);
      const tab=active();if(result.title&&tab&&result.title!==tab.title)browser.updateTitle(tab.id,result.title);
      if(result.url&&remoteUrl(result.url)&&tab&&result.url!==tab.url)browser.navigate(result.url,{replace:true});reportContext();
    };
    const ensureStream=()=>{if(!streamOff&&!destroyed)streamOff=browserAutomation.subscribe(message=>{if(message.type==='frame'||message.type==='navigation')updateView(message)})};
    const navigate=async value=>{panel='';loading=true;view=null;browserError='';try{const tab=browser.navigate(value);draw();updateView(await browserAutomation.navigate(tab.url))}catch(error){loading=false;browserError=error.message;draw()}};
    const history=async direction=>{if(home())return;loading=true;browserError='';try{const local=direction==='forward'?browser.forward():browser.back();draw();const result=await browserAutomation.history(direction);updateView(result);if(result.url&&result.url!==local.url)browser.navigate(result.url,{replace:true})}catch(error){loading=false;browserError=error.message;draw()}};
    const reload=async()=>{if(home())return;loading=true;browserError='';draw();try{updateView(await browserAutomation.reload())}catch(error){loading=false;browserError=error.message;draw()}};
    const closeTab=async id=>{const closingActive=active()?.id===id;if(closingActive){loading=true;view=null;browserError=''}browser.close(id);if(!closingActive)return;const tab=active();if(home()&&browserAutomation.snapshot().state!=='ready'){loading=false;draw();return}try{updateView(await browserAutomation.navigate(tab.url))}catch(error){loading=false;browserError=error.message;draw()}};
    const point=event=>{const target=event.currentTarget,rect=target.getBoundingClientRect(),viewport=view?.viewport||{width:1280,height:720};return{x:(event.clientX-rect.left)/rect.width*viewport.width,y:(event.clientY-rect.top)/rect.height*viewport.height}};
    const bindRemote=()=>{const remote=root.querySelector('[data-browser-remote]');if(!remote)return;remote.onclick=event=>{remote.focus();browserAutomation.pointer({...point(event),type:'click'}).catch(showError)};remote.onwheel=event=>{event.preventDefault();const position=point(event);wheelDelta+=event.deltaY;clearTimeout(wheelTimer);wheelTimer=setTimeout(()=>{browserAutomation.pointer({...position,type:'scroll',deltaY:wheelDelta}).catch(showError);wheelDelta=0},55)};remote.onkeydown=event=>{if(event.metaKey||event.ctrlKey||event.altKey)return;const supported=event.key.length===1||['Enter','Backspace','Tab','Escape','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Delete'].includes(event.key);if(!supported)return;event.preventDefault();browserAutomation.key(event.key.length===1?{key:event.key,text:event.key}:{key:event.key}).catch(showError)}};
    const bind=()=>{
      root.querySelectorAll('[data-browser-tab]').forEach(button=>button.onclick=event=>{if(event.target.closest('[data-browser-close-tab]'))return;browser.select(button.dataset.browserTab);const tab=active();if(remoteUrl(tab?.url)){loading=true;view=null;browserError='';draw();browserAutomation.navigate(tab.url).then(updateView).catch(error=>{loading=false;browserError=error.message;draw()})}});
      root.querySelectorAll('[data-browser-close-tab]').forEach(button=>button.onclick=event=>{event.stopPropagation();closeTab(button.dataset.browserCloseTab)});root.querySelector('[data-browser-new-tab]')?.addEventListener('click',()=>{loading=false;view=null;panel='';browser.newTab()});
      root.querySelector('[data-browser-back]')?.addEventListener('click',()=>history('back'));root.querySelector('[data-browser-forward]')?.addEventListener('click',()=>history('forward'));root.querySelector('[data-browser-reload]')?.addEventListener('click',reload);
      root.querySelector('[data-browser-address]')?.addEventListener('submit',event=>{event.preventDefault();navigate(event.currentTarget.querySelector('input').value)});root.querySelector('[data-browser-start-search]')?.addEventListener('submit',event=>{event.preventDefault();navigate(event.currentTarget.querySelector('input').value)});root.querySelectorAll('[data-browser-quick]').forEach(button=>button.onclick=()=>navigate(button.dataset.browserQuick));
      root.querySelector('[data-browser-bookmark]')?.addEventListener('click',()=>browser.toggleBookmark());root.querySelectorAll('[data-browser-panel]').forEach(button=>button.onclick=()=>{panel=panel===button.dataset.browserPanel?'':button.dataset.browserPanel;draw()});root.querySelector('[data-browser-close-panel]')?.addEventListener('click',()=>{panel='';draw()});root.querySelectorAll('[data-browser-library-url]').forEach(button=>button.onclick=()=>navigate(button.dataset.browserLibraryUrl));root.querySelectorAll('[data-browser-remove-bookmark]').forEach(button=>button.onclick=()=>browser.removeBookmark(button.dataset.browserRemoveBookmark));root.querySelector('[data-browser-clear-history]')?.addEventListener('click',()=>browser.clearHistory());
      root.querySelector('[data-browser-copy-error]')?.addEventListener('click',async event=>{event.stopPropagation();if(await clipboard.copyText(browserError))shell.toast(i18n.t('copiedToClipboard'))});root.querySelector('[data-browser-dismiss-error]')?.addEventListener('click',event=>{event.stopPropagation();clearError()});
      root.querySelector('[data-browser-ask]')?.addEventListener('click',()=>{reportContext();agentEntry.open({prompt:i18n.t('askAerisWebPrompt'),source:'browser'})});bindRemote();
    };
    const off=kernel.bus.on('browser:changed',draw),offAutomation=kernel.bus.on('browser-automation:changed',updateStatus);draw();
    if(!home()){loading=true;browserAutomation.navigate(active().url).then(updateView).catch(error=>{loading=false;browserError=error.message;draw()})}
    return async()=>{destroyed=true;streamOff?.();clearTimeout(wheelTimer);off();offAutomation();browser.resetSession();await browserAutomation.disconnect()};
  }
};
