import {icon} from '../../icons.js';
import './browser.css';
import './automation.css';

const esc=value=>String(value??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const host=url=>{try{return new URL(url).hostname.replace(/^www\./,'')}catch{return''}};
const safeUrl=url=>/^https?:/i.test(url)?url:'';

export default{
  id:'browser',title:'webBrowser',icon:'browser',color:'blue',width:1120,height:720,singleInstance:true,
  mount(root,{browser,browserAutomation,i18n,kernel,agentContext,agentEntry,shell}){
    let panel='',loading=false,loadTimer=0;
    const state=()=>browser.snapshot(),active=()=>browser.active();
    const reportContext=()=>{const tab=active();if(!tab)return;agentContext.set({appId:'browser',label:tab.title||i18n.t('webBrowser'),resource:{kind:'webpage',id:tab.id,uri:tab.url,name:tab.title,metadata:{url:tab.url,title:tab.title,host:host(tab.url),readable:false}}})};
    const panelMarkup=value=>{const s=state(),items=value==='bookmarks'?s.bookmarks:s.history;return`<aside class="browser-library"><header><div><strong>${i18n.t(value==='bookmarks'?'bookmarks':'history')}</strong><small>${i18n.t(value==='bookmarks'?'browserBookmarksCopy':'browserHistoryCopy')}</small></div>${value==='history'&&items.length?`<button data-browser-clear-history>${i18n.t('clear')}</button>`:''}<button data-browser-close-panel>${icon('close',12)}</button></header><div>${items.length?items.map(item=>`<article><button data-browser-library-url="${esc(item.url)}"><span class="browser-site-icon">${esc((host(item.url)[0]||'•').toUpperCase())}</span><span><strong>${esc(item.title||host(item.url))}</strong><small>${esc(item.url)}</small></span></button>${value==='bookmarks'?`<button data-browser-remove-bookmark="${esc(item.id)}" title="${i18n.t('remove')}">${icon('close',10)}</button>`:''}</article>`).join(''):`<div class="browser-library-empty">${icon(value==='bookmarks'?'star':'history',26)}<strong>${i18n.t(value==='bookmarks'?'noBookmarks':'noBrowserHistory')}</strong></div>`}</div></aside>`};
    const automationStatus=()=>{const status=browserAutomation.snapshot(),key=['connecting','ready','failed'].includes(status.state)?status.state:'idle';return`<span class="browser-automation-status ${key}" data-browser-automation-status><i></i>${i18n.t(`browserAutomation_${key}`)}</span>`};
    const updateAutomationStatus=()=>{const current=root.querySelector('[data-browser-automation-status]');if(!current)return;const template=document.createElement('template');template.innerHTML=automationStatus();current.replaceWith(template.content.firstElementChild)};
    const draw=()=>{const s=state(),tab=active(),home=!safeUrl(tab?.url),bookmarked=tab?browser.isBookmarked(tab.url):false;
      root.innerHTML=`<div class="system-app aeris-browser ${panel?'has-library':''}"><div class="browser-tabbar"><div class="browser-tabs">${s.tabs.map(item=>`<button class="browser-tab ${item.id===s.activeTabId?'selected':''}" data-browser-tab="${esc(item.id)}"><span class="browser-tab-favicon">${item.url==='about:blank'?icon('browser',12):esc((host(item.url)[0]||'•').toUpperCase())}</span><strong>${esc(item.title||i18n.t('newTab'))}</strong>${s.tabs.length>1?`<i data-browser-close-tab="${esc(item.id)}">${icon('close',9)}</i>`:''}</button>`).join('')}</div><button data-browser-new-tab title="${i18n.t('newTab')}">${icon('plus',13)}</button></div><div class="browser-navigation"><nav><button data-browser-back ${tab?.entryIndex>0?'':'disabled'} title="${i18n.t('back')}">${icon('back',14)}</button><button data-browser-forward ${tab&&tab.entryIndex<tab.entries.length-1?'':'disabled'} title="${i18n.t('forward')}">${icon('chevron',14)}</button><button data-browser-reload title="${i18n.t('refresh')}">${icon(loading?'stopSquare':'refresh',14)}</button></nav><form data-browser-address><label>${icon(tab?.url?.startsWith('https:')?'lock':'globe',13)}<input value="${esc(home?'':tab.url)}" placeholder="${i18n.t('browserAddressPlaceholder')}" autocomplete="off" autocapitalize="off" spellcheck="false"></label></form><nav><button data-browser-bookmark class="${bookmarked?'selected':''}" title="${i18n.t('bookmarkPage')}">${icon('star',14)}</button><button data-browser-panel="history" class="${panel==='history'?'selected':''}" title="${i18n.t('history')}">${icon('history',14)}</button><button data-browser-panel="bookmarks" class="${panel==='bookmarks'?'selected':''}" title="${i18n.t('bookmarks')}">${icon('list',14)}</button><button data-browser-ask title="${i18n.t('askAeris')}">${icon('aerisAi',14)}</button></nav></div><main class="browser-stage">${home?`<section class="browser-start"><span>${icon('browser',38)}</span><h1>${i18n.t('browseTheWeb')}</h1><p>${i18n.t('browserPrivacyCopy')}</p><form data-browser-start-search><label>${icon('search',15)}<input placeholder="${i18n.t('browserAddressPlaceholder')}" autocomplete="off" spellcheck="false"></label></form><div><button data-browser-quick="https://example.com">Example</button><button data-browser-quick="https://wikipedia.org">Wikipedia</button><button data-browser-quick="https://developer.mozilla.org">MDN</button></div></section>`:`<div class="browser-frame-wrap ${loading?'loading':''}"><div class="browser-loading"><i></i><span>${esc(host(tab.url))}</span></div><iframe data-browser-frame title="${esc(tab.title)}" src="${esc(tab.url)}" sandbox="allow-downloads allow-forms allow-modals allow-popups allow-popups-to-escape-sandbox allow-same-origin allow-scripts" referrerpolicy="strict-origin-when-cross-origin"></iframe></div>`}${panel?panelMarkup(panel):''}</main><footer><span>${home?i18n.t('newTab'):esc(host(tab.url))}</span>${automationStatus()}<span>${i18n.t('browserExperimentalCopy')}</span></footer></div>`;
      bind();reportContext();
    };
    const navigate=value=>{try{loading=true;browser.navigate(value);panel=''}catch(error){loading=false;shell.toast(error.message)}};
    const bind=()=>{
      root.querySelectorAll('[data-browser-tab]').forEach(button=>button.onclick=event=>{if(event.target.closest('[data-browser-close-tab]'))return;browser.select(button.dataset.browserTab)});
      root.querySelectorAll('[data-browser-close-tab]').forEach(button=>button.onclick=event=>{event.stopPropagation();browser.close(button.dataset.browserCloseTab)});
      root.querySelector('[data-browser-new-tab]')?.addEventListener('click',()=>{loading=false;panel='';browser.newTab()});
      root.querySelector('[data-browser-back]')?.addEventListener('click',()=>{loading=true;browser.back()});root.querySelector('[data-browser-forward]')?.addEventListener('click',()=>{loading=true;browser.forward()});root.querySelector('[data-browser-reload]')?.addEventListener('click',()=>{loading=true;browser.reload()});
      root.querySelector('[data-browser-address]')?.addEventListener('submit',event=>{event.preventDefault();navigate(event.currentTarget.querySelector('input').value)});root.querySelector('[data-browser-start-search]')?.addEventListener('submit',event=>{event.preventDefault();navigate(event.currentTarget.querySelector('input').value)});root.querySelectorAll('[data-browser-quick]').forEach(button=>button.onclick=()=>navigate(button.dataset.browserQuick));
      root.querySelector('[data-browser-bookmark]')?.addEventListener('click',()=>browser.toggleBookmark());root.querySelectorAll('[data-browser-panel]').forEach(button=>button.onclick=()=>{panel=panel===button.dataset.browserPanel?'':button.dataset.browserPanel;draw()});root.querySelector('[data-browser-close-panel]')?.addEventListener('click',()=>{panel='';draw()});
      root.querySelectorAll('[data-browser-library-url]').forEach(button=>button.onclick=()=>navigate(button.dataset.browserLibraryUrl));root.querySelectorAll('[data-browser-remove-bookmark]').forEach(button=>button.onclick=()=>browser.removeBookmark(button.dataset.browserRemoveBookmark));root.querySelector('[data-browser-clear-history]')?.addEventListener('click',()=>browser.clearHistory());
      root.querySelector('[data-browser-ask]')?.addEventListener('click',()=>{reportContext();agentEntry.open({prompt:i18n.t('askAerisWebPrompt'),source:'browser'})});
      const frame=root.querySelector('[data-browser-frame]');if(frame){clearTimeout(loadTimer);loadTimer=setTimeout(()=>{loading=false;root.querySelector('.browser-frame-wrap')?.classList.remove('loading')},12000);frame.onload=()=>{clearTimeout(loadTimer);loading=false;root.querySelector('.browser-frame-wrap')?.classList.remove('loading');try{const url=frame.contentWindow.location.href,title=frame.contentDocument.title;if(url&&url!==active()?.url)browser.navigate(url,{replace:true});else if(title)browser.updateTitle(active().id,title)}catch{}reportContext()}}
    };
    const off=kernel.bus.on('browser:changed',()=>draw()),offAutomation=kernel.bus.on('browser-automation:changed',updateAutomationStatus);draw();return()=>{clearTimeout(loadTimer);off();offAutomation()};
  }
};
