import { icon } from '../../icons.js';
export default{
  id:'textedit',title:'textEditor',icon:'textedit',color:'blue',width:900,height:620,singleInstance:true,
  mount(root,{system,kernel,dialog,i18n,launchOptions}){
    let path=launchOptions.path||'/home/aeris/Documents/Untitled.txt',dirty=false,wrap=true;
    root.innerHTML=`<div class="system-app textedit-pro"><div class="app-commandbar"><div class="toolbar-cluster"><button data-text-new aria-label="${i18n.t('newDocument')}">${icon('plus',15)}</button><button data-text-open aria-label="${i18n.t('open')}">${icon('folder',15)}</button><button data-text-save aria-label="${i18n.t('save')}">${icon('check',15)}</button></div><strong data-text-path></strong><div class="toolbar-spacer"></div><label class="app-search text-find">${icon('search',14)}<input data-text-find placeholder="${i18n.t('find')}"></label><button data-text-wrap class="selected">${i18n.t('wrap')}</button><button data-text-save-as>${i18n.t('saveAs')}</button></div><div class="text-formatbar"><label>${i18n.t('font')}<select data-text-font><option value="Georgia,serif">Serif</option><option value="Manrope,sans-serif">Sans</option><option value="DM Mono,monospace">Mono</option></select></label><label>${i18n.t('fontSize')}<select data-text-size>${[11,12,13,14,16,18,20,24].map(size=>`<option ${size===14?'selected':''}>${size}</option>`).join('')}</select></label><span></span><em data-text-status></em></div><main class="text-paper"><textarea data-text-content spellcheck="true" wrap="soft"></textarea></main><footer class="app-statusbar"><span data-text-count></span><span data-text-location></span></footer></div>`;
    const area=root.querySelector('[data-text-content]'),status=root.querySelector('[data-text-status]'),label=root.querySelector('[data-text-path]'),count=root.querySelector('[data-text-count]'),location=root.querySelector('[data-text-location]');
    const updateMeta=()=>{const words=area.value.trim()?area.value.trim().split(/\s+/).length:0;count.textContent=i18n.t('documentStats').replace('{words}',words).replace('{characters}',area.value.length);location.textContent=path};
    const setStatus=(key,error=false)=>{status.textContent=i18n.t(key)||key;status.classList.toggle('error',error);label.textContent=`${path.split('/').at(-1)}${dirty?' •':''}`;updateMeta()};
    const load=async next=>{if(!system.ready){setStatus('startMachine',true);return}path=next;setStatus('opening');try{area.value=await system.read(path);dirty=false;setStatus('saved')}catch(error){area.value='';setStatus(error.message,true)}};
    const save=async()=>{if(!system.ready)return setStatus('startMachine',true);setStatus('saving');try{await system.write(path,area.value);dirty=false;setStatus('saved')}catch(error){setStatus(error.message,true)}};
    const choosePath=async()=>{const name=await dialog.prompt({title:i18n.t('saveAs'),value:path.split('/').at(-1),placeholder:'Document.txt',validate:value=>!value||value.includes('/')?i18n.t('invalidName'):''});if(!name)return false;path=`/home/aeris/Documents/${name}`;return true};
    root.querySelector('[data-text-save]').onclick=save;root.querySelector('[data-text-save-as]').onclick=async()=>{if(await choosePath())await save()};root.querySelector('[data-text-new]').onclick=async()=>{if(dirty&&!await dialog.confirm({title:i18n.t('newDocument'),message:i18n.t('discardChanges'),confirmLabel:i18n.t('continue'),danger:true}))return;path='/home/aeris/Documents/Untitled.txt';area.value='';dirty=false;setStatus('saved');area.focus()};root.querySelector('[data-text-open]').onclick=async()=>{const next=await dialog.prompt({title:i18n.t('open'),value:path,placeholder:'/home/aeris/Documents/file.txt',validate:value=>value.startsWith('/')?'':i18n.t('invalidPath')});if(next)await load(next)};root.querySelector('[data-text-font]').onchange=event=>area.style.fontFamily=event.target.value;root.querySelector('[data-text-size]').onchange=event=>area.style.fontSize=`${event.target.value}px`;root.querySelector('[data-text-wrap]').onclick=event=>{wrap=!wrap;area.wrap=wrap?'soft':'off';event.currentTarget.classList.toggle('selected',wrap)};root.querySelector('[data-text-find]').onkeydown=event=>{if(event.key!=='Enter'||!event.target.value)return;const at=area.value.toLowerCase().indexOf(event.target.value.toLowerCase(),area.selectionEnd);const found=at>=0?at:area.value.toLowerCase().indexOf(event.target.value.toLowerCase());if(found>=0){area.focus();area.setSelectionRange(found,found+event.target.value.length)}};area.oninput=()=>{dirty=true;setStatus('edited')};
    const keydown=event=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='s'){event.preventDefault();save()}if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='f'){event.preventDefault();root.querySelector('[data-text-find]').focus()}};root.addEventListener('keydown',keydown);const offOpen=kernel.bus.on('textedit:open',load),offReady=kernel.bus.on('guest:ready',()=>{if(launchOptions.path)load(path)});if(system.ready&&launchOptions.path)load(path);setStatus('saved');area.focus();return()=>{offOpen();offReady();root.removeEventListener('keydown',keydown)}
  }
};
