import {icon} from '../../icons.js';
const TRASH='/home/future/.local/share/Trash/files';
const esc=value=>String(value??'').replace(/&/g,'&amp;').replace(/</g,'&lt;');
const fmt=size=>size>1048576?`${(size/1048576).toFixed(1)} MB`:size>1024?`${Math.ceil(size/1024)} KB`:`${size} B`;
export default{
  id:'trash',title:'trash',icon:'delete',color:'slate',width:880,height:580,singleInstance:true,dockSpecial:true,
  mount(root,{system,i18n,dialog,kernel,shell,agentContext}){
    let entries=[],selected='',loading=true,error='';
    const draw=()=>{root.innerHTML=`<div class="system-app trash-app"><div class="app-commandbar"><strong>${icon('delete',18)} ${i18n.t('trash')}</strong><div class="toolbar-spacer"></div><button data-trash-restore ${selected?'':'disabled'}>${icon('refresh',14)} ${i18n.t('putBack')}</button><button data-trash-delete ${selected?'':'disabled'}>${icon('delete',14)} ${i18n.t('deleteImmediately')}</button><button data-trash-empty ${entries.length?'':'disabled'}>${i18n.t('emptyTrash')}</button></div><main>${loading?`<div class="app-loading"><i></i>${i18n.t('loading')}</div>`:error?`<div class="empty-state">${icon('warning',34)}<strong>${esc(error)}</strong><button data-trash-retry>${i18n.t('tryAgain')}</button></div>`:entries.length?`<div class="trash-grid">${entries.map(entry=>`<button class="${selected===entry.name?'selected':''}" data-trash-item="${esc(entry.name)}"><span>${icon(entry.type==='directory'?'folder':'document',42)}</span><strong>${esc(entry.name)}</strong><small>${entry.type==='directory'?i18n.t('folder'):fmt(entry.size)}</small></button>`).join('')}</div>`:`<div class="trash-empty">${icon('delete',64)}<strong>${i18n.t('trashIsEmpty')}</strong><p>${i18n.t('trashEmptyCopy')}</p></div>`}</main><aside class="trash-inspector ${selected?'':'hidden'}">${selected?`<span>${icon(entries.find(x=>x.name===selected)?.type==='directory'?'folder':'document',48)}</span><h3>${esc(selected)}</h3><dl><dt>${i18n.t('originalLocation')}</dt><dd>${esc(system.trashOrigin(selected)||i18n.t('unknown'))}</dd><dt>${i18n.t('size')}</dt><dd>${fmt(entries.find(x=>x.name===selected)?.size||0)}</dd></dl>`:''}</aside><footer class="app-statusbar"><span>${entries.length} ${i18n.t('items')}</span><span>${i18n.t('trashAutoDelete')}</span></footer></div>`;bind()};
    const refresh=async()=>{if(!system.ready){loading=false;error=i18n.t('startMachine');draw();return}loading=true;error='';draw();try{entries=await system.list(TRASH,{priority:true});selected=entries.some(x=>x.name===selected)?selected:''}catch(e){error=e.message}finally{loading=false;draw()}};
    const current=()=>`${TRASH}/${selected}`;
    const reportSelection=event=>{if(!event.target.closest('[data-trash-item]'))return;const entry=entries.find(item=>item.name===selected);if(!entry)return;const path=current();agentContext.set({appId:'trash',label:i18n.t('trash'),resource:{kind:entry.type==='directory'?'folder':'file',entityType:`filesystem.${entry.type==='directory'?'folder':'file'}`,id:path,uri:`future://files${path}`,name:entry.name,path,metadata:{size:entry.size||0,originalLocation:system.trashOrigin(entry.name)||''}}})};root.addEventListener('click',reportSelection);
    const bind=()=>{root.querySelectorAll('[data-trash-item]').forEach(button=>{button.onclick=()=>{selected=button.dataset.trashItem;draw()};button.ondblclick=async()=>{const entry=entries.find(x=>x.name===button.dataset.trashItem);if(entry?.type==='directory')shell.open('files',`${TRASH}/${entry.name}`);else shell.open('preview',`${TRASH}/${entry.name}`)}});root.querySelector('[data-trash-retry]')?.addEventListener('click',refresh);root.querySelector('[data-trash-restore]')?.addEventListener('click',async()=>{await system.restoreTrash(current());shell.toast(i18n.t('itemRestored'),i18n.t('trash'));refresh()});root.querySelector('[data-trash-delete]')?.addEventListener('click',async()=>{if(await dialog.confirm({title:i18n.t('deleteImmediately'),message:i18n.t('deleteImmediatelyCopy').replace('{name}',selected),confirmLabel:i18n.t('delete'),danger:true})){await system.remove(current());refresh()}});root.querySelector('[data-trash-empty]')?.addEventListener('click',async()=>{if(await dialog.confirm({title:i18n.t('emptyTrash'),message:i18n.t('emptyTrashCopy'),confirmLabel:i18n.t('emptyTrash'),danger:true})){await system.emptyTrash();refresh()}})};
    const off=kernel.bus.on('filesystem:changed',({path})=>{if(path===TRASH)refresh()});refresh();return()=>{off();root.removeEventListener('click',reportSelection)};
  }
};
