import {icon} from '../../icons.js';
import {MUSIC_LIBRARY} from '../../services/MusicService.js';

const esc=value=>String(value??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const formatTime=value=>{const seconds=Math.max(0,Number(value)||0);return`${Math.floor(seconds/60)}:${String(Math.floor(seconds%60)).padStart(2,'0')}`};
const initials=value=>String(value||'Future').split(/\s+/).map(part=>part[0]).slice(0,2).join('').toUpperCase();

export default{
  id:'music',title:'music',icon:'music',color:'pink',width:1120,height:700,singleInstance:true,
  mount(root,{music,i18n,kernel,shell,agentContext,agentEntry,system}){
    let category='all',expanded='all',query='',importOpen=false,importing=false;
    const state=()=>music.snapshot();
    const report=track=>agentContext.set({appId:'music',label:i18n.t('music'),resource:{kind:'audio-track',id:track?.id||'library',uri:track?`future://music/tracks/${encodeURIComponent(track.id)}`:'future://music/library',name:track?.title||i18n.t('musicLibrary'),path:track?.path||MUSIC_LIBRARY,metadata:track?{artist:track.artist,category:track.category}: {trackCount:state().tracks.length}}});
    const artwork=track=>`<div class="music-artwork ${state().playing?'is-playing':''}"><div class="music-artwork-glow"></div><div class="music-record"><i></i><b>${esc(initials(track?.artist))}</b></div><div class="music-arm"></div></div>`;
    const trackRows=tracks=>tracks.length?tracks.map(track=>`<button data-music-track="${esc(track.id)}" class="${currentTrack()?.id===track.id?'selected':''}"><span class="music-track-art">${currentTrack()?.id===track.id&&state().playing?'<i></i><i></i><i></i>':icon('music',14)}</span><span><strong>${esc(track.title)}</strong><small>${esc(track.artist)}</small></span></button>`).join(''):`<div class="music-tree-empty">${i18n.t('noMusic')}</div>`;
    const currentTrack=()=>state().current;
    const draw=()=>{const snapshot=state(),current=snapshot.current,categories=snapshot.categories,groups=[{id:'all',label:i18n.t('allSongs'),icon:'music',tracks:snapshot.tracks.filter(track=>track.category==='Library')},...categories.map(item=>({id:item,label:item,icon:'folder',tracks:snapshot.tracks.filter(track=>track.category===item)}))];root.innerHTML=`<div class="music-app ${snapshot.playing?'is-playing':''}">
      <aside class="music-library"><header><span>${icon('music',20)}</span><div><strong>${i18n.t('music')}</strong><small>${i18n.t('localMusic')}</small></div></header><label>${icon('search',13)}<input data-music-search value="${esc(query)}" placeholder="${i18n.t('searchMusic')}"></label><nav class="music-library-tree">${snapshot.loading?`<div class="music-loading"><i></i>${i18n.t('loadingMusic')}</div>`:snapshot.error?`<div class="music-error">${icon('warning',16)}<span>${esc(snapshot.error)}</span></div>`:groups.map(group=>{const open=expanded===group.id,items=group.tracks.filter(track=>`${track.title} ${track.artist}`.toLowerCase().includes(query.toLowerCase()));return`<section class="${open?'expanded':''}"><button data-music-category="${esc(group.id)}" class="${category===group.id?'selected':''}"><span class="music-tree-chevron">${icon('chevron',11)}</span>${icon(group.icon,15)}<span>${esc(group.label)}</span><em>${group.tracks.length}</em></button>${open?`<div class="music-tree-tracks">${trackRows(items)}</div>`:''}</section>`}).join('')}</nav><footer style="grid-template-columns:minmax(0,1fr) 31px 31px"><button data-music-folder>${icon('folder',15)}<span><strong>${i18n.t('openMusicFolder')}</strong><small>${esc(MUSIC_LIBRARY)}</small></span></button><button data-music-import title="${i18n.t('importMusic')}">${icon('upload',14)}</button><button data-music-refresh title="${i18n.t('refresh')}">${icon('refresh',14)}</button></footer></aside>
      <main class="music-stage"><div class="music-ambient"><i></i><i></i><i></i></div><header><div><small>${esc(category==='all'?i18n.t('musicLibrary'):category)}</small><strong>${current?esc(current.title):i18n.t('readyToPlay')}</strong></div><button data-music-ask title="${i18n.t('askFuture')}">${icon('futureAi',15)}</button></header>
        <section class="music-now">${artwork(current)}<div class="music-now-meta"><small>${current?esc(current.category==='Library'?i18n.t('allSongs'):current.category):i18n.t('localMusic')}</small><h1>${current?esc(current.title):i18n.t('chooseSong')}</h1><p>${current?esc(current.artist):i18n.t('musicEmptyCopy')}</p></div><div class="music-progress"><input data-music-seek type="range" min="0" max="${snapshot.duration||1}" step="0.1" value="${snapshot.currentTime}"><div><time>${formatTime(snapshot.currentTime)}</time><time>${formatTime(snapshot.duration)}</time></div></div><div class="music-controls"><div class="music-volume-popover"><button title="${i18n.t('volume')}">${icon('volume',17)}</button><span><input data-music-volume type="range" min="0" max="1" step="0.01" value="${snapshot.volume}"></span></div><button data-music-shuffle class="${snapshot.shuffle?'active':''}" title="${i18n.t('shuffle')}">${icon('shuffle',17)}</button><button data-music-previous>${icon('previous',21)}</button><button class="music-play" data-music-toggle ${!current&&!snapshot.tracks.length?'disabled':''}>${icon(snapshot.playing?'pause':'play',24)}</button><button data-music-next>${icon('next',21)}</button><button data-music-repeat class="${snapshot.repeat!=='off'?'active':''}" title="${i18n.t('repeat')}">${icon('repeat',17)}${snapshot.repeat==='one'?'<b>1</b>':''}</button></div></section>
      </main>${importOpen?`<section class="music-import-sheet"><div><span>${icon('music',24)}</span><h2>${i18n.t('importMusic')}</h2><p>${i18n.t('importMusicSheetCopy')}</p><button data-music-choose-files ${importing?'disabled':''}>${icon('music',15)}${i18n.t(importing?'importingMusic':'chooseMusicFiles')}</button><button data-music-choose-folder ${importing?'disabled':''}>${icon('folder',15)}${i18n.t('chooseMusicFolder')}</button><button class="quiet" data-music-import-close ${importing?'disabled':''}>${i18n.t('cancel')}</button><input data-music-file-input type="file" accept="audio/*,.flac,.opus" multiple hidden><input data-music-folder-input type="file" accept="audio/*,.flac,.opus" webkitdirectory directory multiple hidden></div></section>`:''}</div>`;bind();report(current)};
    const bind=()=>{
      root.querySelector('[data-music-search]')?.addEventListener('input',event=>{query=event.target.value;draw();requestAnimationFrame(()=>{const input=root.querySelector('[data-music-search]');input?.focus();input?.setSelectionRange(query.length,query.length)})});
      root.querySelectorAll('[data-music-category]').forEach(button=>button.onclick=()=>{const next=button.dataset.musicCategory;category=next;expanded=expanded===next?'':next;draw()});
      root.querySelectorAll('[data-music-track]').forEach(button=>button.onclick=()=>music.play(button.dataset.musicTrack).catch(()=>{}));
      root.querySelector('[data-music-toggle]')?.addEventListener('click',()=>music.toggle());root.querySelector('[data-music-next]')?.addEventListener('click',()=>music.next());root.querySelector('[data-music-previous]')?.addEventListener('click',()=>music.previous());root.querySelector('[data-music-shuffle]')?.addEventListener('click',()=>music.toggleShuffle());root.querySelector('[data-music-repeat]')?.addEventListener('click',()=>music.cycleRepeat());
      root.querySelector('[data-music-seek]')?.addEventListener('input',event=>music.seek(event.target.value));root.querySelector('[data-music-volume]')?.addEventListener('input',event=>music.setVolume(event.target.value));
      const importFiles=async(files,folderMode=false)=>{const audio=[...files].filter(file=>/\.(mp3|m4a|aac|wav|ogg|oga|flac|opus)$/i.test(file.name));if(!audio.length){shell.toast(i18n.t('noSupportedMusic'),i18n.t('importFailed'));return}importing=true;draw();try{const occupied=new Set(state().tracks.map(track=>track.path));let importedCategory='';if(folderMode){const source=String(audio[0].webkitRelativePath||'Imported Music').split('/').filter(Boolean)[0]||'Imported Music',entries=await system.list(MUSIC_LIBRARY,{fresh:true,priority:true,timeout:20000}),folders=new Set(entries.filter(item=>item.type==='directory').map(item=>item.name));importedCategory=source;let index=2;while(folders.has(importedCategory))importedCategory=`${source} ${index++}`}for(const file of audio){const directory=importedCategory?`${MUSIC_LIBRARY}/${importedCategory}`:MUSIC_LIBRARY;let name=file.name,target=`${directory}/${name}`,index=2;while(occupied.has(target)){const dot=name.lastIndexOf('.'),stem=dot>0?name.slice(0,dot):name,ext=dot>0?name.slice(dot):'';target=`${directory}/${stem} ${index++}${ext}`}await system.writeBytes(target,new Uint8Array(await file.arrayBuffer()),{priority:true});occupied.add(target)}await music.refresh();category=importedCategory||'all';expanded=category;importOpen=false;shell.toast(i18n.t('musicImported'),i18n.t('music'))}catch(error){shell.toast(error.message,i18n.t('importFailed'))}finally{importing=false;draw()}};
      root.querySelectorAll('[data-music-folder]').forEach(button=>button.onclick=()=>shell.open('files',MUSIC_LIBRARY));root.querySelector('[data-music-import]')?.addEventListener('click',()=>{importOpen=true;draw()});root.querySelector('[data-music-import-close]')?.addEventListener('click',()=>{importOpen=false;draw()});root.querySelector('[data-music-choose-files]')?.addEventListener('click',()=>root.querySelector('[data-music-file-input]')?.click());root.querySelector('[data-music-choose-folder]')?.addEventListener('click',()=>root.querySelector('[data-music-folder-input]')?.click());root.querySelector('[data-music-file-input]')?.addEventListener('change',event=>importFiles(event.target.files));root.querySelector('[data-music-folder-input]')?.addEventListener('change',event=>importFiles(event.target.files,true));root.querySelector('[data-music-refresh]')?.addEventListener('click',()=>music.refresh());root.querySelector('[data-music-ask]')?.addEventListener('click',()=>{report(state().current);agentEntry.open({prompt:i18n.t('askFutureMusicPrompt'),source:'music'})});
    };
    const off=kernel.bus.on('music:changed',draw),offTime=kernel.bus.on('music:time',snapshot=>{root.querySelector('[data-music-seek]')?.setAttribute('value',snapshot.currentTime);const times=root.querySelectorAll('.music-progress time');if(times[0])times[0].textContent=formatTime(snapshot.currentTime)}),offVolume=kernel.bus.on('music:volume',snapshot=>{const volume=root.querySelector('[data-music-volume]');if(volume)volume.value=snapshot.volume});draw();return()=>{off();offTime();offVolume();music.pause()};
  }
};
