import {icon} from '../../icons.js';
import {weatherCondition} from '../../services/WeatherService.js';

export const weatherEsc=value=>String(value??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/"/g,'&quot;');
export const weatherNumber=value=>Math.round(Number(value)||0);

export const weatherViewData=(value,i18n)=>{
  const data=value.data,current=data?.current,condition=weatherCondition(current?.weather_code,i18n.locale);
  const hours=data?.hourly?.time?.map((time,index)=>({time,temp:data.hourly.temperature_2m[index],code:data.hourly.weather_code[index],rain:data.hourly.precipitation_probability[index]})).filter(hour=>new Date(hour.time)>=new Date()).slice(0,24)||[];
  const days=data?.daily?.time?.map((date,index)=>({date,code:data.daily.weather_code[index],high:data.daily.temperature_2m_max[index],low:data.daily.temperature_2m_min[index],rain:data.daily.precipitation_probability_max[index],uv:data.daily.uv_index_max[index],sunrise:data.daily.sunrise[index],sunset:data.daily.sunset[index]}))||[];
  return{data,current,condition,hours,days};
};

export const weatherDetailMarkup=(value,i18n,{extraActions=''}={})=>{
  const {data,current,condition,hours,days}=weatherViewData(value,i18n),locale=i18n.t('dateFormat'),n=weatherNumber,esc=weatherEsc;
  return `<div class="weather-toolbar"><div><h1>${esc(value.location?.name||i18n.t('weather'))}</h1><p>${esc([value.location?.admin1,value.location?.country].filter(Boolean).join(', '))}</p></div><button data-weather-search>${icon('location',15)} ${i18n.t('changeLocation')}</button><button data-weather-refresh class="${value.loading?'spinning':''}">${icon('refresh',15)}</button>${extraActions}</div>${!data?`<div class="weather-empty">${icon('cloud',58)}<strong>${value.loading?i18n.t('loadingWeather'):i18n.t('weatherUnavailable')}</strong></div>`:`<section class="weather-hero"><div><span>${icon(condition.glyph,72)}</span><strong>${n(current.temperature_2m)}°</strong></div><h2>${condition.label}</h2><p>${i18n.t('feelsLike')} ${n(current.apparent_temperature)}° · H:${n(days[0]?.high)}° L:${n(days[0]?.low)}°</p></section><section class="weather-panel weather-hourly"><header>${icon('clock',14)} ${i18n.t('hourlyForecast')}</header><div>${hours.map((hour,index)=>{const item=weatherCondition(hour.code,i18n.locale);return`<article><b>${index===0?i18n.t('now'):new Intl.DateTimeFormat(locale,{hour:'numeric'}).format(new Date(hour.time))}</b>${icon(item.glyph,25)}<strong>${n(hour.temp)}°</strong><small>${hour.rain||0}%</small></article>`}).join('')}</div></section><div class="weather-lower"><section class="weather-panel weather-days"><header>${icon('calendar',14)} ${i18n.t('tenDayForecast')}</header>${days.map((day,index)=>{const item=weatherCondition(day.code,i18n.locale);return`<article><strong>${index===0?i18n.t('today'):new Intl.DateTimeFormat(locale,{weekday:'short'}).format(new Date(`${day.date}T12:00`))}</strong><small>${day.rain||0}%</small>${icon(item.glyph,22)}<span>${n(day.low)}° <i><b style="--low:${n(day.low)};--high:${n(day.high)}"></b></i> ${n(day.high)}°</span></article>`}).join('')}</section><div class="weather-details"><section class="weather-panel"><header>${icon('rain',14)} ${i18n.t('precipitation')}</header><strong>${n(current.precipitation)} <small>mm</small></strong><p>${days[0]?.rain||0}% ${i18n.t('today').toLowerCase()}</p></section><section class="weather-panel"><header>${icon('wind',14)} ${i18n.t('wind')}</header><strong>${n(current.wind_speed_10m)} <small>km/h</small></strong><p>${n(current.relative_humidity_2m)}% ${i18n.t('humidity').toLowerCase()}</p></section><section class="weather-panel"><header>${icon('sun',14)} UV</header><strong>${n(days[0]?.uv)}</strong><p>${i18n.t('sunset')} ${days[0]?.sunset?.slice(11,16)||'—'}</p></section></div></div>`}`;
};
