export const counterPackage={
  manifest:{
    formatVersion:1,sdkVersion:'1',id:'counter',version:'1.0.0',
    name:{en:'Counter',zh:'计数器'},description:{en:'A shared counter built with the Aeris App SDK.',zh:'使用 Aeris App SDK 构建的共享计数器。'},
    icon:'plus',color:'aqua',singleInstance:true,permissions:['storage'],initialState:{count:0,step:1,history:[]},
    window:{width:760,height:540,minWidth:480,minHeight:380},
    views:{
      main:{html:'main/index.html',css:'main/style.css',script:'main/app.js'},
      activity:{html:'activity/index.html',css:'activity/style.css',script:'activity/app.js'},
    },
  },
  files:{
    'locales/en.json':JSON.stringify({eyebrow:'Aeris App SDK',title:'Counter',subtitle:'One state, every surface.',decrease:'Decrease',increase:'Increase',reset:'Reset counter',step:'Step size',recent:'Recent activity',empty:'Your changes will appear here.',open:'Open full app',changed:'Changed by {amount}',resetAction:'Reset to zero'}),
    'locales/zh.json':JSON.stringify({eyebrow:'Aeris App SDK',title:'计数器',subtitle:'一份状态，同步所有界面。',decrease:'减少',increase:'增加',reset:'重置计数器',step:'步长',recent:'最近活动',empty:'你的操作会显示在这里。',open:'打开完整应用',changed:'变化 {amount}',resetAction:'重置为零'}),
    'main/index.html':'<main class="counter-shell"><header><div><small data-i18n="eyebrow"></small><h1 data-i18n="title"></h1><p data-i18n="subtitle"></p></div><span class="live-pill"><i></i> Live</span></header><section class="counter-card"><output data-count>0</output><div class="counter-actions"><button class="secondary" data-action="decrease" aria-label="Decrease">−</button><button class="primary" data-action="increase" aria-label="Increase">+</button></div><label><span data-i18n="step"></span><input data-step type="range" min="1" max="10" value="1"><output data-step-value>1</output></label></section><section class="history"><div class="section-heading"><h2 data-i18n="recent"></h2><button data-action="reset" data-i18n="reset"></button></div><ol data-history></ol></section></main>',
    'main/style.css':`:root{color:#102b3c;background:#edf7fb}html[data-theme="dark"]{color:#e9f7fd;background:#0b1821}.counter-shell{height:100%;padding:34px 38px;overflow:auto;background:radial-gradient(circle at 82% 4%,color-mix(in srgb,var(--accent) 24%,transparent),transparent 36%),linear-gradient(145deg,rgba(255,255,255,.78),rgba(226,244,250,.72))}html[data-theme="dark"] .counter-shell{background:radial-gradient(circle at 82% 4%,color-mix(in srgb,var(--accent) 30%,transparent),transparent 38%),linear-gradient(145deg,#10232e,#09151d)}header{display:flex;align-items:flex-start;justify-content:space-between;margin-bottom:30px}small{font-size:11px;font-weight:750;letter-spacing:.14em;text-transform:uppercase;color:var(--accent)}h1{font-size:36px;letter-spacing:-.04em;margin:7px 0 4px}p{margin:0;opacity:.58}.live-pill{display:flex;gap:7px;align-items:center;padding:7px 11px;border:1px solid rgba(20,80,105,.12);border-radius:999px;background:rgba(255,255,255,.55);font-size:12px;font-weight:650}.live-pill i{width:7px;height:7px;border-radius:50%;background:#30bc83;box-shadow:0 0 0 4px rgba(48,188,131,.12)}.counter-card{padding:28px;border:1px solid rgba(25,91,115,.12);border-radius:26px;background:rgba(255,255,255,.68);box-shadow:0 18px 55px rgba(23,87,111,.1);backdrop-filter:blur(18px)}html[data-theme="dark"] .counter-card,.live-pill{background:rgba(11,31,42,.62);border-color:rgba(187,226,241,.11)}[data-count]{display:block;text-align:center;font-size:92px;line-height:1.1;font-weight:680;letter-spacing:-.07em;font-variant-numeric:tabular-nums}.counter-actions{display:flex;justify-content:center;gap:13px;margin:17px 0 27px}.counter-actions button{width:58px;height:46px;border-radius:15px;border:0;font-size:26px;cursor:pointer;transition:transform .15s ease,filter .15s ease}.counter-actions button:active{transform:scale(.94)}.primary{color:white;background:var(--accent);box-shadow:0 8px 25px color-mix(in srgb,var(--accent) 35%,transparent)}.secondary{color:inherit;background:rgba(113,158,177,.14)}label{display:grid;grid-template-columns:auto 1fr 26px;gap:14px;align-items:center;font-size:12px;font-weight:650;opacity:.72}input{accent-color:var(--accent)}.history{padding:25px 5px 0}.section-heading{display:flex;align-items:center;justify-content:space-between}.section-heading h2{font-size:14px;margin:0}.section-heading button{border:0;color:var(--accent);background:none;font-size:12px;cursor:pointer}ol{list-style:none;padding:0;margin:13px 0}li{display:flex;justify-content:space-between;align-items:center;padding:11px 2px;border-bottom:1px solid rgba(60,102,120,.1);font-size:13px}li small{color:inherit;opacity:.48;letter-spacing:0;text-transform:none}.empty{opacity:.42;border:0}@media(max-width:560px){.counter-shell{padding:25px}[data-count]{font-size:74px}}`,
    'main/app.js':`Aeris.ready.then(() => {
  const text = key => Aeris.i18n.t(key), localize = () => document.querySelectorAll('[data-i18n]').forEach(node => node.textContent = text(node.dataset.i18n));
  const commit = async (next, amount, reset = false) => { const history = [{ id: crypto.randomUUID(), amount, reset, at: Date.now() }, ...(next.history || [])].slice(0, 8); await Aeris.app.setState({ ...next, history }); };
  const render = state => { const step = Number(state.step) || 1; document.querySelector('[data-count]').textContent = state.count || 0; document.querySelector('[data-step]').value = step; document.querySelector('[data-step-value]').textContent = step; const history = document.querySelector('[data-history]'), items = state.history || []; history.innerHTML = items.length ? items.map(item => '<li><span>' + (item.reset ? text('resetAction') : text('changed').replace('{amount}', (item.amount > 0 ? '+' : '') + item.amount)) + '</span><small>' + new Intl.DateTimeFormat(undefined,{hour:'2-digit',minute:'2-digit'}).format(item.at) + '</small></li>').join('') : '<li class="empty">' + text('empty') + '</li>'; };
  document.querySelector('[data-action="increase"]').onclick = async () => { const state = await Aeris.app.getState(), step = Number(state.step)||1; commit({ ...state, count:(Number(state.count)||0)+step }, step); };
  document.querySelector('[data-action="decrease"]').onclick = async () => { const state = await Aeris.app.getState(), step = Number(state.step)||1; commit({ ...state, count:(Number(state.count)||0)-step }, -step); };
  document.querySelector('[data-action="reset"]').onclick = async () => { const state = await Aeris.app.getState(); commit({ ...state, count:0 }, -(Number(state.count)||0), true); };
  document.querySelector('[data-step]').oninput = event => { document.querySelector('[data-step-value]').textContent=event.target.value; };
  document.querySelector('[data-step]').onchange = async event => Aeris.app.patchState({step:Number(event.target.value)});
  localize(); Aeris.environment.subscribe(localize); Aeris.app.subscribe(render);
});`,
    'activity/index.html':'<main class="activity-counter"><div class="activity-glow"></div><header><div><small data-i18n="eyebrow"></small><h1 data-i18n="title"></h1></div><button data-open aria-label="Open full app">↗</button></header><section><p data-i18n="subtitle"></p><output data-count>0</output><div><button data-action="decrease">−</button><button class="primary" data-action="increase">+</button></div></section><footer><span><i></i> Shared state</span><button data-open data-i18n="open"></button></footer></main>',
    'activity/style.css':`:root{color:#102b3c;background:#eaf5f9}html[data-theme="dark"]{color:#e8f7fc;background:#09161e}.activity-counter{position:relative;height:100%;min-height:340px;padding:24px;overflow:hidden;background:linear-gradient(160deg,rgba(255,255,255,.86),rgba(220,240,247,.8))}.activity-glow{position:absolute;width:280px;height:280px;right:-100px;top:-110px;border-radius:50%;background:color-mix(in srgb,var(--accent) 30%,transparent);filter:blur(12px)}html[data-theme="dark"] .activity-counter{background:linear-gradient(160deg,#10242e,#08151c)}header,footer{position:relative;display:flex;justify-content:space-between;align-items:center}small{font-size:10px;color:var(--accent);font-weight:750;text-transform:uppercase;letter-spacing:.12em}h1{font-size:23px;margin:4px 0 0;letter-spacing:-.03em}button{border:0;cursor:pointer}header button{width:32px;height:32px;border-radius:10px;background:rgba(100,150,170,.13);color:inherit}section{position:relative;display:flex;min-height:240px;flex-direction:column;align-items:center;justify-content:center}section p{font-size:12px;opacity:.5;margin:0 0 8px}section output{font-size:78px;font-weight:680;line-height:1.2;letter-spacing:-.07em;font-variant-numeric:tabular-nums}section div{display:flex;gap:10px;margin-top:17px}section button{width:49px;height:40px;border-radius:13px;background:rgba(95,143,163,.14);color:inherit;font-size:22px}section .primary{background:var(--accent);color:white;box-shadow:0 7px 21px color-mix(in srgb,var(--accent) 32%,transparent)}footer{font-size:11px}footer span{display:flex;align-items:center;gap:7px;opacity:.5}footer i{width:6px;height:6px;border-radius:50%;background:#35bd85}footer button{background:none;color:var(--accent);font-size:11px;font-weight:650}`,
    'activity/app.js':`Aeris.ready.then(() => {
  const localize=()=>document.querySelectorAll('[data-i18n]').forEach(node=>node.textContent=Aeris.i18n.t(node.dataset.i18n));
  const change=async direction=>{const state=await Aeris.app.getState(),step=Number(state.step)||1,amount=step*direction,history=[{id:crypto.randomUUID(),amount,reset:false,at:Date.now()},...(state.history||[])].slice(0,8);await Aeris.app.setState({...state,count:(Number(state.count)||0)+amount,history})};
  document.querySelector('[data-action="increase"]').onclick=()=>change(1);document.querySelector('[data-action="decrease"]').onclick=()=>change(-1);document.querySelectorAll('[data-open]').forEach(button=>button.onclick=()=>Aeris.activity.openFullApp());
  localize();Aeris.environment.subscribe(localize);Aeris.app.subscribe(state=>document.querySelector('[data-count]').textContent=state.count||0);
});`,
  },
};
