import { addDays,dateKey,endOfMonth,occurrences,startOfMonth,startOfWeek } from './model.js';
const esc=value=>String(value??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/"/g,'&quot;');
const time=(date,locale)=>new Intl.DateTimeFormat(locale,{hour:'numeric',minute:'2-digit'}).format(date);
const eventColor=(event,calendars)=>calendars.find(item=>item.id===event.calendarId)?.color||'#5f87d7';
const eventChip=(event,calendars,locale,compact=false)=>`<button draggable="${event.readOnly?'false':'true'}" class="calendar-event-chip ${event.allDay?'all-day':''} ${event.readOnly?'readonly':''}" data-event="${event.id}" data-occurrence="${event.occurrenceKey}" style="--event-color:${eventColor(event,calendars)}" title="${esc(event.title)}">${!event.allDay&&!compact?`<time>${time(event.occurrenceStart,locale)}</time>`:''}<span>${esc(event.title)}</span></button>`;

export function monthView(cursor,events,calendars,i18n,selectedDate){
  const month=startOfMonth(cursor),gridStart=startOfWeek(month),gridEnd=addDays(gridStart,41),items=occurrences(events,calendars,gridStart,new Date(gridEnd.getFullYear(),gridEnd.getMonth(),gridEnd.getDate(),23,59)),today=dateKey(new Date()),locale=i18n.t('dateFormat');
  const weekdays=Array.from({length:7},(_,index)=>new Intl.DateTimeFormat(locale,{weekday:'short'}).format(addDays(gridStart,index)));
  return `<div class="calendar-month-pro"><header>${weekdays.map(label=>`<b>${label}</b>`).join('')}</header><div class="calendar-month-grid">${Array.from({length:42},(_,index)=>{const day=addDays(gridStart,index),key=dateKey(day),dayEvents=items.filter(item=>dateKey(item.occurrenceStart)===key);return `<section class="calendar-month-day ${day.getMonth()!==month.getMonth()?'outside':''} ${key===selectedDate?'selected':''}" data-calendar-date="${key}" data-drop-date="${key}"><button class="day-number ${key===today?'today':''}" data-select-date="${key}">${day.getDate()}</button><div>${dayEvents.slice(0,3).map(event=>eventChip(event,calendars,locale)).join('')}${dayEvents.length>3?`<button class="calendar-more" data-select-date="${key}">+${dayEvents.length-3} ${i18n.t('more')}</button>`:''}</div></section>`}).join('')}</div></div>`;
}

export function timeGridView(cursor,events,calendars,i18n,days){
  const base=days===1?new Date(cursor.getFullYear(),cursor.getMonth(),cursor.getDate()):startOfWeek(cursor),rangeEnd=new Date(addDays(base,days-1).setHours(23,59,59)),items=occurrences(events,calendars,base,rangeEnd),locale=i18n.t('dateFormat'),today=dateKey(new Date()),columns=Array.from({length:days},(_,index)=>addDays(base,index));
  const allDay=items.filter(item=>item.allDay),timed=items.filter(item=>!item.allDay);
  return `<div class="calendar-time-view" style="--calendar-columns:${days}"><header><span></span>${columns.map(day=>`<button data-select-date="${dateKey(day)}" class="${dateKey(day)===today?'today':''}"><small>${new Intl.DateTimeFormat(locale,{weekday:'short'}).format(day)}</small><strong>${day.getDate()}</strong></button>`).join('')}</header><div class="calendar-all-day"><span>${i18n.t('allDay')}</span>${columns.map(day=>`<div data-drop-date="${dateKey(day)}">${allDay.filter(item=>dateKey(item.occurrenceStart)===dateKey(day)).map(event=>eventChip(event,calendars,locale,true)).join('')}</div>`).join('')}</div><div class="calendar-hours"><aside>${Array.from({length:24},(_,hour)=>`<time>${new Intl.DateTimeFormat(locale,{hour:'numeric'}).format(new Date(2026,0,1,hour))}</time>`).join('')}</aside><main>${columns.map(day=>`<section data-drop-date="${dateKey(day)}">${Array.from({length:24},(_,hour)=>`<button data-time-slot="${dateKey(day)}:${hour*60}" aria-label="${hour}:00"></button>`).join('')}${timed.filter(item=>dateKey(item.occurrenceStart)===dateKey(day)).map(event=>{const start=event.occurrenceStart.getHours()*60+event.occurrenceStart.getMinutes(),minutes=Math.max(30,(event.occurrenceEnd-event.occurrenceStart)/60000);return `<button draggable="true" class="calendar-timed-event" data-event="${event.id}" data-occurrence="${event.occurrenceKey}" style="--event-color:${eventColor(event,calendars)};top:${start*.8}px;height:${Math.max(24,minutes*.8)}px"><strong>${esc(event.title)}</strong><time>${time(event.occurrenceStart,locale)} – ${time(event.occurrenceEnd,locale)}</time>${event.location?`<small>${esc(event.location)}</small>`:''}</button>`}).join('')}</section>`).join('')}</main></div></div>`;
}

export function yearView(cursor,events,calendars,i18n){
  const year=cursor.getFullYear(),locale=i18n.t('dateFormat'),today=dateKey(new Date());
  return `<div class="calendar-year-view">${Array.from({length:12},(_,monthIndex)=>{const month=new Date(year,monthIndex,1),start=startOfWeek(month),end=endOfMonth(month),items=occurrences(events,calendars,month,end);return `<section><button data-year-month="${monthIndex}">${new Intl.DateTimeFormat(locale,{month:'long'}).format(month)}</button><header>${Array.from({length:7},(_,index)=>new Intl.DateTimeFormat(locale,{weekday:'narrow'}).format(addDays(start,index))).map(label=>`<b>${label}</b>`).join('')}</header><div>${Array.from({length:42},(_,index)=>{const day=addDays(start,index),key=dateKey(day),hasEvent=items.some(item=>dateKey(item.occurrenceStart)===key);return day.getMonth()===monthIndex?`<button data-select-date="${key}" class="${key===today?'today':''} ${hasEvent?'has-event':''}">${day.getDate()}</button>`:'<i></i>'}).join('')}</div></section>`}).join('')}</div>`;
}

export function searchResults(query,events,calendars,i18n){
  const start=new Date(2000,0,1),end=new Date(2100,0,1),items=occurrences(events,calendars,start,end,query).slice(0,200),locale=i18n.t('dateFormat');
  return `<div class="calendar-search-view"><header><h2>${i18n.t('searchResults')}</h2><span>${i18n.t('resultCount').replace('{count}',items.length)}</span></header>${items.length?items.map(event=>`<button data-event="${event.id}" data-occurrence="${event.occurrenceKey}" style="--event-color:${eventColor(event,calendars)}"><i></i><time>${new Intl.DateTimeFormat(locale,{dateStyle:'medium',timeStyle:event.allDay?undefined:'short'}).format(event.occurrenceStart)}</time><span><strong>${esc(event.title)}</strong><small>${esc(event.location||calendars.find(item=>item.id===event.calendarId)?.name||'')}</small></span></button>`).join(''):`<div class="empty-state">${i18n.t('noSearchResults')}</div>`}</div>`;
}
