import { icon } from '../icons.js';
import { renderMarkdown } from '../apps/ai/MarkdownRenderer.js';
import { AGENT_ATTACHMENT_ACCEPT, attachmentErrorMessage, readAgentAttachments, validateAgentAttachments } from '../services/AgentAttachments.js';

const esc=value=>String(value??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const textOf=message=>typeof message?.content==='string'?message.content:(message?.content||[]).filter(block=>block?.type==='text').map(block=>block.text).join('\n');
const blocksOf=message=>typeof message?.content==='string'?[{type:'text',text:message.content}]:(Array.isArray(message?.content)?message.content:[]);

export class CompactAgentPanel {
  constructor(host,context){this.host=host;this.context=context;this.activeId=null;this.opened=false;this.menu='';this.draft='';this.error='';this.frame=0;this.follow=true;this.editingId=null;this.editDraft='';this.expandedTools=new Set();this.skillCommandQuery=null;this.skillCommandIndex=0;this.selectedSkillName='';this.attachments=[]}

  mount(){
    this.node=document.createElement('section');this.node.className='compact-agent-panel';this.node.hidden=true;this.host.appendChild(this.node);
    this.node.addEventListener('contextmenu',event=>{event.preventDefault();event.stopPropagation()});
    const bus=this.context.kernel.bus;
    this.offs=[
      bus.on('ai:compact-entry',detail=>this.open(detail)),
      bus.on('ai:ready',()=>this.opened&&this.render()),
      bus.on('ai:changed',detail=>{if(!this.opened)return;if(detail?.sessionId&&detail.sessionId!==this.activeId)return;this.#schedule()}),
      bus.on('ai:agent-event',detail=>{if(this.opened&&detail.sessionId===this.activeId)this.#schedule()}),
      bus.on('capability:execution',()=>this.opened&&this.#schedule()),
      bus.on('agent:query-user',detail=>{if(this.opened&&detail?.sessionId===this.activeId)this.#schedule()}),
      bus.on('notification:changed',()=>this.opened&&this.render()),
      bus.on('agent:context-changed',()=>this.opened&&this.render()),
      bus.on('skill:changed',()=>{if(!this.opened)return;if(this.selectedSkillName&&!this.#selectedSkill())this.selectedSkillName='';this.render()}),
      bus.on('multi-agent:workflow',detail=>{if(this.opened&&detail?.sessionId===this.activeId)this.#schedule()}),
      bus.on('agent:open-app',detail=>{if(!this.opened)return;this.#switchToFull();queueMicrotask(()=>bus.emit('agent:open-app',detail))}),
      bus.on('settings:change',({key})=>{if(this.opened&&key==='locale')this.render()}),
    ];
    this.onDocumentPointerDown=event=>{
      if(!this.opened)return;
      const target=event.target;
      if(this.menu&&!target.closest('.compact-agent-popover,[data-compact-menu],[data-compact-context]'))this.#closeMenu();
      if(this.skillCommandQuery!==null&&!target.closest('[data-compact-composer],[data-compact-skill-command]'))this.#closeSkillCommand();
    };
    document.addEventListener('pointerdown',this.onDocumentPointerDown,true);
  }

  open(detail={}){
    const sessions=this.context.aiAgent.snapshot().sessions;
    const requested=String(detail.sessionId||'');
    if(requested&&sessions.some(item=>item.id===requested))this.activeId=requested;
    else if(!this.activeId||!sessions.some(item=>item.id===this.activeId))this.activeId=sessions[0]?.id||this.context.aiAgent.createSession();
    const current=this.#session();
    if(!requested&&detail.prompt&&current?.turns?.length)this.activeId=this.context.aiAgent.createSession();
    this.draft=String(detail.prompt||'');this.attachments=Array.isArray(detail.attachments)?detail.attachments:[];this.selectedSkillName=this.#enabledSkills().some(skill=>skill.name===detail.skillName)?detail.skillName:'';this.skillCommandQuery=null;this.skillCommandIndex=0;this.error='';this.menu='';this.editingId=null;this.editDraft='';this.opened=true;this.node.hidden=false;this.render({focus:true});
    if(detail.autoSend&&(this.draft||this.attachments.length))this.#send();
  }

  close(){this.opened=false;this.menu='';this.skillCommandQuery=null;this.node.hidden=true;this.context.kernel.bus.emit('ai:surface-session',{surface:'compact',sessionId:''})}
  #session(){try{return this.activeId?this.context.aiAgent.sessionState(this.activeId):null}catch{return null}}
  #schedule(){if(this.frame)return;this.frame=requestAnimationFrame(()=>{this.frame=0;this.render()})}
  #configured(){try{return Boolean(this.context.aiAgent.config().apiKey)}catch{return false}}
  #modelOptions(){try{return this.context.aiAgent.modelOptions()}catch{return[]}}
  #enabledSkills(){try{return this.context.skillRegistry.list().filter(skill=>skill.enabled)}catch{return[]}}
  #matchingSkills(){return this.#enabledSkills().filter(skill=>!this.skillCommandQuery||skill.name.includes(this.skillCommandQuery.toLowerCase()))}
  #selectedSkill(){return this.#enabledSkills().find(skill=>skill.name===this.selectedSkillName)||null}
  #selectedSkillMarkup(){const skill=this.#selectedSkill();return skill?`<button class="compact-agent-selected-skill" data-compact-remove-skill title="${this.context.i18n.t('removeSkill')}"><strong>/${esc(skill.name)}</strong>${icon('close',8)}</button>`:''}
  #skillCommandMarkup(){if(this.skillCommandQuery===null)return'';const skills=this.#matchingSkills();return`<section class="compact-agent-skill-command" data-compact-skill-command>${skills.length?skills.map((skill,index)=>`<button data-compact-select-skill="${esc(skill.name)}" class="${index===this.skillCommandIndex?'selected':''}"><strong>/${esc(skill.name)}</strong><small>${esc(skill.description)}</small></button>`).join(''):`<p>${this.context.i18n.t('noMatchingSkills')}</p>`}</section>`}
  #syncSkillCommand(composer=this.node.querySelector('[data-compact-composer]')){if(!composer)return;const match=composer.value.match(/^\/([a-z0-9-]*)$/i);this.skillCommandQuery=match?match[1]:null;this.skillCommandIndex=0;this.#renderSkillCommand()}
  #renderSkillCommand(){const host=this.node.querySelector('[data-compact-skill-command-host]');if(!host)return;host.innerHTML=this.#skillCommandMarkup();this.#bindSkillChoices()}
  #closeSkillCommand(){if(this.skillCommandQuery===null)return;this.skillCommandQuery=null;this.skillCommandIndex=0;this.#renderSkillCommand()}
  #closeMenu(){if(!this.menu)return;this.menu='';this.node.querySelector('.compact-agent-popover')?.remove();this.node.querySelectorAll('[data-compact-menu],[data-compact-context]').forEach(button=>button.classList.remove('selected'))}
  #bindSkillChoices(){this.node.querySelectorAll('[data-compact-select-skill]').forEach(button=>button.onpointerdown=event=>{event.preventDefault();this.#chooseSkill(button.dataset.compactSelectSkill)})}
  #chooseSkill(name){const skill=this.#enabledSkills().find(item=>item.name===name);if(!skill)return;this.selectedSkillName=skill.name;this.draft=this.draft.replace(/^\/[a-z0-9-]*\s*/i,'');const composer=this.node.querySelector('[data-compact-composer]');if(composer)composer.value=this.draft;this.#closeSkillCommand();this.render({focus:true})}
  #switchToFull(){const detail={mode:'full',source:'view-switch',sessionId:this.activeId,prompt:this.node.querySelector('[data-compact-composer]')?.value??this.draft,skillName:this.selectedSkillName,attachments:this.attachments};this.attachments=[];this.close();this.context.agentEntry.open(detail)}
  #messageText(message){return textOf(message)}
  #attachmentSize(size){return size<1024?`${size} B`:size<1024*1024?`${Math.ceil(size/1024)} KB`:`${(size/1024/1024).toFixed(1)} MB`}
  #attachmentMarkup(items,{removable=false}={}){return items?.length?`<div class="compact-agent-attachments ${removable?'composer':''}">${items.map(item=>`<div class="compact-agent-attachment">${item.kind==='image'&&item.data?`<img src="data:${esc(item.mimeType)};base64,${item.data}" alt="">`:`<span>${icon(item.kind==='image'?'image':'document',11)}</span>`}<span><strong>${esc(item.name)}</strong><small>${this.#attachmentSize(item.size||0)}</small></span>${removable?`<button data-compact-remove-attachment="${esc(item.id)}" title="${this.context.i18n.t('removeAttachment')}">${icon('close',8)}</button>`:''}</div>`).join('')}</div>`:''}

  #toolMarkup(block,result,turn){
    const {tools,i18n,registry}=this.context,metadata=tools.metadata(block.name)||{},execution={...(result?.details||{}),...(tools.execution(block.id)||{})};let phase=execution.phase||'running';
    if(['running','approval'].includes(phase)){if(result?.isError||turn.status==='failed')phase='failed';else if(turn.status==='stopped')phase='cancelled';else if(result||turn.status==='completed')phase='completed'}
    const app=registry.get(metadata.appId||execution.appId),label=execution.label||metadata.label||block.name,args=block.arguments??execution.params??{},output=result?textOf(result):'',expanded=this.expandedTools.has(block.id),hasDetails=Boolean(Object.keys(typeof args==='object'&&args?args:{}).length||output||execution.error);
    return`<section class="compact-agent-tool ai-tool-${phase} ${expanded?'expanded':''}" data-compact-tool="${esc(block.id)}"><header><span class="app-icon app-icon-${app?.color||'grey'}">${icon(app?.icon||'wrench',12)}</span><strong>${esc(label)}</strong><em>${i18n.t(`toolStatus_${phase}`)}</em>${hasDetails?`<button data-compact-tool-expand title="${i18n.t(expanded?'hideDetails':'showDetails')}">${icon('chevron',9)}</button>`:''}</header>${hasDetails?`<div class="compact-agent-tool-details">${Object.keys(typeof args==='object'&&args?args:{}).length?`<section><strong>${i18n.t('toolParameters')}</strong><pre data-copyable>${esc(JSON.stringify(args,null,2))}</pre></section>`:''}${output?`<section><strong>${i18n.t('toolResult')}</strong><p data-copyable>${esc(output).slice(0,1600)}</p></section>`:''}${execution.error?`<section class="error"><strong>${i18n.t('toolStatus_failed')}</strong><p data-copyable>${esc(execution.error)}</p></section>`:''}</div>`:''}</section>`;
  }

  #assistantMarkup(turn,streaming=null){
    const results=new Map((turn.responses||[]).filter(message=>message.role==='toolResult').map(message=>[message.toolCallId,message])),parts=[];
    const add=(message,{active=false}={})=>{const blocks=blocksOf(message),lastMeaningful=blocks.reduce((last,block,index)=>['thinking','text','toolCall'].includes(block?.type)?index:last,-1);for(const [index,block] of blocks.entries()){if(block?.type==='thinking'){const content=String(block.thinking||'').trim(),thinking=active&&index===lastMeaningful;if(content||thinking)parts.push(`<details class="compact-agent-thinking ${thinking?'is-thinking':''}" ${thinking?'open':''}><summary>${icon('sparkles',10)} <span>${this.context.i18n.t(thinking?'thinkingInProgress':'thinking')}</span>${thinking?'<i></i>':icon('chevron',8)}</summary><div>${content?renderMarkdown(content):`<span class="compact-agent-thinking-placeholder">${this.context.i18n.t('thinkingInProgress')}</span>`}</div></details>`)}else if(block?.type==='text'&&String(block.text||'').trim())parts.push(`<div class="compact-agent-markdown">${renderMarkdown(block.text)}</div>`);else if(block?.type==='toolCall')parts.push(this.#toolMarkup(block,results.get(block.id),turn))}};
    (turn.responses||[]).filter(message=>message.role==='assistant').forEach(message=>add(message));if(streaming?.role==='assistant')add(streaming,{active:true});
    if(turn.status==='running'&&!parts.length)parts.push('<span class="compact-agent-typing"><i></i><i></i><i></i></span>');
    if(turn.status==='failed'&&turn.error)parts.push(`<p class="compact-agent-error">${esc(turn.error)}</p>`);
    return parts.join('');
  }

  #conversation(session){
    const {i18n}=this.context;if(!this.context.aiAgent.ready)return`<div class="compact-agent-empty">${icon('futureAi',27)}<strong>${i18n.t('preparingAI')}</strong></div>`;
    if(!this.#configured())return`<div class="compact-agent-empty">${icon('settings',25)}<strong>${i18n.t('setupRequired')}</strong><small>${i18n.t('configureAICopy')}</small></div>`;
    if(!session?.turns?.length)return`<div class="compact-agent-empty">${icon('futureAi',28)}<strong>${i18n.t('howCanIHelp')}</strong><small>${i18n.t('compactAgentWelcome')}</small></div>`;
    return session.turns.map((turn,index)=>{const last=index===session.turns.length-1,actions=turn.status!=='running'&&!(last&&session.busy),editing=turn.id===this.editingId,userText=this.#messageText(turn.user),user=editing?`<div class="compact-agent-inline-editor"><textarea data-compact-inline-edit>${esc(this.editDraft)}</textarea><footer><button data-compact-cancel-edit>${i18n.t('cancel')}</button><button class="primary" data-compact-submit-edit>${i18n.t('send')}</button></footer></div>`:`${this.#attachmentMarkup(turn.user?.attachments)}${userText?`<div class="compact-agent-user-content">${renderMarkdown(userText)}</div>`:''}${actions?`<footer class="compact-agent-actions"><button data-compact-copy-turn="${esc(turn.id)}" data-compact-copy-role="user" title="${i18n.t('copyMessage')}">${icon('copy',13)}</button>${last&&!session.busy?`<button data-compact-edit-turn="${esc(turn.id)}" title="${i18n.t('editMessage')}">${icon('textedit',13)}</button>`:''}</footer>`:''}`,answer=this.#assistantMarkup(turn,turn.id===session.activeTurnId?session.streamingMessage:null);return`<section class="compact-agent-turn" data-compact-turn="${esc(turn.id)}"><div class="compact-agent-user"><div class="${editing?'editing':''}">${user}</div></div>${answer?`<div class="compact-agent-answer"><span>${icon('futureAi',14)}</span><div><div>${answer}</div>${actions?`<footer class="compact-agent-actions"><button data-compact-copy-turn="${esc(turn.id)}" data-compact-copy-role="assistant" title="${i18n.t('copyMessage')}">${icon('copy',13)}</button>${this.#usageMarkup(turn)}</footer>`:''}</div></div>`:''}</section>`}).join('');
  }

  #assistantText(turn){return(turn.responses||[]).filter(message=>message.role==='assistant').map(message=>textOf(message)).filter(Boolean).join('\n\n')}
  #usageMarkup(turn){const usage=this.context.aiAgent.turnUsage(turn);if(!usage.hasUsage)return'';const format=value=>new Intl.NumberFormat(this.context.i18n.t('dateFormat')).format(Number(value)||0),i18n=this.context.i18n;return`<span class="compact-agent-usage" tabindex="0">${icon('chart',13)}<span><strong>${i18n.t('taskUsage')}</strong><small>${esc(usage.modelName||i18n.t('unknownModel'))}</small><b>${i18n.t('inputTokens')} ${format(usage.input)}</b><b>${i18n.t('outputTokens')} ${format(usage.output)}</b><b>${i18n.t('cacheReadTokens')} ${format(usage.cacheRead)}</b></span></span>`}

  #historyMenu(){const {aiAgent,i18n,tools,queryUser,notifications}=this.context,sessions=aiAgent.snapshot().sessions,notices=notifications.snapshot().items;return`<section class="compact-agent-popover compact-agent-history"><header><strong>${i18n.t('conversations')}</strong></header><div>${sessions.length?sessions.map(item=>{const approval=tools.pendingApproval(item.id),input=queryUser.pendingForSession(item.id),unread=notices.some(note=>note.type==='agent'&&!note.read&&note.agent?.sessionId===item.id),status=approval?i18n.t('agentWaitingApproval'):input?i18n.t('agentInputRequired'):(item.busy||item.streaming)?i18n.t('agentStatus_running'):unread?i18n.t('agentFinished'):'';return`<button data-compact-session="${esc(item.id)}" class="${item.id===this.activeId?'selected':''}"><span>${icon('message',13)}</span><span><strong>${esc(item.title)}</strong><small>${esc(status||new Intl.DateTimeFormat(i18n.t('dateFormat'),{month:'short',day:'numeric'}).format(item.updatedAt))}</small></span>${status?'<i></i>':''}</button>`}).join(''):`<p>${i18n.t('noConversations')}</p>`}</div></section>`}
  #notificationMenu(){const {notifications,i18n,registry,tools}=this.context,{items}=notifications.snapshot();return`<section class="compact-agent-popover compact-agent-notifications"><header><strong>${i18n.t('notifications')}</strong>${items.length?`<button data-compact-clear-notifications>${i18n.t('clearAll')}</button>`:''}</header><div>${items.length?items.map(item=>{const app=registry.get(item.appId),approval=item.type==='agent'&&item.category==='approval'&&item.agent?.status==='approval'&&tools.execution(item.agent.toolCallId)?.phase==='approval';return`<article class="${item.read?'':'unread'}"><button data-compact-notification="${esc(item.id)}"><span class="app-icon app-icon-${app?.color||'blue'}">${icon(app?.icon||'bell',14)}</span><span><small>${esc(item.type==='agent'?(item.agent?.sessionTitle||i18n.t('futureAI')):(app?i18n.t(app.title):i18n.t('system')))}</small><strong>${esc(item.title)}</strong><p>${esc(item.message)}</p></span></button>${approval?`<footer><button data-compact-notification-deny="${esc(item.agent.toolCallId)}">${i18n.t('deny')}</button><button class="primary" data-compact-notification-approve="${esc(item.agent.toolCallId)}">${i18n.t('approve')}</button></footer>`:''}</article>`}).join(''):`<p>${i18n.t('noNotifications')}</p>`}</div></section>`}
  #contextMenu(){const {shell,agentContext,i18n}=this.context,current=agentContext.snapshot(),windows=shell.windowManager.contextWindows();return`<section class="compact-agent-popover compact-agent-context-menu"><header><strong>${i18n.t('chooseContext')}</strong></header><div><button data-compact-context-desktop class="${current?.resource?.kind==='desktop'?'selected':''}">${icon('desktop',13)}<span>${i18n.t('desktop')}</span></button>${windows.map(item=>`<button data-compact-context-window="${esc(item.id)}" class="${current?.windowId===item.id?'selected':''}"><span class="app-icon app-icon-${item.color}">${icon(item.icon,12)}</span><span>${esc(item.title)}</span></button>`).join('')}</div></section>`}

  #approval(session){const request=this.context.tools.pendingApproval(this.activeId);if(!request)return'';return`<section class="compact-agent-approval"><span>${icon('lock',13)}</span><div><small>${this.context.i18n.t('approvalRequired')}</small><strong>${esc(request.label||this.context.i18n.t('approveAgentAction'))}</strong></div><button data-compact-deny="${esc(request.toolCallId)}">${this.context.i18n.t('deny')}</button><button class="primary" data-compact-approve="${esc(request.toolCallId)}">${this.context.i18n.t('approve')}</button></section>`}
  #query(){const request=this.context.queryUser.pendingForSession(this.activeId);if(!request)return'';const t=this.context.i18n;return`<section class="compact-agent-query"><strong>${esc(t.t('appWidgetQuestion').replace('{app}',request.appName))}</strong><div><button data-compact-query="disable">${t.t('appOnly')}</button><button class="primary" data-compact-query="enable">${t.t('includeWidgets')}</button></div></section>`}

  render({focus=false}={}){
    if(!this.opened)return;const {aiAgent,i18n,notifications,agentContext}=this.context,session=this.#session(),state=aiAgent.snapshot(),busy=Boolean(session?.busy),draft=this.node.querySelector('[data-compact-composer]')?.value??this.draft;this.draft=draft;
    this.context.kernel.bus.emit('ai:surface-session',{surface:'compact',sessionId:this.activeId||''});
    const models=this.#modelOptions(),config=this.#configured()?aiAgent.config():null,context=agentContext.snapshot(),contextApp=context?.appId?this.context.registry.get(context.appId):null,contextIcon=contextApp?.icon||(context?.resource?.kind==='desktop'?'desktop':'focus'),contextColor=contextApp?.color||'blue',unread=notifications.snapshot().unread,workflow=this.context.multiAgent?.active(this.activeId),workers=workflow?.nodes?.slice(1)||[];
    const workflowBar=workers.length?`<button class="compact-agent-workflow" data-compact-workflow><span>${icon('list',13)}</span><span><strong>${i18n.t('agentWorkflow')}</strong><small>${workers.filter(node=>node.status==='completed').length}/${workers.length} · ${i18n.t(`agentStatus_${workflow.status}`)}</small></span><i><b style="width:${workflow.progress||0}%"></b></i>${icon('chevron',9)}</button>`:'';
    this.node.innerHTML=`<header class="compact-agent-header"><div><span>${icon('futureAi',17)}</span><strong>${esc(session?.title||i18n.t('newChat'))}</strong></div><nav><button data-compact-full title="${i18n.t('fullAgentView')}">${icon('maximize',14)}</button><button data-compact-menu="history" class="${this.menu==='history'?'selected':''}" title="${i18n.t('conversations')}">${icon('history',14)}</button><button data-compact-new title="${i18n.t('newChat')}">${icon('plus',14)}</button><button data-compact-menu="notifications" class="${this.menu==='notifications'?'selected':''}" title="${i18n.t('notifications')}">${icon('bell',14)}${unread?'<i></i>':''}</button><button data-compact-close title="${i18n.t('close')}">${icon('close',14)}</button></nav>${this.menu==='history'?this.#historyMenu():this.menu==='notifications'?this.#notificationMenu():''}</header>${workflowBar}<main data-compact-conversation>${this.#conversation(session)}</main><footer class="compact-agent-footer">${this.error?`<p class="compact-agent-error">${esc(this.error)}</p>`:''}${this.#query()}${this.#approval(session)}<div class="compact-agent-composer"><div data-compact-skill-command-host>${this.#skillCommandMarkup()}</div>${this.#attachmentMarkup(this.attachments,{removable:true})}<div class="compact-agent-input-row">${this.#selectedSkillMarkup()}<textarea data-compact-composer rows="1" placeholder="${i18n.t('messageFutureAI')}" ${!state.ready||!this.#configured()||busy||this.editingId?'disabled':''}>${esc(draft)}</textarea></div><div class="compact-agent-composer-toolbar"><button class="compact-agent-attach" data-compact-attach title="${i18n.t('attachFiles')}" ${busy?'disabled':''}>${icon('paperclip',13)}</button><input data-compact-attachment-input type="file" accept="${AGENT_ATTACHMENT_ACCEPT}" multiple hidden><span></span><button data-compact-context class="${this.menu==='context'?'selected':''}"><span class="app-icon app-icon-${contextColor}">${icon(contextIcon,11)}</span><span>${esc(context?.label||context?.resource?.name||i18n.t('chooseContext'))}</span>${icon('chevron',8)}</button><label>${icon('sparkles',10)}<select data-compact-model ${busy?'disabled':''}>${models.map(model=>`<option value="${esc(model.key)}" ${model.key===config?.activeModelKey?'selected':''}>${esc(model.label)}</option>`).join('')}</select><em>${config?i18n.t(`reasoning_${config.reasoningEffort||'medium'}`):''}</em></label><button class="compact-agent-send" data-compact-send ${!state.ready||!this.#configured()||this.editingId?'disabled':''}>${icon(busy?'stopSquare':'arrowUp',15)}</button></div>${this.menu==='context'?this.#contextMenu():''}</div><small>${i18n.t('aiMayMakeMistakes')}</small></footer>`;
    this.#bind();const conversation=this.node.querySelector('[data-compact-conversation]');if(conversation&&this.follow)requestAnimationFrame(()=>{conversation.scrollTop=conversation.scrollHeight});if(focus&&!busy)requestAnimationFrame(()=>this.node.querySelector('[data-compact-composer]')?.focus())
  }

  #bind(){
    const {aiAgent,notifications,agentContext,shell,tools,queryUser,i18n,clipboard}=this.context;
    this.node.querySelector('[data-compact-close]')?.addEventListener('click',()=>this.close());
    this.node.querySelector('[data-compact-full]')?.addEventListener('click',()=>this.#switchToFull());
    this.node.querySelector('[data-compact-workflow]')?.addEventListener('click',()=>this.#switchToFull());
    this.node.querySelectorAll('[data-compact-menu]').forEach(button=>button.onclick=()=>{this.#closeSkillCommand();this.menu=this.menu===button.dataset.compactMenu?'':button.dataset.compactMenu;this.render()});
    this.node.querySelector('[data-compact-new]')?.addEventListener('click',()=>{this.activeId=aiAgent.createSession();this.draft='';this.attachments=[];this.menu='';this.error='';this.editingId=null;this.editDraft='';this.render({focus:true})});
    this.node.querySelectorAll('[data-compact-session]').forEach(button=>button.onclick=()=>{this.activeId=button.dataset.compactSession;this.attachments=[];this.menu='';this.error='';this.editingId=null;this.editDraft='';this.render({focus:true})});
    this.node.querySelector('[data-compact-clear-notifications]')?.addEventListener('click',()=>notifications.clear());
    this.node.querySelectorAll('[data-compact-notification]').forEach(button=>button.onclick=()=>{const item=notifications.snapshot().items.find(entry=>entry.id===button.dataset.compactNotification);if(!item)return;notifications.markRead(item.id);if(item.type==='agent'&&item.agent?.sessionId){this.activeId=item.agent.sessionId;this.menu='';this.render();requestAnimationFrame(()=>{const toolId=item.agent.toolCallId,turnId=item.agent.turnId,target=[...this.node.querySelectorAll('[data-compact-tool]')].find(node=>node.dataset.compactTool===toolId)||[...this.node.querySelectorAll('[data-compact-turn]')].find(node=>node.dataset.compactTurn===turnId);target?.scrollIntoView({block:'center',behavior:'smooth'})});return}if(item.context)agentContext.set(item.context);this.draft=i18n.t('prepareWithFuturePrompt').replace('{title}',item.title);this.menu='';this.render({focus:true})});
    this.node.querySelectorAll('[data-compact-notification-approve],[data-compact-notification-deny]').forEach(button=>button.onclick=event=>{event.stopPropagation();tools.resolveApproval(button.dataset.compactNotificationApprove||button.dataset.compactNotificationDeny,Boolean(button.dataset.compactNotificationApprove))});
    this.node.querySelector('[data-compact-context]')?.addEventListener('click',()=>{this.#closeSkillCommand();this.menu=this.menu==='context'?'':'context';this.render()});
    this.node.querySelector('[data-compact-context-desktop]')?.addEventListener('click',()=>{agentContext.focusDesktop();this.menu='';this.render({focus:true})});
    this.node.querySelectorAll('[data-compact-context-window]').forEach(button=>button.onclick=()=>{const target=shell.windowManager.contextWindows().find(item=>item.id===button.dataset.compactContextWindow);if(target)agentContext.focusWindow(target);this.menu='';this.render({focus:true})});
    this.node.querySelectorAll('[data-compact-model]').forEach(select=>select.addEventListener('change',event=>aiAgent.updateConfig({activeModelKey:event.target.value}).catch(error=>{this.error=error.message;this.render()})));
    this.node.querySelector('[data-compact-attach]')?.addEventListener('click',()=>this.node.querySelector('[data-compact-attachment-input]')?.click());
    const attachmentInput=this.node.querySelector('[data-compact-attachment-input]');if(attachmentInput)attachmentInput.onchange=async()=>{try{const added=await readAgentAttachments(attachmentInput.files);this.attachments=validateAgentAttachments([...this.attachments,...added]);this.error='';this.render({focus:true})}catch(error){this.error=attachmentErrorMessage(error,i18n);this.render({focus:true})}};
    this.node.querySelectorAll('[data-compact-remove-attachment]').forEach(button=>button.onclick=()=>{this.attachments=this.attachments.filter(item=>item.id!==button.dataset.compactRemoveAttachment);this.render({focus:true})});
    this.node.querySelectorAll('[data-compact-copy-turn]').forEach(button=>button.onclick=async()=>{const turn=this.#session()?.turns.find(item=>item.id===button.dataset.compactCopyTurn),text=button.dataset.compactCopyRole==='user'?this.#messageText(turn?.user):this.#assistantText(turn||{responses:[]});if(text&&await clipboard.copyText(text))shell.toast(i18n.t('copiedToClipboard'))});
    this.node.querySelectorAll('[data-compact-tool-expand]').forEach(button=>button.onclick=event=>{event.stopPropagation();const id=button.closest('[data-compact-tool]')?.dataset.compactTool;if(!id)return;if(this.expandedTools.has(id))this.expandedTools.delete(id);else this.expandedTools.add(id);this.render()});
    this.node.querySelectorAll('[data-compact-edit-turn]').forEach(button=>button.onclick=()=>{const turn=this.#session()?.turns.find(item=>item.id===button.dataset.compactEditTurn);this.editingId=turn?.id||null;this.editDraft=this.#messageText(turn?.user);this.render();requestAnimationFrame(()=>{const editor=this.node.querySelector('[data-compact-inline-edit]');editor?.focus();editor?.setSelectionRange(editor.value.length,editor.value.length)})});
    this.node.querySelector('[data-compact-cancel-edit]')?.addEventListener('click',()=>{this.editingId=null;this.editDraft='';this.render({focus:true})});
    const editor=this.node.querySelector('[data-compact-inline-edit]');if(editor){editor.oninput=()=>{this.editDraft=editor.value;editor.style.height='auto';editor.style.height=`${editor.scrollHeight}px`};editor.onkeydown=event=>{if(event.key==='Escape'){event.preventDefault();this.editingId=null;this.editDraft='';this.render({focus:true})}else if(event.key==='Enter'&&(event.metaKey||event.ctrlKey)){event.preventDefault();this.#submitEdit()}}}
    this.node.querySelector('[data-compact-submit-edit]')?.addEventListener('click',()=>this.#submitEdit());
    this.#bindSkillChoices();
    this.node.querySelector('[data-compact-remove-skill]')?.addEventListener('click',()=>{this.selectedSkillName='';this.render({focus:true})});
    const composer=this.node.querySelector('[data-compact-composer]');if(composer){composer.addEventListener('input',event=>{this.draft=event.target.value;this.#syncSkillCommand(event.target);event.target.style.height='auto';event.target.style.height=`${Math.min(112,event.target.scrollHeight)}px`});composer.addEventListener('focus',()=>this.#syncSkillCommand(composer));composer.addEventListener('keydown',event=>{const skills=this.#matchingSkills();if(this.skillCommandQuery!==null&&event.key==='Escape'){event.preventDefault();this.#closeSkillCommand();return}if(this.skillCommandQuery!==null&&skills.length&&['ArrowDown','ArrowUp'].includes(event.key)){event.preventDefault();this.skillCommandIndex=(this.skillCommandIndex+(event.key==='ArrowDown'?1:-1)+skills.length)%skills.length;this.#renderSkillCommand();this.node.querySelector('[data-compact-skill-command] .selected')?.scrollIntoView({block:'nearest'});return}if(this.skillCommandQuery!==null&&event.key==='Enter'&&!event.shiftKey){const selected=skills[this.skillCommandIndex]||skills[0];if(selected){event.preventDefault();this.#chooseSkill(selected.name);return}}if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();this.#send()}})}
    this.node.querySelector('[data-compact-send]')?.addEventListener('click',()=>this.#session()?.busy?aiAgent.abort(this.activeId):this.#send());
    this.node.querySelector('[data-compact-deny]')?.addEventListener('click',event=>tools.resolveApproval(event.currentTarget.dataset.compactDeny,false));
    this.node.querySelector('[data-compact-approve]')?.addEventListener('click',event=>tools.resolveApproval(event.currentTarget.dataset.compactApprove,true));
    this.node.querySelectorAll('[data-compact-query]').forEach(button=>button.onclick=()=>{const pending=queryUser.pendingForSession(this.activeId);if(pending)queryUser.resolve(pending.toolCallId,button.dataset.compactQuery)});
    const conversation=this.node.querySelector('[data-compact-conversation]');if(conversation)conversation.onscroll=()=>{this.follow=conversation.scrollHeight-conversation.scrollTop-conversation.clientHeight<80};
  }

  #submitEdit(){const text=this.node.querySelector('[data-compact-inline-edit]')?.value.trim()||this.editDraft.trim(),turnId=this.editingId;if(!text||!turnId)return;this.editingId=null;this.editDraft='';this.error='';this.follow=true;this.context.aiAgent.editAndResend(this.activeId,turnId,text).catch(error=>{this.error=error.message||String(error);this.render()});this.render()}
  #send(){const composer=this.node.querySelector('[data-compact-composer]'),text=composer?.value.trim()||this.draft.trim();if((!text&&!this.attachments.length)||this.#session()?.busy)return;const skillName=this.selectedSkillName,attachments=this.attachments;this.selectedSkillName='';this.skillCommandQuery=null;this.attachments=[];if(composer){composer.value='';composer.style.height='auto'}this.draft='';this.error='';this.follow=true;this.context.aiAgent.send(this.activeId,text,{skillName,attachments}).catch(error=>{this.error=error.message||String(error);this.render()});this.render()}
}
