import { icon } from '../icons.js';
import { WindowManager } from './WindowManager.js';
import { SetupAssistant } from './SetupAssistant.js';
import { DesktopWidgets } from './DesktopWidgets.js';

export class DesktopShell {
  constructor(root, context, registry) { this.root=root; this.context=context; this.registry=registry; this.launcherOpen=false;this.bootActivities=[];this.lastBootActivity=Date.now(); }

  mount() {
    const { i18n, settings } = this.context;
    document.body.classList.remove('system-ready','system-installed');
    document.documentElement.dataset.theme=settings.get('theme');
    document.documentElement.dataset.reduceMotion=settings.get('reduceMotion')?'true':'false';
    document.documentElement.style.setProperty('--accent',settings.get('accent'));
    this.root.innerHTML=`<div class="boot-screen"><div class="boot-mark">${icon('logo',42)}</div><div class="boot-name">Aeris</div><div class="boot-progress"><i></i></div></div><main class="desktop wallpaper-${settings.get('wallpaper')}" aria-label="${i18n.t('desktop')}"><div class="wallpaper-orb orb-one"></div><div class="wallpaper-orb orb-two"></div><header class="system-bar"><button class="brand-button" data-shell="launcher">${icon('logo',19)}</button><button class="active-app-name" data-shell="launcher">Aeris</button><nav class="app-menu"><button>${i18n.t('applications')}</button><button>${i18n.t('system')}</button></nav><div class="system-tray"><span class="kernel-indicator" data-kernel-state><i></i><b>${i18n.t('booting')}</b></span><button data-open-app="monitor">${icon('memory',17)}</button><button class="network-tray-button" data-network-status="offline" aria-label="${i18n.t('network')}" title="${i18n.t('guestNetworkUnavailable')}">${icon('wifi',17)}</button><button class="clock" data-shell="calendar"></button></div></header><section class="desktop-icons" data-desktop-items></section><section class="window-layer" data-window-layer></section><section class="shell-overlays" data-overlays></section><section id="device-layer" hidden><div id="guest-screen-persistent" hidden><div style="white-space:pre;font:14px monospace;line-height:16px"></div><canvas style="display:none"></canvas></div></section><nav class="dock" aria-label="${i18n.t('applications')}"><button class="dock-launcher" data-shell="launcher">${icon('grid',23)}</button><span class="dock-divider"></span>${this.registry.list().map(app=>`<button class="dock-app" data-open-app="${app.id}" title="${i18n.t(app.title)}"><span class="app-icon app-icon-${app.color}">${icon(app.icon,26)}</span><i></i></button>`).join('')}</nav><div class="notification-banner-stack" aria-live="polite"></div><div class="toast-stack"></div></main>`;
    const brandButton=this.root.querySelector('.brand-button'),activeAppButton=this.root.querySelector('.active-app-name');brandButton.dataset.shell='system-info';delete activeAppButton.dataset.shell;
    const bootScreen=this.root.querySelector('.boot-screen'),tray=this.root.querySelector('.system-tray'),trayButtons=[...tray.querySelectorAll(':scope>button')],notificationButton=document.createElement('button');notificationButton.dataset.shell='notifications';notificationButton.setAttribute('aria-label',i18n.t('notifications'));notificationButton.innerHTML=`${icon('bell',17)}<i class="notification-dot" data-notification-dot></i>`;tray.insertBefore(notificationButton,trayButtons[1]);trayButtons[1].dataset.shell='controls';
    bootScreen.dataset.bootScreen='';bootScreen.setAttribute('role','status');bootScreen.setAttribute('aria-live','polite');
    bootScreen.innerHTML=`<div class="boot-mark">${icon('logo',42)}</div><div class="boot-name">Aeris</div><h1 data-boot-title>${i18n.t('preparingSystem')}</h1><p data-boot-stage>${i18n.t('checkingSystem')}</p><div class="boot-progress"><i data-boot-progress style="width:3%"></i></div><small data-boot-detail>${i18n.t('firstInstallHint')}</small><section class="boot-activity" aria-label="${i18n.t('installationStatus')}"><div class="boot-summary"><div class="boot-step completed" data-boot-completed hidden><i></i><span data-boot-previous></span></div><button class="boot-step current" data-boot-toggle aria-expanded="false"><i></i><span><strong data-boot-current>${i18n.t('checkingSystem')}</strong><em data-boot-heartbeat>${i18n.t('waitingForGuest')}</em></span><b aria-hidden="true">›</b></button></div><div class="boot-details" data-boot-details hidden><header><strong>${i18n.t('installationDetails')}</strong><button data-boot-close aria-label="${i18n.t('hideDetails')}">×</button></header><div class="boot-log" data-boot-log></div><p class="boot-stall-message" data-boot-stall hidden></p></div></section>`;
    const toggleBootDetails=()=>{const button=bootScreen.querySelector('[data-boot-toggle]'),details=bootScreen.querySelector('[data-boot-details]'),expanded=button.getAttribute('aria-expanded')==='true';button.setAttribute('aria-expanded',String(!expanded));details.hidden=expanded};bootScreen.querySelector('[data-boot-toggle]').onclick=toggleBootDetails;bootScreen.querySelector('[data-boot-close]').onclick=toggleBootDetails;
    this.bootActivities=[];this.lastBootActivity=Date.now();clearInterval(this.bootHeartbeatTimer);this.bootHeartbeatTimer=setInterval(()=>this.#updateBootHeartbeat(),1000);
    this.root.querySelector('.desktop').setAttribute('inert','');this.root.querySelector('.desktop').setAttribute('aria-hidden','true');
    const menuButtons=this.root.querySelectorAll('.app-menu>button');if(menuButtons[0])menuButtons[0].dataset.shell='launcher';if(menuButtons[1])menuButtons[1].dataset.shell='system-menu';
    this.windowManager=new WindowManager(this.root.querySelector('[data-window-layer]'),this.registry,{...this.context,i18n});this.#renderDock();
    this.widgets=new DesktopWidgets(this.root.querySelector('.desktop'),this.context);this.widgets.mount();this.#bind();if(settings.get('setupComplete'))this.windowManager.restoreSession();this.#renderDesktop();this.#clock();this.clockTimer=setInterval(()=>this.#clock(),30000);
    setTimeout(()=>this.context.machine.start().catch(error=>this.#bootError(error)),650);
  }

  #bind() {
    this.root.addEventListener('click',event=>{const shell=event.target.closest('[data-shell]'),action=event.target.closest('[data-shell-action]');if(shell?.dataset.shell==='system-info')this.toggleSystemInfo();if(action?.dataset.shellAction==='pin-app')this.#setDockPinned(action.dataset.appId,true);if(action?.dataset.shellAction==='unpin-app')this.#setDockPinned(action.dataset.appId,false);if(action?.dataset.shellAction==='edit-widgets')this.widgets.openGallery()});
    this.root.onclick=event=>{const app=event.target.closest('[data-open-app]'),shell=event.target.closest('[data-shell]'),action=event.target.closest('[data-shell-action]'),banner=event.target.closest('.notification-banner');if(app)this.open(app.dataset.openApp,app.dataset.path);if(action?.dataset.shellAction==='copy-selection')this.#copySelection(this.clipboardTarget,this.clipboardText);if(action?.dataset.shellAction==='select-all')this.#selectAll(this.clipboardTarget);if(action?.dataset.shellAction==='new-desktop-folder')this.#newFolderAt('/home/aeris/Desktop');if(action?.dataset.shellAction==='new-folder-at')this.#newFolderAt(action.dataset.path);if(action?.dataset.shellAction==='open-desktop-entry')this.#openDesktopPath(action.dataset.path,action.dataset.type);if(action?.dataset.shellAction==='rename-desktop-entry')this.#renameDesktopEntry(action.dataset.path);if(action?.dataset.shellAction==='trash-desktop-entry')this.#trashDesktopEntry(action.dataset.path);if(action?.dataset.shellAction==='clear-notifications')this.context.notifications.clear();if(action?.dataset.shellAction==='dismiss-notification'){banner?.remove();this.context.notifications.dismiss(action.dataset.notificationId)}if(action?.dataset.shellAction==='open-notification'){const item=this.context.notifications.snapshot().items.find(entry=>entry.id===action.dataset.notificationId);banner?.remove();if(item)this.open(item.appId);this.context.notifications.markAllRead()}if(action?.dataset.shellAction==='quit-app'){this.windowManager.closeApp(action.dataset.appId);this.closeOverlays()}if(shell?.dataset.shell==='launcher')this.toggleLauncher();if(shell?.dataset.shell==='system-menu')this.toggleSystemMenu();if(shell?.dataset.shell==='calendar')this.toggleCalendar();if(shell?.dataset.shell==='notifications')this.toggleNotifications();if(shell?.dataset.shell==='controls')this.toggleControls();if(!event.target.closest('.floating-panel,.widget-gallery,[data-shell],.notification-banner'))this.closeOverlays()};
    this.root.ondblclick=event=>{const entry=event.target.closest('[data-desktop-path]');if(entry)this.#openDesktopPath(entry.dataset.desktopPath,entry.dataset.desktopType)};
    this.root.oncontextmenu=event=>{
      event.preventDefault();
      const copyTarget=this.context.clipboard.targetFor(event.target);
      if(copyTarget)return this.#openCopyMenu(copyTarget,event.clientX,event.clientY);
      if(event.target.closest('input,textarea,.window'))return this.closeOverlays();
      const app=event.target.closest('[data-open-app]'),entry=event.target.closest('[data-desktop-path]');
      if(app)return this.#openAppMenu(app.dataset.openApp,app.dataset.path,event.clientX,event.clientY);
      if(entry)return this.#openDesktopEntryMenu(entry.dataset.desktopPath,entry.dataset.desktopType,event.clientX,event.clientY);
      this.#openDesktopMenu(event.clientX,event.clientY);
    };
    this.context.kernel.bus.on('machine:status',status=>this.#machineStatus(status));
    this.context.kernel.bus.on('machine:boot-stage',detail=>this.#bootStage(detail));
    this.context.kernel.bus.on('machine:boot-activity',detail=>this.#bootActivity(detail));
    this.context.kernel.bus.on('guest:error',error=>this.#bootError(error));
    this.context.kernel.bus.on('guest:ready',detail=>this.#guestReady(detail));
    this.context.kernel.bus.on('network:change',state=>this.#networkStatus(state));
    this.context.kernel.bus.on('filesystem:changed',detail=>{if(detail?.path==='/home/aeris/Desktop')this.#renderDesktop()});
    this.context.kernel.bus.on('notification:changed',()=>{this.#updateNotificationDot();if(this.panelOpen==='notifications')this.#renderNotificationPanel()});
    this.context.kernel.bus.on('notification:added',item=>this.#showNotificationBanner(item));
    this.context.kernel.bus.on('settings:change',({key,value})=>{if(key==='theme')document.documentElement.dataset.theme=value;if(key==='accent')document.documentElement.style.setProperty('--accent',value);if(key==='wallpaper'){const desktop=this.root.querySelector('.desktop');desktop.className=desktop.className.replace(/wallpaper-\S+/g,'').trim()+` wallpaper-${value}`}if(key==='dockApps')this.#renderDock();if(key==='locale'){document.documentElement.lang=value;this.refreshChrome()}});
    this.context.kernel.bus.on('window:focused',appId=>{const app=this.registry.get(appId);this.root.querySelector('.active-app-name').textContent=app?this.context.i18n.t(app.title):'Aeris'});
    this.context.kernel.bus.on('window:opened',({appId})=>this.#updateAppRunning(appId));
    this.context.kernel.bus.on('window:closed',({appId})=>this.#updateAppRunning(appId));
    this.context.kernel.bus.on('shell:open-app',({id,path})=>this.open(id,path));
    addEventListener('keydown',event=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='c'&&this.context.clipboard.textFor(event.target)){event.preventDefault();this.#copySelection(event.target)}if((event.metaKey||event.ctrlKey)&&event.code==='Space'){event.preventDefault();this.toggleLauncher(true)}if(event.altKey&&event.key==='Tab'){event.preventDefault();this.closeOverlays();this.windowManager.focusNext()}if(event.key==='Escape')this.closeOverlays()});
  }

  open(id,path){this.closeOverlays();this.windowManager.open(id,{path});this.#updateAppRunning(id);if(path&&id==='textedit')setTimeout(()=>this.context.kernel.bus.emit('textedit:open',path));if(path&&id==='preview')setTimeout(()=>this.context.kernel.bus.emit('preview:open',path))}
  toggleLauncher(focus=false){if(this.launcherOpen)return this.closeOverlays();this.launcherOpen=true;const overlay=this.root.querySelector('[data-overlays]');overlay.innerHTML=`<div class="floating-panel launcher-panel"><label class="launcher-search">${icon('search',19)}<input placeholder="${this.context.i18n.t('search')}" data-launcher-search></label><div class="launcher-heading">${this.context.i18n.t('applications')}<small>${this.registry.list().length}</small></div><div class="app-grid">${this.registry.list().map(app=>`<button data-open-app="${app.id}" data-app-name="${this.context.i18n.t(app.title).toLowerCase()}"><span class="app-icon app-icon-${app.color}">${icon(app.icon,29)}</span><span>${this.context.i18n.t(app.title)}</span></button>`).join('')}</div><div class="launcher-footer"><span class="avatar">AE</span><span>Aeris</span><button data-open-app="machine">${icon('power',18)}</button></div></div>`;const input=overlay.querySelector('[data-launcher-search]');input.oninput=()=>overlay.querySelectorAll('[data-app-name]').forEach(button=>button.hidden=!button.dataset.appName.includes(input.value.toLowerCase()));if(focus)input.focus()}
  toggleCalendar(){if(this.panelOpen==='calendar')return this.closeOverlays();this.closeOverlays();this.panelOpen='calendar';const now=new Date(),year=now.getFullYear(),month=now.getMonth(),first=new Date(year,month,1),days=new Date(year,month+1,0).getDate(),overlay=this.root.querySelector('[data-overlays]');overlay.innerHTML=`<div class="floating-panel calendar-panel"><div class="calendar-date"><strong>${now.getDate()}</strong><span>${new Intl.DateTimeFormat(this.context.i18n.t('dateFormat'),{weekday:'long'}).format(now)}<small>${new Intl.DateTimeFormat(this.context.i18n.t('dateFormat'),{month:'long',year:'numeric'}).format(now)}</small></span></div><div class="calendar-week">${Array.from({length:7},(_,i)=>new Intl.DateTimeFormat(this.context.i18n.t('dateFormat'),{weekday:'narrow'}).format(new Date(2024,0,7+i))).map(x=>`<b>${x}</b>`).join('')}</div><div class="calendar-grid">${Array(first.getDay()).fill('<i></i>').join('')}${Array.from({length:days},(_,i)=>`<button class="${i+1===now.getDate()?'today':''}" data-open-app="calendar">${i+1}</button>`).join('')}</div><hr><button class="panel-open-row" data-open-app="calendar">${icon('calendar',17)}<span>${this.context.i18n.t('openCalendar')}</span></button></div>`}
  toggleControls(){if(this.panelOpen==='controls')return this.closeOverlays();this.closeOverlays();this.panelOpen='controls';const {i18n,settings,system}=this.context,state=system.networkState,online=state.status==='connected',overlay=this.root.querySelector('[data-overlays]');overlay.innerHTML=`<div class="floating-panel quick-panel"><div class="quick-title"><strong>${i18n.t('controlCenter')}</strong><small>${i18n.t(online?'online':state.status==='connecting'?'connecting':'offline')}</small></div><div class="quick-grid"><button class="${online?'active':''}" data-open-app="settings">${icon('wifi',20)}<span>${i18n.t('network')}<small>${online?state.address:i18n.t(state.status==='connecting'?'connecting':'offline')}</small></span></button><button data-control-theme class="${settings.get('theme')==='dark'?'active':''}">${icon(settings.get('theme')==='dark'?'moon':'sun',20)}<span>${i18n.t('appearance')}<small>${i18n.t(settings.get('theme'))}</small></span></button><button data-control-motion class="${settings.get('reduceMotion')?'active':''}">${icon('accessibility',20)}<span>${i18n.t('reduceMotion')}<small>${i18n.t(settings.get('reduceMotion')?'on':'off')}</small></span></button><button data-open-app="settings">${icon('settings',20)}<span>${i18n.t('settings')}<small>${i18n.t('allSettings')}</small></span></button></div><label class="range-row">${icon('volume',18)}<input type="range" min="0" max="100" value="70"><span>70%</span></label></div>`;overlay.querySelector('[data-control-theme]').onclick=()=>settings.set('theme',settings.get('theme')==='dark'?'light':'dark');overlay.querySelector('[data-control-motion]').onclick=()=>settings.set('reduceMotion',!settings.get('reduceMotion'));const range=overlay.querySelector('.range-row input');range.oninput=()=>range.nextElementSibling.textContent=`${range.value}%`}
  toggleSystemMenu(){if(this.panelOpen==='system-menu')return this.closeOverlays();this.closeOverlays();this.panelOpen='system-menu';const {i18n}=this.context,overlay=this.root.querySelector('[data-overlays]');overlay.innerHTML=`<div class="floating-panel desktop-context-menu system-menu-panel"><header>${icon('logo',18)}<strong>Aeris</strong></header><button data-open-app="settings">${icon('settings',16)}<span>${i18n.t('settings')}</span></button><button data-open-app="monitor">${icon('memory',16)}<span>${i18n.t('monitor')}</span></button><button data-open-app="machine">${icon('vm',16)}<span>${i18n.t('machine')}</span></button><i></i><button data-open-app="settings">${icon('logo',16)}<span>${i18n.t('aboutAeris')}</span></button></div>`}
  toggleSystemInfo(){if(this.panelOpen==='system-info')return this.closeOverlays();this.closeOverlays();this.panelOpen='system-info';const {i18n,machine,settings}=this.context,overlay=this.root.querySelector('[data-overlays]'),status=i18n.t(machine.status==='running'?'running':machine.status==='booting'?'booting':'stopped');overlay.innerHTML=`<div class="floating-panel system-info-panel"><header><span>${icon('logo',30)}</span><div><strong>Aeris</strong><small>${i18n.t('systemInformation')}</small></div></header><div class="system-info-grid"><span>${i18n.t('version')}</span><strong>0.4.0</strong><span>${i18n.t('engine')}</span><strong>v86 / WebAssembly</strong><span>${i18n.t('architecture')}</span><strong>x86 · Alpine Linux</strong><span>${i18n.t('memory')}</span><strong>${settings.get('memory')} MB</strong><span>${i18n.t('status')}</span><strong>${status}</strong><span>${i18n.t('savedSystem')}</span><strong data-system-storage>—</strong></div><footer><button data-open-app="monitor">${i18n.t('moreInfo')}</button><button data-open-app="settings">${i18n.t('settings')}</button></footer></div>`;machine.persistenceInfo().then(info=>{const node=overlay.querySelector('[data-system-storage]');if(node)node.textContent=info.size?`${(info.size/1048576).toFixed(1)} MB`:i18n.t('notSaved')}).catch(()=>{})}
  toggleNotifications(){if(this.panelOpen==='notifications')return this.closeOverlays();this.closeOverlays();this.panelOpen='notifications';this.#renderNotificationPanel();this.context.notifications.markAllRead()}
  #renderNotificationPanel(){const {i18n,notifications}=this.context,overlay=this.root.querySelector('[data-overlays]'),items=notifications.snapshot().items;overlay.innerHTML=`<div class="floating-panel notification-panel"><header><strong>${i18n.t('notifications')}</strong>${items.length?`<button data-shell-action="clear-notifications">${i18n.t('clearAll')}</button>`:''}</header><div class="notification-list">${items.length?items.map(item=>this.#notificationCard(item)).join(''):`<div class="empty-state">${icon('bell',28)}<span>${i18n.t('noNotifications')}</span></div>`}</div></div>`}
  #notificationCard(item){const {i18n}=this.context,app=this.registry.get(item.appId),date=new Date(item.createdAt);return`<article class="${item.read?'':'unread'}" data-shell-action="open-notification" data-notification-id="${item.id}"><span class="app-icon app-icon-${app?.color||'blue'}">${icon(app?.icon||'bell',18)}</span><div><small>${this.#escape(app?i18n.t(app.title):'Aeris')}</small><strong>${this.#escape(item.title)}</strong><p>${this.#escape(item.message)}</p><time>${new Intl.DateTimeFormat(i18n.t('dateFormat'),{hour:'2-digit',minute:'2-digit'}).format(date)}</time></div><button data-shell-action="dismiss-notification" data-notification-id="${item.id}" aria-label="${i18n.t('dismiss')}">${icon('close',11)}</button></article>`}
  #updateNotificationDot(){const dot=this.root.querySelector('[data-notification-dot]'),count=this.context.notifications.snapshot().unread;if(dot){dot.classList.toggle('visible',count>0);dot.parentElement?.setAttribute('aria-label',count?`${this.context.i18n.t('notifications')}, ${count}`:this.context.i18n.t('notifications'))}}
  #showNotificationBanner(item){const stack=this.root.querySelector('.notification-banner-stack'),app=this.registry.get(item.appId);if(!stack||!app)return;const banner=document.createElement('article');banner.className='notification-banner';banner.dataset.shellAction='open-notification';banner.dataset.notificationId=item.id;banner.innerHTML=`<span class="app-icon app-icon-${app.color}">${icon(app.icon,20)}</span><div><small>${this.context.i18n.t(app.title)}</small><strong>${this.#escape(item.title)}</strong><p>${this.#escape(item.message)}</p></div><button data-shell-action="dismiss-notification" data-notification-id="${item.id}" aria-label="${this.context.i18n.t('dismiss')}">${icon('close',11)}</button>`;stack.prepend(banner);setTimeout(()=>{banner.classList.add('leaving');setTimeout(()=>banner.remove(),180)},6500)}
  #openDesktopMenu(x,y){
    this.launcherOpen=false;
    const overlay=this.root.querySelector('[data-overlays]'),width=190,height=220;
    const left=Math.max(8,Math.min(x,innerWidth-width-8)),top=Math.max(50,Math.min(y,innerHeight-height-78));
    overlay.innerHTML=`<div class="floating-panel desktop-context-menu" style="left:${left}px;top:${top}px"><button data-shell-action="new-desktop-folder">${icon('plus',16)}<span>${this.context.i18n.t('newFolder')}</span></button><button data-shell-action="edit-widgets">${icon('grid',16)}<span>${this.context.i18n.t('editWidgets')}</span></button><i></i><button data-open-app="files" data-path="/home/aeris/Desktop">${icon('folder',16)}<span>${this.context.i18n.t('openDesktop')}</span></button><button data-open-app="terminal">${icon('terminal',16)}<span>${this.context.i18n.t('terminal')}</span></button><button data-open-app="settings">${icon('settings',16)}<span>${this.context.i18n.t('settings')}</span></button></div>`;
  }
  #openAppMenu(id,path,x,y){const app=this.registry.get(id);if(!app)return;const running=this.windowManager.isOpen(id),pinned=this.#dockApps().includes(id);this.#positionedMenu(x,y,`<header>${icon(app.icon,17)}<strong>${this.context.i18n.t(app.title)}</strong>${running?`<em>${this.context.i18n.t('running')}</em>`:''}</header><button data-open-app="${id}"${path?` data-path="${path}"`:''}>${icon('play',16)}<span>${this.context.i18n.t('open')}</span></button>${running?`<button class="menu-danger" data-shell-action="quit-app" data-app-id="${id}">${icon('close',16)}<span>${this.context.i18n.t('quit')}</span></button>`:''}<i></i>${app.dockSpecial||app.dockLeading?'':`<button data-shell-action="${pinned?'unpin-app':'pin-app'}" data-app-id="${id}">${icon('dock',16)}<span>${this.context.i18n.t(pinned?'removeFromDock':'keepInDock')}</span></button>`}<button data-open-app="settings">${icon('settings',16)}<span>${this.context.i18n.t('appSettings')}</span></button>`,'app-context-menu')}
  #openDesktopEntryMenu(path,type,x,y){const safe=this.#escape(path);this.#positionedMenu(x,y,`<button data-shell-action="open-desktop-entry" data-path="${safe}" data-type="${type}">${icon(type==='directory'?'folder':'document',16)}<span>${this.context.i18n.t('open')}</span></button>${type==='directory'?`<button data-shell-action="new-folder-at" data-path="${safe}">${icon('plus',16)}<span>${this.context.i18n.t('newFolder')}</span></button>`:''}<i></i><button data-shell-action="rename-desktop-entry" data-path="${safe}">${icon('textedit',16)}<span>${this.context.i18n.t('rename')}</span></button><button class="menu-danger" data-shell-action="trash-desktop-entry" data-path="${safe}">${icon('delete',16)}<span>${this.context.i18n.t('moveToTrash')}</span></button>`,'desktop-entry-menu')}
  #positionedMenu(x,y,content,className){this.launcherOpen=false;const overlay=this.root.querySelector('[data-overlays]'),left=Math.max(8,Math.min(x,innerWidth-198)),top=Math.max(50,Math.min(y,innerHeight-220));overlay.innerHTML=`<div class="floating-panel desktop-context-menu ${className}" style="left:${left}px;top:${top}px">${content}</div>`}
  #openCopyMenu(target,x,y){this.clipboardTarget=target;this.clipboardText=this.context.clipboard.textFor(target);const hasSelection=Boolean(this.clipboardText);this.#positionedMenu(x,y,`<button data-shell-action="copy-selection" ${hasSelection?'':'disabled'}>${icon('copy',16)}<span>${this.context.i18n.t('copy')}</span><kbd>⌘C</kbd></button><i></i><button data-shell-action="select-all">${icon('check',16)}<span>${this.context.i18n.t('selectAll')}</span><kbd>⌘A</kbd></button>`,'clipboard-menu')}
  async #copySelection(target,text=''){const copied=text?await this.context.clipboard.copyText(text):await this.context.clipboard.copyFrom(target).catch(()=>false);this.closeOverlays();if(copied)this.toast(this.context.i18n.t('copiedToClipboard'))}
  #selectAll(target){this.closeOverlays();requestAnimationFrame(()=>this.context.clipboard.selectAll(target))}
  #openDesktopPath(path,type){type==='directory'?this.open('files',path):this.open(/\.(png|jpe?g|gif|webp|svg|pdf)$/i.test(path)?'preview':'textedit',path)}
  async #newFolderAt(path){this.closeOverlays();const {dialog,i18n,system,kernel}=this.context;if(!system.ready)return this.toast(i18n.t('startMachine'));const entries=await system.list(path),name=await dialog.prompt({title:i18n.t('newFolder'),placeholder:i18n.t('folderName'),validate:value=>!value||value==='.'||value==='..'||value.includes('/')?i18n.t('invalidName'):entries.some(entry=>entry.name===value)?i18n.t('nameExists'):''});if(!name)return;await system.mkdir(`${path}/${name}`);kernel.bus.emit('filesystem:changed',{path,name,type:'directory'});this.toast(i18n.t('folderCreated'))}
  async #renameDesktopEntry(path){this.closeOverlays();const {dialog,i18n,system}=this.context,original=path.split('/').at(-1),name=await dialog.prompt({title:i18n.t('rename'),value:original,validate:value=>!value||value.includes('/')?i18n.t('invalidName'):''});if(!name||name===original)return;await system.rename(path,name);await this.#renderDesktop()}
  async #trashDesktopEntry(path){this.closeOverlays();const {dialog,i18n,system}=this.context,approved=await dialog.confirm({title:i18n.t('moveToTrash'),message:i18n.t('trashConfirm').replace('{name}',path.split('/').at(-1)),confirmLabel:i18n.t('moveToTrash'),danger:true});if(!approved)return;await system.trash(path);await this.#renderDesktop()}
  async #renderDesktop(){const {i18n,system}=this.context,node=this.root.querySelector('[data-desktop-items]');if(!node)return;const staticItems=`<button class="desktop-item" data-open-app="files" data-path="/mnt/aeris"><span class="desktop-file-icon">${icon('folder',28)}</span><span>${i18n.t('shared')}</span></button><button class="desktop-item" data-open-app="machine"><span class="app-icon app-icon-violet">${icon('vm',25)}</span><span>${i18n.t('machine')}</span></button>`;node.innerHTML=staticItems;if(!system.ready)return;try{const entries=await system.list('/home/aeris/Desktop');node.insertAdjacentHTML('afterbegin',entries.map(entry=>`<button class="desktop-item" data-desktop-path="/home/aeris/Desktop/${this.#escape(entry.name)}" data-desktop-type="${entry.type}"><span class="desktop-file-icon">${icon(entry.type==='directory'?'folder':'document',28)}</span><span>${this.#escape(entry.name)}</span></button>`).join(''))}catch{}}
  #escape(value){return String(value).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
  #dockApps(){return this.context.settings.get('dockApps')||[]}
  #setDockPinned(id,pinned){if(this.registry.get(id)?.dockSpecial||this.registry.get(id)?.dockLeading)return;const apps=this.#dockApps().filter(appId=>appId!==id);if(pinned)apps.push(id);this.context.settings.set('dockApps',apps);this.closeOverlays()}
  #renderDock(){const dock=this.root.querySelector('.dock');if(!dock)return;const {i18n}=this.context,pinned=this.#dockApps(),leading=this.registry.list().filter(app=>app.dockLeading),apps=this.registry.list().filter(app=>!app.dockSpecial&&!app.dockLeading&&(pinned.includes(app.id)||this.windowManager?.isOpen(app.id))),trash=this.registry.get('trash');const button=app=>`<button class="dock-app ${app.dockSpecial?'dock-special ':''}${app.dockLeading?'dock-leading ':''}${this.windowManager?.isOpen(app.id)?'running':''}" data-open-app="${app.id}" title="${i18n.t(app.title)}"><span class="app-icon app-icon-${app.color}">${icon(app.icon,26)}</span><i></i></button>`;dock.innerHTML=`${leading.map(button).join('')}<span class="dock-divider dock-ai-divider"></span><button class="dock-launcher" data-shell="launcher">${icon('grid',23)}</button><span class="dock-divider"></span>${apps.map(button).join('')}${trash?`<span class="dock-divider dock-trash-divider"></span>${button(trash)}`:''}`}
  #updateAppRunning(){this.#renderDock()}
  closeOverlays(){this.launcherOpen=false;this.panelOpen=null;this.root.querySelector('[data-overlays]').innerHTML=''}
  refreshChrome(){const {i18n}=this.context;this.root.querySelector('.app-menu').innerHTML=`<button>${i18n.t('applications')}</button><button>${i18n.t('system')}</button>`;this.root.querySelector('.desktop').setAttribute('aria-label',i18n.t('desktop'));this.registry.list().forEach(app=>{const dock=this.root.querySelector(`.dock-app[data-open-app="${app.id}"]`);if(dock)dock.title=i18n.t(app.title)});this.#renderDesktop();this.windowManager.refreshLabels();this.#clock();this.#machineStatus(this.context.machine.status)}
  toast(message,title='Aeris'){const stack=this.root.querySelector('.toast-stack'),toast=document.createElement('div');toast.className='toast';toast.innerHTML=`<span>${icon('check',16)}</span>${message}`;stack.appendChild(toast);setTimeout(()=>toast.remove(),3200)}
  #clock(){const now=new Date(),locale=this.context.i18n.t('dateFormat');this.root.querySelector('.clock').textContent=new Intl.DateTimeFormat(locale,{weekday:'short',hour:'2-digit',minute:'2-digit'}).format(now)}
  #machineStatus(status){const node=this.root.querySelector('[data-kernel-state]');if(!node)return;node.className=`kernel-indicator kernel-${status}`;node.querySelector('b').textContent=this.context.i18n.t(status==='running'?'running':status==='booting'?'booting':'stopped')}
  #networkStatus(state){const node=this.root.querySelector('[data-network-status]');if(!node)return;node.dataset.networkStatus=state.status;node.title=state.status==='connected'?`${this.context.i18n.t('guestNetworkConnected')} · ${state.address}`:this.context.i18n.t(state.status==='connecting'?'connecting':'guestNetworkUnavailable');if(this.panelOpen==='controls'){this.panelOpen=null;this.toggleControls()}}
  #bootStage({label,progress,mode}){const screen=this.root.querySelector('[data-boot-screen]');if(!screen)return;screen.dataset.mode=mode;screen.querySelector('[data-boot-title]').textContent=this.context.i18n.t(mode==='restore'?'restoringAeris':mode==='install'?'installingAeris':'preparingSystem');screen.querySelector('[data-boot-stage]').textContent=this.context.i18n.t(label);screen.querySelector('[data-boot-detail]').textContent=this.context.i18n.t(mode==='restore'?'restoreHint':'firstInstallHint');const bar=screen.querySelector('[data-boot-progress]');bar.style.width=`${Math.max(3,Math.min(100,progress||3))}%`}
  #bootActivity({key,message,kind='console',timestamp=Date.now(),progress=0}={}){const screen=this.root.querySelector('[data-boot-screen]');if(!screen)return;const label=message||this.context.i18n.t(key);if(!label)return;this.lastBootActivity=timestamp;screen.classList.remove('boot-stalled');screen.querySelector('[data-boot-stall]').hidden=true;const rendered=kind==='progress'?`${label} ${Math.round(progress)}%`:label,last=this.bootActivities.at(-1);if(last?.label===rendered){last.timestamp=timestamp}else{this.bootActivities.push({label:rendered,kind,timestamp});this.bootActivities=this.bootActivities.slice(-10)}this.#renderBootActivity();this.#updateBootHeartbeat()}
  #renderBootActivity(){const screen=this.root.querySelector('[data-boot-screen]'),log=screen?.querySelector('[data-boot-log]');if(!log)return;const i18n=this.context.i18n,last=this.bootActivities.at(-1),isComplete=item=>item&&(/\[\s*ok\s*\]\s*$/i.test(item.label)||item.kind==='stage'),lastCompleted=isComplete(last),previous=lastCompleted?last:[...this.bootActivities.slice(0,-1)].reverse().find(isComplete),current=lastCompleted?i18n.t('waitingForNextStep'):(last?.label||i18n.t('checkingSystem')),completedRow=screen.querySelector('[data-boot-completed]');completedRow.hidden=!previous;if(previous)screen.querySelector('[data-boot-previous]').textContent=previous.label;screen.querySelector('[data-boot-current]').textContent=current;screen.querySelector('.boot-summary .current').classList.toggle('waiting',Boolean(lastCompleted));log.innerHTML=this.bootActivities.map(item=>`<div class="boot-log-row boot-log-${item.kind}"><i></i><span>${this.#escape(item.label)}</span><time data-activity-time="${item.timestamp}"></time></div>`).join('')}
  #updateBootHeartbeat(){const screen=this.root.querySelector('[data-boot-screen]'),heartbeat=screen?.querySelector('[data-boot-heartbeat]');if(!heartbeat||document.body.classList.contains('system-ready'))return;const seconds=Math.max(0,Math.floor((Date.now()-this.lastBootActivity)/1000)),i18n=this.context.i18n;let text=seconds<5?i18n.t('activityNow'):i18n.t(seconds<30?'lastActivitySeconds':seconds<90?'guestBusySeconds':'startupMayBeStalled').replace('{seconds}',seconds);heartbeat.textContent=text;screen.querySelectorAll('[data-activity-time]').forEach(node=>{const age=Math.max(0,Math.floor((Date.now()-Number(node.dataset.activityTime))/1000));node.textContent=age<5?i18n.t('now'):i18n.t('secondsAgo').replace('{seconds}',age)});const stalled=seconds>=90;screen.classList.toggle('boot-stalled',stalled);const stall=screen.querySelector('[data-boot-stall]');if(stalled){const minutes=Math.floor(seconds/60);stall.hidden=false;stall.textContent=seconds>=300?i18n.t('startupStalledMinutes').replace('{minutes}',minutes):i18n.t('startupMayBeStalled').replace('{seconds}',seconds)}else stall.hidden=true}
  #guestReady(detail){this.#renderDesktop();if(this.context.settings.get('setupComplete'))return this.#finishBoot(detail);this.#bootStage({label:'systemReady',progress:100,mode:detail?.restored?'restore':'install'});setTimeout(()=>{document.body.classList.add('system-installed');this.setupAssistant=new SetupAssistant(this.root,this.context,async()=>this.#finishBoot(detail));this.setupAssistant.mount()},450)}
  #finishBoot({restored}={}){this.#bootStage({label:'systemReady',progress:100,mode:restored?'restore':'install'});clearInterval(this.bootHeartbeatTimer);setTimeout(()=>{const desktop=this.root.querySelector('.desktop');desktop?.removeAttribute('inert');desktop?.removeAttribute('aria-hidden');document.body.classList.add('system-ready');this.toast(this.context.i18n.t('systemReady'))},450)}
  #bootError(error){const screen=this.root.querySelector('[data-boot-screen]');if(!screen)return;clearInterval(this.bootHeartbeatTimer);screen.classList.add('boot-error');screen.querySelector('[data-boot-title]').textContent=this.context.i18n.t('installationFailed');screen.querySelector('[data-boot-stage]').textContent=error?.message||String(error);const detail=screen.querySelector('[data-boot-detail]');detail.innerHTML=`${this.#escape(this.context.i18n.t('installationFailedHint'))}<span class="boot-recovery-actions"><button data-boot-retry>${this.context.i18n.t('tryAgain')}</button><button class="danger" data-boot-reset>${this.context.i18n.t('eraseReinstall')}</button></span>`;detail.querySelector('[data-boot-retry]').onclick=async()=>{screen.classList.remove('boot-error');detail.textContent=this.context.i18n.t('firstInstallHint');try{await this.context.machine.stop(false);await this.context.machine.start()}catch(reason){this.#bootError(reason)}};detail.querySelector('[data-boot-reset]').onclick=async()=>{const approved=await this.context.dialog.confirm({title:this.context.i18n.t('eraseReinstall'),message:this.context.i18n.t('eraseReinstallWarning'),confirmLabel:this.context.i18n.t('eraseReinstall'),danger:true});if(!approved)return;await this.context.machine.stop(false);await this.context.machine.clearPersistedState();this.context.settings.set('setupComplete',false);localStorage.removeItem('aeris.window-session');localStorage.removeItem('aeris.setup.draft');location.reload()};this.#bootActivity({message:error?.message||String(error),kind:'error'})}
}
