import {icon} from '../icons.js';
import {weatherCondition} from '../services/WeatherService.js';
const DEFAULTS=[{id:'date',x:22,y:72},{id:'agenda',x:22,y:242},{id:'system',x:296,y:72},{id:'weather',x:296,y:262}];
const esc=value=>String(value??'').replace(/&/g,'&amp;').replace(/</g,'&lt;');
const dateKey=date=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
export class DesktopWidgets{
  constructor(desktop,context){this.desktop=desktop;this.context=context;this.items=this.#load();this.timers=[];this.extensionMounts=new WeakMap()}
  mount(){this.layer=document.createElement('section');this.layer.className='desktop-widgets';this.layer.setAttribute('aria-label',this.context.i18n.t('widgets'));this.desktop.insertBefore(this.layer,this.desktop.querySelector('[data-desktop-items]'));if(!localStorage.getItem('aeris.widgets.weather.v2')){if(this.context.registry.get('weather')&&!this.items.some(x=>x.id==='weather'))this.items.push({id:'weather',x:296,y:262});localStorage.setItem('aeris.widgets.weather.v2','1');this.#save()}this.items=this.items.filter(item=>this.#supported(item));this.render();this.timers.push(setInterval(()=>this.update(),1000));this.offs=[this.context.kernel.bus.on('userdata:change',detail=>{if(detail?.name==='calendar'||detail?.name==='reminders')this.render(['agenda'])}),this.context.kernel.bus.on('machine:status',()=>this.update()),this.context.kernel.bus.on('metrics:update',()=>this.update()),this.context.kernel.bus.on('weather:update',()=>this.render(['weather'])),this.context.registry.subscribe(change=>{if(change.type==='unregistered'){this.items=this.items.filter(item=>this.#supported(item));this.#save();this.render()}}),this.context.widgetRegistry.subscribe(change=>{if(change.type==='unregistered'){this.items=this.items.filter(item=>item.id!==change.widget.id);this.#save()}this.render(change.type==='updated'?[change.widget.id]:null)})];if(this.context.registry.get('weather'))this.context.weather.refresh().catch(()=>{})}
  destroy(){this.timers.forEach(clearInterval);this.offs?.forEach(off=>off());for(const widget of this.layer?.children||[])this.#unmount(widget);this.layer?.remove()}
  #load(){try{const value=JSON.parse(localStorage.getItem('aeris.desktop.widgets')||'null');if(Array.isArray(value))return value}catch{}return structuredClone(DEFAULTS)}
  #save(){localStorage.setItem('aeris.desktop.widgets',JSON.stringify(this.items))}
  #supported(item){if(item.id==='weather')return Boolean(this.context.registry.get('weather'));if(item.id==='system')return Boolean(this.context.registry.get('monitor'));if(item.id==='agenda')return Boolean(this.context.registry.get('calendar')||this.context.registry.get('reminders'));return true}
  #calendar(){try{return JSON.parse(localStorage.getItem('aeris.userdata.calendar')||'{"events":[]}').events||[]}catch{return[]}}
  #reminders(){try{return JSON.parse(localStorage.getItem('aeris.userdata.reminders')||'[]')}catch{return[]}}
  #markup(item){const {i18n,machine}=this.context,now=new Date(),definition=this.context.widgetRegistry.get(item.id),size=item.size||definition?.defaultSize||'medium',style=`--widget-x:${item.x}px;--widget-y:${item.y}px`,head=(id,label,glyph='')=>`<header data-widget-drag><span>${glyph?icon(glyph,15):''}${label}</span><button data-widget-remove="${id}">×</button></header>`;
    if(definition?.extension){const label=this.#localized(definition.name);return`<article class="desktop-widget widget-extension widget-size-${size}" data-widget="${esc(item.id)}" data-widget-extension style="${style}">${head(item.id,esc(label),definition.glyph)}<div class="widget-extension-content" data-widget-content></div></article>`}
    if(item.id==='date')return`<article class="desktop-widget widget-date" data-widget="date" style="${style}">${head('date',new Intl.DateTimeFormat(i18n.t('dateFormat'),{weekday:'long'}).format(now))}<strong data-widget-day>${now.getDate()}</strong><p>${new Intl.DateTimeFormat(i18n.t('dateFormat'),{month:'long',year:'numeric'}).format(now)}</p><footer data-widget-time></footer></article>`;
    if(item.id==='agenda'){const today=dateKey(now),events=this.#calendar().filter(e=>(e.start||e.date||'').startsWith(today)).sort((a,b)=>String(a.start).localeCompare(String(b.start))).slice(0,3),reminders=this.#reminders().filter(e=>!e.done&&(!e.due||e.due===today)).slice(0,2);return`<article class="desktop-widget widget-agenda" data-widget="agenda" style="${style}">${head('agenda',i18n.t('upNext'),'calendar')}<div>${events.length||reminders.length?[...events.map(e=>`<button data-open-app="calendar"><i style="--item-color:#d86582"></i><span><strong>${esc(e.title)}</strong><small>${e.allDay?i18n.t('allDay'):(e.start||'').slice(11,16)}</small></span></button>`),...reminders.map(e=>`<button data-open-app="reminders"><i style="--item-color:#7868dc"></i><span><strong>${esc(e.title)}</strong><small>${i18n.t('reminders')}</small></span></button>`)].join(''):`<div class="widget-empty">${icon('check',17)}<span>${i18n.t('nothingScheduled')}</span></div>`}</div><footer><button data-open-app="calendar">${i18n.t('openCalendar')} ${icon('chevron',11)}</button></footer></article>`}
    if(item.id==='system'){const sample=this.context.metrics.snapshot();return`<article class="desktop-widget widget-system" data-widget="system" style="${style}">${head('system',i18n.t('systemStatus'),'memory')}<div class="widget-system-orb"><svg viewBox="0 0 42 42"><circle cx="21" cy="21" r="17"></circle><circle data-widget-ring cx="21" cy="21" r="17"></circle></svg><strong data-widget-memory-percent>${sample.ready?sample.percent:'—'}<small>${sample.ready?'%':i18n.t('memory')}</small></strong></div><dl><div><dt>${i18n.t('memoryUsed')}</dt><dd data-widget-memory-used>${sample.ready?`${Math.round(sample.usedKb/1024)} MB`:'—'}</dd></div><div><dt>${i18n.t('memoryAvailable')}</dt><dd data-widget-memory-available>${sample.ready?`${Math.round(sample.availableKb/1024)} MB`:'—'}</dd></div><div><dt>${i18n.t('uptime')}</dt><dd data-widget-uptime>00:00</dd></div></dl><footer><button data-open-app="monitor">${i18n.t('moreInfo')} ${icon('chevron',11)}</button></footer></article>`}
    if(item.id==='weather'){const s=this.context.weather.snapshot(),c=s.data?.current,condition=weatherCondition(c?.weather_code,i18n.locale),daily=s.data?.daily;return`<article class="desktop-widget widget-weather widget-weather-${condition.key}" data-widget="weather" style="${style}">${head('weather',esc(s.location.name),'location')}<button class="widget-weather-main" data-open-app="weather"><span>${icon(condition.glyph,48)}</span><strong>${c?Math.round(c.temperature_2m):'—'}°</strong><div><b>${condition.label}</b><small>${daily?`H:${Math.round(daily.temperature_2m_max[0])}° L:${Math.round(daily.temperature_2m_min[0])}°`:i18n.t('loadingWeather')}</small></div></button><footer><button data-open-app="weather">${i18n.t('openWeather')} ${icon('chevron',11)}</button></footer></article>`}
    if(item.id==='launcher')return`<article class="desktop-widget widget-launcher" data-widget="launcher" style="${style}">${head('launcher',i18n.t('favorites'))}<div>${['files','photos','calendar','weather'].map(id=>this.context.registry.get(id)).filter(Boolean).map(app=>`<button data-open-app="${app.id}" title="${i18n.t(app.title)}"><span class="app-icon app-icon-${app.color}">${icon(app.icon,20)}</span></button>`).join('')}</div></article>`;return''
  }
  render(refreshIds=null){const refresh=refreshIds?new Set(refreshIds):null,existing=new Map([...this.layer.children].map(widget=>[widget.dataset.widget,widget])),keep=new Set(),available=this.items.filter(item=>this.context.widgetRegistry.get(item.id)&&this.#supported(item));available.forEach((item,index)=>{let widget=existing.get(item.id);if(!widget||refresh?.has(item.id)){const template=document.createElement('template');template.innerHTML=this.#markup(item);const next=template.content.firstElementChild;if(widget){this.#unmount(widget);widget.replaceWith(next)}widget=next}if(!widget)return;keep.add(item.id);const current=this.layer.children[index];if(current!==widget)this.layer.insertBefore(widget,current||null);this.#mountExtension(widget,item)});[...this.layer.children].forEach(widget=>{if(!keep.has(widget.dataset.widget)){this.#unmount(widget);widget.remove()}});this.layer.querySelectorAll('[data-widget-remove]').forEach(button=>button.onclick=event=>{event.stopPropagation();this.items=this.items.filter(item=>item.id!==button.dataset.widgetRemove);this.#save();this.render()});this.layer.querySelectorAll('[data-widget-drag]').forEach(handle=>this.#drag(handle.closest('[data-widget]'),handle));this.update()}
  #mountExtension(widget,item){if(!widget.hasAttribute('data-widget-extension')||this.extensionMounts.has(widget))return;const definition=this.context.widgetRegistry.get(item.id),content=widget.querySelector('[data-widget-content]');if(!definition?.mount||!content)return;const cleanup=definition.mount(content,this.context,{size:item.size||definition.defaultSize||'medium',instanceId:item.instanceId||item.id});this.extensionMounts.set(widget,typeof cleanup==='function'?cleanup:()=>{})}
  #unmount(widget){const cleanup=this.extensionMounts.get(widget);if(cleanup){cleanup();this.extensionMounts.delete(widget)}}
  #localized(value){const locale=this.context.i18n.locale||'en';return typeof value==='string'?this.context.i18n.t(value):value?.[locale]||value?.en||Object.values(value||{})[0]||''}
  update(){const now=new Date(),{i18n,machine,metrics}=this.context;this.layer.querySelector('[data-widget-day]')?.replaceChildren(String(now.getDate()));this.layer.querySelector('[data-widget-time]')?.replaceChildren(new Intl.DateTimeFormat(i18n.t('dateFormat'),{hour:'2-digit',minute:'2-digit'}).format(now));const seconds=Math.floor(machine.uptime()/1000),uptime=this.layer.querySelector('[data-widget-uptime]');if(uptime)uptime.textContent=`${String(Math.floor(seconds/3600)).padStart(2,'0')}:${String(Math.floor(seconds%3600/60)).padStart(2,'0')}`;const status=this.layer.querySelector('[data-widget-machine]');if(status)status.textContent=i18n.t(machine.status==='running'?'running':machine.status==='booting'?'booting':'stopped');const sample=metrics.snapshot(),percent=sample.ready?Math.max(0,Math.min(100,sample.percent)):0,ring=this.layer.querySelector('[data-widget-ring]');if(ring)ring.style.strokeDashoffset=String(107-(107*percent/100));const memoryPercent=this.layer.querySelector('[data-widget-memory-percent]');if(memoryPercent)memoryPercent.innerHTML=`${sample.ready?percent:'—'}<small>${sample.ready?'%':i18n.t('memory')}</small>`;this.layer.querySelector('[data-widget-memory-used]')?.replaceChildren(sample.ready?`${Math.round(sample.usedKb/1024)} MB`:'—');this.layer.querySelector('[data-widget-memory-available]')?.replaceChildren(sample.ready?`${Math.round(sample.availableKb/1024)} MB`:'—')}
  #drag(widget,handle){let drag=null;const stop=event=>{if(!drag)return;drag=null;if(handle.hasPointerCapture(event.pointerId))handle.releasePointerCapture(event.pointerId);const item=this.items.find(entry=>entry.id===widget.dataset.widget);item.x=parseFloat(widget.style.getPropertyValue('--widget-x'))||0;item.y=parseFloat(widget.style.getPropertyValue('--widget-y'))||0;this.#save()};handle.onpointerdown=event=>{if(event.button!==0||event.target.closest('button'))return;const item=this.items.find(entry=>entry.id===widget.dataset.widget);drag={id:event.pointerId,startX:event.clientX,startY:event.clientY,x:item.x,y:item.y};handle.setPointerCapture(event.pointerId)};handle.onpointermove=event=>{if(!drag||event.pointerId!==drag.id||!(event.buttons&1))return stop(event);const x=Math.max(10,Math.min(innerWidth-widget.offsetWidth-10,drag.x+event.clientX-drag.startX)),y=Math.max(52,Math.min(innerHeight-widget.offsetHeight-82,drag.y+event.clientY-drag.startY));widget.style.setProperty('--widget-x',`${x}px`);widget.style.setProperty('--widget-y',`${y}px`)};handle.onpointerup=stop;handle.onpointercancel=stop}
  openGallery(){const overlay=this.desktop.querySelector('[data-overlays]'),widgets=this.context.widgetRegistry.list();overlay.innerHTML=`<section class="widget-gallery"><div class="widget-gallery-backdrop" data-widget-close></div><div class="widget-gallery-panel"><header><div><h2>${this.context.i18n.t('editWidgets')}</h2><p>${this.context.i18n.t('widgetGalleryCopy')}</p></div><button data-widget-close>×</button></header><div>${widgets.map(widget=>`<button data-add-widget="${esc(widget.id)}" ${this.items.some(item=>item.id===widget.id)?'disabled':''}><span>${icon(widget.glyph||'grid',25)}</span><strong>${esc(widget.system?this.context.i18n.t(`widget_${widget.id}`):this.#localized(widget.name))}</strong><small>${esc(widget.system?this.context.i18n.t(`widget_${widget.id}Copy`):this.#localized(widget.description))}</small><b>${this.items.some(item=>item.id===widget.id)?this.context.i18n.t('added'):'+'}</b></button>`).join('')}</div></div></section>`;overlay.querySelectorAll('[data-widget-close]').forEach(button=>button.onclick=()=>overlay.innerHTML='');overlay.querySelectorAll('[data-add-widget]').forEach(button=>button.onclick=()=>{const definition=this.context.widgetRegistry.get(button.dataset.addWidget),offset=this.items.length*24;this.items.push({id:button.dataset.addWidget,size:definition?.defaultSize||'medium',x:22+offset,y:72+offset});this.#save();this.render();this.openGallery()})}
}
