import { icon } from '../icons.js';

const REGIONS = [
  { code:'US', name:'United States', timezone:'America/New_York' },
  { code:'CN', name:'中国大陆', timezone:'Asia/Shanghai' },
  { code:'GB', name:'United Kingdom', timezone:'Europe/London' },
  { code:'JP', name:'日本', timezone:'Asia/Tokyo' },
  { code:'SG', name:'Singapore', timezone:'Asia/Singapore' },
];

export class SetupAssistant {
  constructor(root, context, onComplete) {
    this.root=root;this.context=context;this.onComplete=onComplete;this.step=0;this.password='';
    try{this.draft={language:'en',region:'US',timezone:'America/New_York',keyboardLayout:'us',fullName:'Future User',analytics:false,location:false,theme:'light',reduceMotion:false,...JSON.parse(localStorage.getItem('future.setup.draft')||'{}')}}catch{this.draft={language:'en',region:'US',timezone:'America/New_York',keyboardLayout:'us',fullName:'Future User',analytics:false,location:false,theme:'light',reduceMotion:false}}
  }

  mount(){this.layer=document.createElement('section');this.layer.className='setup-assistant';this.layer.setAttribute('role','dialog');this.layer.setAttribute('aria-modal','true');this.root.appendChild(this.layer);this.render()}
  render(){const {i18n}=this.context,steps=[()=>this.#welcome(),()=>this.#language(),()=>this.#region(),()=>this.#accessibility(),()=>this.#network(),()=>this.#account(),()=>this.#privacy(),()=>this.#appearance(),()=>this.#ready()];this.layer.innerHTML=`<div class="setup-chrome"><header><span class="setup-brand">${icon('logo',22)}</span><strong>${i18n.t('system')}</strong><small>${i18n.t('setupAssistant')}</small></header><div class="setup-progress" aria-label="${i18n.t('setupProgress')}">${steps.map((_,index)=>`<i class="${index<=this.step?'active':''}"></i>`).join('')}</div><main>${steps[this.step]()}</main><footer>${this.step>0&&this.step<steps.length-1?`<button data-setup-back>${i18n.t('back')}</button>`:'<span></span>'}<button class="setup-primary" data-setup-next>${i18n.t(this.step===steps.length-1?'startUsingFuture':this.step===0?'getStarted':'continue')}</button></footer></div>`;this.#bind()}
  #panel(iconName,title,copy,body){return `<div class="setup-panel"><span class="setup-hero-icon">${icon(iconName,36)}</span><h1>${title}</h1><p>${copy}</p>${body}</div>`}
  #welcome(){const {i18n}=this.context;return this.#panel('logo',i18n.t('welcomeToFuture'),i18n.t('welcomeSetupCopy'),`<div class="setup-feature-row"><span>${icon('vm',19)}<b>${i18n.t('realLinux')}</b></span><span>${icon('lock',19)}<b>${i18n.t('privateByDefault')}</b></span><span>${icon('globe',19)}<b>${i18n.t('yourLanguage')}</b></span></div>`)}
  #language(){const {i18n}=this.context;return this.#panel('globe',i18n.t('chooseLanguage'),i18n.t('chooseLanguageCopy'),`<div class="setup-choice-list">${i18n.list().map(lang=>`<button data-setup-language="${lang.code}" class="${this.draft.language===lang.code?'selected':''}"><span>${lang.code.toUpperCase()}</span><strong>${lang.name}</strong>${this.draft.language===lang.code?icon('check',18):''}</button>`).join('')}</div>`)}
  #region(){const {i18n}=this.context,layouts=[['us','U.S.'],['uk','British'],['cn','中文拼音'],['jp','日本語']];return this.#panel('globe',i18n.t('chooseRegion'),i18n.t('chooseRegionCopy'),`<div class="setup-choice-list compact">${REGIONS.map(region=>`<button data-setup-region="${region.code}" class="${this.draft.region===region.code?'selected':''}"><strong>${region.name}</strong><small>${region.timezone}</small>${this.draft.region===region.code?icon('check',18):''}</button>`).join('')}</div><div class="setup-field"><span>${i18n.t('keyboardLayout')}</span><div class="setup-inline-options">${layouts.map(([value,label])=>`<button data-setup-keyboard="${value}" class="${this.draft.keyboardLayout===value?'selected':''}">${label}</button>`).join('')}</div></div>`)}
  #accessibility(){const {i18n}=this.context;return this.#panel('accessibility',i18n.t('accessibility'),i18n.t('accessibilityCopy'),`<div class="setup-toggle-list"><label><span>${icon('eye',20)}<b>${i18n.t('reduceMotion')}</b><small>${i18n.t('reduceMotionCopy')}</small></span><input type="checkbox" data-setup-motion ${this.draft.reduceMotion?'checked':''}></label><label><span>${icon('keyboard',20)}<b>${i18n.t('keyboardNavigation')}</b><small>${i18n.t('keyboardNavigationCopy')}</small></span><input type="checkbox" data-setup-keyboard-nav checked></label></div>`)}
  #network(){const {i18n,system}=this.context,state=system.networkState,online=state.status==='connected';return this.#panel('wifi',i18n.t('network'),i18n.t('networkCopy'),`<div class="setup-network-card ${online?'online':state.status==='connecting'?'connecting':'offline'}"><span>${icon('wifi',27)}</span><div><strong>${i18n.t(online?'guestNetworkConnected':state.status==='connecting'?'connecting':'guestNetworkUnavailable')}</strong><small>${online?state.address:i18n.t('networkCanConfigureLater')}</small></div><i></i></div><small class="setup-disclosure">${i18n.t('guestNetworkDisclosure')}</small>`)}
  #account(){const {i18n}=this.context;return this.#panel('user',i18n.t('createAccount'),i18n.t('createAccountCopy'),`<div class="setup-account-form" data-form-type="other"><label class="setup-field"><span>${i18n.t('fullName')}</span><input data-setup-name value="${this.#escape(this.draft.fullName)}" autocomplete="off" autocorrect="off" spellcheck="false" data-lpignore="true" data-1p-ignore></label><label class="setup-field"><span>${i18n.t('accountName')}</span><input value="future" disabled autocomplete="off"></label><div class="setup-field"><span>${i18n.t('password')}</span><div class="setup-secure-input"><input data-setup-password class="secure-masked" type="text" inputmode="text" value="${this.#escape(this.password)}" autocomplete="off" autocapitalize="off" autocorrect="off" spellcheck="false" data-lpignore="true" data-1p-ignore data-protonpass-ignore="true" data-bwignore="true" placeholder="${i18n.t('optional')}" aria-label="${i18n.t('password')}"><button data-setup-password-toggle aria-label="${i18n.t('showPassword')}" aria-pressed="false">${icon('eye',17)}</button></div></div></div>`)}
  #privacy(){const {i18n}=this.context;return this.#panel('privacy',i18n.t('privacySecurity'),i18n.t('privacyCopy'),`<div class="setup-toggle-list"><label><span>${icon('location',20)}<b>${i18n.t('locationServices')}</b><small>${i18n.t('locationCopy')}</small></span><input type="checkbox" data-setup-location ${this.draft.location?'checked':''}></label><label><span>${icon('chart',20)}<b>${i18n.t('shareAnalytics')}</b><small>${i18n.t('analyticsCopy')}</small></span><input type="checkbox" data-setup-analytics ${this.draft.analytics?'checked':''}></label></div><small class="setup-disclosure">${i18n.t('privacyDefaultCopy')}</small>`)}
  #appearance(){const {i18n}=this.context;return this.#panel('sun',i18n.t('chooseAppearance'),i18n.t('appearanceCopy'),`<div class="setup-appearance-options">${['light','dark'].map(theme=>`<button data-setup-theme="${theme}" class="${this.draft.theme===theme?'selected':''}"><i class="theme-preview ${theme}"></i><strong>${i18n.t(theme)}</strong>${this.draft.theme===theme?icon('check',18):''}</button>`).join('')}</div>`)}
  #ready(){const {i18n}=this.context;return this.#panel('check',i18n.t('readyTitle'),i18n.t('readyCopy'),`<div class="setup-summary"><span>${icon('user',18)}<b>${this.#escape(this.draft.fullName)}</b><small>future</small></span><span>${icon('globe',18)}<b>${REGIONS.find(x=>x.code===this.draft.region)?.name||this.draft.region}</b><small>${this.draft.timezone}</small></span><span>${icon(this.draft.theme==='dark'?'moon':'sun',18)}<b>${i18n.t(this.draft.theme)}</b><small>${i18n.t('appearance')}</small></span></div>`)}
  #bind(){this.layer.querySelector('[data-setup-back]')?.addEventListener('click',()=>{this.#capture();this.step--;this.render()});this.layer.querySelector('[data-setup-next]').onclick=()=>this.#next();this.layer.querySelectorAll('[data-setup-language]').forEach(button=>button.onclick=()=>{this.draft.language=button.dataset.setupLanguage;this.context.i18n.use(this.draft.language);document.documentElement.lang=this.draft.language;this.#save();this.render()});this.layer.querySelectorAll('[data-setup-region]').forEach(button=>button.onclick=()=>{const region=REGIONS.find(x=>x.code===button.dataset.setupRegion);this.draft.region=region.code;this.draft.timezone=region.timezone;this.#save();this.render()});this.layer.querySelectorAll('[data-setup-keyboard]').forEach(button=>button.onclick=()=>{this.draft.keyboardLayout=button.dataset.setupKeyboard;this.#save();this.render()});this.layer.querySelectorAll('[data-setup-theme]').forEach(button=>button.onclick=()=>{this.draft.theme=button.dataset.setupTheme;if(this.context.themeRuntime)this.context.themeRuntime.apply(this.draft.theme,{persist:false});else document.documentElement.dataset.theme=this.draft.theme;this.#save();this.render()});const reveal=this.layer.querySelector('[data-setup-password-toggle]');if(reveal)reveal.onclick=()=>{const input=this.layer.querySelector('[data-setup-password]'),visible=input.classList.toggle('secure-visible');reveal.setAttribute('aria-pressed',String(visible));reveal.setAttribute('aria-label',this.context.i18n.t(visible?'hidePassword':'showPassword'))}}
  #capture(){const q=selector=>this.layer.querySelector(selector);if(q('[data-setup-motion]'))this.draft.reduceMotion=q('[data-setup-motion]').checked;if(q('[data-setup-name]'))this.draft.fullName=q('[data-setup-name]').value.trim()||'Future User';if(q('[data-setup-password]'))this.password=q('[data-setup-password]').value;if(q('[data-setup-location]'))this.draft.location=q('[data-setup-location]').checked;if(q('[data-setup-analytics]'))this.draft.analytics=q('[data-setup-analytics]').checked;this.#save()}
  async #next(){this.#capture();if(this.step<8){this.step++;this.render();return}const button=this.layer.querySelector('[data-setup-next]');button.disabled=true;button.textContent=this.context.i18n.t('finishingSetup');try{await this.context.system.configureProfile({...this.draft,password:this.password});this.context.settings.update({...this.draft,locale:this.draft.language,setupComplete:true});document.documentElement.dataset.reduceMotion=this.draft.reduceMotion?'true':'false';localStorage.removeItem('future.setup.draft');await this.context.machine.checkpoint();this.layer.remove();await this.onComplete()}catch(error){button.disabled=false;button.textContent=this.context.i18n.t('tryAgain');this.layer.querySelector('.setup-panel>p').textContent=error.message}}
  #save(){const safe={...this.draft};localStorage.setItem('future.setup.draft',JSON.stringify(safe))}
  #escape(value){return String(value||'').replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}
}
