import { icon } from '../../icons.js';
const esc=value=>String(value).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
const quote=value=>`'${String(value).replace(/'/g,`'"'"'`)}'`;
const mimeFor=path=>({png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg',gif:'image/gif',webp:'image/webp',svg:'image/svg+xml',pdf:'application/pdf'})[path.split('.').at(-1).toLowerCase()];
export default{
  id:'preview',title:'preview',icon:'preview',color:'blue',width:920,height:640,singleInstance:true,
  mount(root,{system,kernel,dialog,i18n,launchOptions,agentContext}){
    let currentPath='',mime='',zoom=1,rotation=0;
    root.innerHTML=`<div class="system-app preview-pro"><div class="app-commandbar"><button data-preview-open>${icon('folder',15)} ${i18n.t('open')}</button><div class="toolbar-cluster"><button data-preview-zoom="out">−</button><button data-preview-fit>${i18n.t('fit')}</button><button data-preview-zoom="in">+</button></div><button data-preview-rotate>${icon('refresh',14)} ${i18n.t('rotate')}</button><strong data-preview-title>${i18n.t('preview')}</strong><div class="toolbar-spacer"></div><button data-preview-info class="selected">${icon('info',15)}</button></div><div class="preview-workspace"><main data-preview-content><div class="empty-state">${icon('preview',38)}<span>${i18n.t('selectFileToPreview')}</span></div></main><aside data-preview-inspector><header>${icon('preview',30)}<strong>${i18n.t('noFileSelected')}</strong></header><dl><dt>${i18n.t('kind')}</dt><dd>—</dd><dt>${i18n.t('where')}</dt><dd>—</dd></dl></aside></div><footer class="app-statusbar"><span data-preview-meta></span><span data-preview-zoom-label>100%</span></footer></div>`;
    const content=root.querySelector('[data-preview-content]'),title=root.querySelector('[data-preview-title]'),meta=root.querySelector('[data-preview-meta]'),inspector=root.querySelector('[data-preview-inspector]');
    const transform=()=>{const media=content.querySelector('img, pre');if(media)media.style.transform=`scale(${zoom}) rotate(${rotation}deg)`;root.querySelector('[data-preview-zoom-label]').textContent=`${Math.round(zoom*100)}%`;if(currentPath)agentContext.set({appId:'preview',label:i18n.t('preview'),resource:{kind:'file-preview',entityType:'filesystem.file',id:currentPath,uri:`future://files${currentPath}`,name:currentPath.split('/').at(-1),path:currentPath,metadata:{mime,zoom,rotation}}})};
    const open=async path=>{if(!system.ready){content.innerHTML=`<div class="empty-state">${esc(i18n.t('startMachine'))}</div>`;return}currentPath=path;zoom=1;rotation=0;title.textContent=path.split('/').at(-1);content.innerHTML=`<div class="app-loading"><i></i>${i18n.t('opening')}</div>`;mime=mimeFor(path)||'text/plain';try{if(mime!=='text/plain'){const {output}=await system.execChecked(`base64 < ${quote(path)} | tr -d '\\n'`,60000);content.innerHTML=mime==='application/pdf'?`<iframe title="${i18n.t('preview')}" src="data:${mime};base64,${output}"></iframe>`:`<img alt="" src="data:${mime};base64,${output}">`}else content.innerHTML=`<pre>${esc(await system.read(path))}</pre>`;meta.textContent=mime;inspector.innerHTML=`<header>${icon(mime.startsWith('image/')?'pictures':'preview',30)}<strong>${esc(path.split('/').at(-1))}</strong></header><dl><dt>${i18n.t('kind')}</dt><dd>${mime}</dd><dt>${i18n.t('where')}</dt><dd>${esc(path.slice(0,path.lastIndexOf('/'))||'/')}</dd></dl>`;transform()}catch(error){content.innerHTML=`<div class="empty-state">${esc(error.message)}</div>`}};
    root.querySelector('[data-preview-open]').onclick=async()=>{const path=await dialog.prompt({title:i18n.t('open'),value:launchOptions.path||'/home/future/Documents/',placeholder:'/home/future/Documents/file.txt',validate:value=>value.startsWith('/')?'':i18n.t('invalidPath')});if(path)open(path)};root.querySelectorAll('[data-preview-zoom]').forEach(button=>button.onclick=()=>{zoom=Math.min(3,Math.max(.25,zoom+(button.dataset.previewZoom==='in'?.1:-.1)));transform()});root.querySelector('[data-preview-fit]').onclick=()=>{zoom=1;rotation=0;transform()};root.querySelector('[data-preview-rotate]').onclick=()=>{if(!currentPath||mime==='application/pdf')return;rotation=(rotation+90)%360;transform()};root.querySelector('[data-preview-info]').onclick=event=>{inspector.hidden=!inspector.hidden;event.currentTarget.classList.toggle('selected',!inspector.hidden)};const off=kernel.bus.on('preview:open',open),offReady=kernel.bus.on('guest:ready',()=>{if(launchOptions.path)open(launchOptions.path)});if(system.ready&&launchOptions.path)open(launchOptions.path);return()=>{off();offReady()}
  }
};
