import { icon } from '../../icons.js';
const esc=value=>String(value).replace(/&/g,'&amp;').replace(/</g,'&lt;');
export default{
  id:'diskutility',title:'diskUtility',icon:'disk',color:'grey',width:860,height:570,singleInstance:true,
  mount(root,{system,kernel,i18n}){
    const shell=()=>{root.innerHTML=`<div class="system-app disk-pro"><aside><header><strong>${i18n.t('diskUtility')}</strong></header><small>${i18n.t('internal')}</small><button class="selected">${icon('disk',18)}<span><strong>${i18n.t("linuxSystemName")}</strong><small>${i18n.t('computerStorage')}</small></span></button><small>${i18n.t('diskImages')}</small><p>${i18n.t('noDiskImages')}</p></aside><section><div class="app-commandbar"><button data-disk-refresh>${icon('refresh',15)} ${i18n.t('refresh')}</button><div class="toolbar-spacer"></div><span class="kernel-badge">${system.ready?i18n.t('online'):i18n.t('offline')}</span></div><div data-disk-content class="app-loading"><i></i>${i18n.t('readingStorage')}</div></section></div>`;root.querySelector('[data-disk-refresh]').onclick=render};
    const render=async()=>{shell();const node=root.querySelector('[data-disk-content]');if(!system.ready){node.className='empty-state';node.textContent=i18n.t('startMachine');return}try{const [{output:df},{output:mounts}]=await Promise.all([system.exec("df -hP | tail -n +2"),system.exec("mount | head -20")]);const rows=df.trim().split('\n').map(line=>line.trim().split(/\s+/)).filter(row=>row.length>=6),primary=rows.find(row=>row[5]==='/')||rows[0],percent=parseInt(primary?.[4])||0;node.className='disk-dashboard';node.innerHTML=`<header><span>${icon('disk',42)}</span><div><h2>${i18n.t("linuxSystemName")}</h2><p>${primary?.[0]||'Alpine Linux'} · ${i18n.t('mounted')}</p></div></header><section class="capacity-card"><div><strong>${i18n.t('used')}</strong><b>${primary?.[2]||'—'}</b><strong>${i18n.t('available')}</strong><b>${primary?.[3]||'—'}</b><strong>${i18n.t('capacity')}</strong><b>${primary?.[1]||'—'}</b></div><i><span style="width:${percent}%"></span></i><small>${percent}% ${i18n.t('used').toLowerCase()}</small></section><h3>${i18n.t('filesystems')}</h3><div class="volume-table"><header><span>${i18n.t('name')}</span><span>${i18n.t('size')}</span><span>${i18n.t('used')}</span><span>${i18n.t('mountPoints')}</span></header>${rows.map(row=>`<div><strong>${esc(row[0])}</strong><span>${esc(row[1])}</span><span>${esc(row[4])}</span><code>${esc(row[5])}</code></div>`).join('')}</div><details><summary>${i18n.t('mountDetails')}</summary><pre>${esc(mounts)}</pre></details>`}catch(error){node.className='empty-state';node.textContent=error.message}};
    render();const off=kernel.bus.on('guest:ready',render);return off
  }
};
