import {icon} from '../../icons.js';

const esc=value=>String(value??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
export const TERMINAL_TASK_STATES=new Set(['completed','failed','cancelled']);
export const HISTORY_TASK_STATES=new Set(['completed','failed']);
const statusIcon=(task)=>task.status==='completed'?'check':task.status==='failed'?'warning':task.status==='approval'?'lock':task.status==='input'?'message':task.origin==='automation'?'timer':'futureAi';
const formatTime=(value,i18n)=>value?new Intl.DateTimeFormat(i18n.t('dateFormat'),{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(value)):'—';
const receiptTask=(record,task)=>record.taskId===task.id||(!record.taskId&&record.turnId&&record.turnId===task.turnId);
const receiptStep=(record,task)=>(task.operations||[]).some(step=>record.toolCallId===step.id||(!record.toolCallId&&record.appId===step.appId&&record.operation===step.operation));
const triggerLabel=(rule,i18n)=>{const trigger=rule.trigger||{};if(trigger.type==='daily')return`${i18n.t('automationDaily')} · ${trigger.time||'09:00'}`;if(trigger.type==='interval')return`${i18n.t('automationEvery')} ${trigger.intervalMinutes||60} ${i18n.t('minutes')}`;if(trigger.type==='app_opened')return`${i18n.t('automationAppOpened')} · ${trigger.appId||i18n.t('anyApp')}`;if(trigger.type==='file_changed')return`${i18n.t('automationFileChanged')} · ${trigger.path||'/home/future'}`;if(trigger.type==='network_online')return i18n.t('automationNetworkOnline');if(trigger.type==='memory_above')return`${i18n.t('automationMemoryAbove')} ${trigger.threshold||80}%`;return trigger.type};

export function automationNextRunAt(rule,nowValue=Date.now()){
  if(!rule?.enabled)return 0;
  const trigger=rule.trigger||{},now=new Date(nowValue);
  if(trigger.type==='daily'){
    const [hour,minute]=String(trigger.time||'09:00').split(':').map(Number),due=new Date(now);due.setHours(hour||0,minute||0,0,0);
    if(due.getTime()<=nowValue||Number(rule.createdAt)>due.getTime()||Number(rule.lastRunAt)>=due.getTime())due.setDate(due.getDate()+1);
    return due.getTime();
  }
  if(trigger.type==='interval')return Math.max(nowValue,(Number(rule.lastRunAt)||Number(rule.createdAt)||nowValue)+Math.max(1,Number(trigger.intervalMinutes)||60)*60_000);
  return 0;
}

export function taskExecutionHistory(tasks=[],records=[]){
  const finished=tasks.filter(task=>HISTORY_TASK_STATES.has(task.status)).sort((a,b)=>(b.finishedAt||b.updatedAt)-(a.finishedAt||a.updatedAt));
  const undoable=records.filter(record=>record.undoable&&record.status==='completed'&&finished.some(task=>receiptTask(record,task)&&receiptStep(record,task))).length;
  return{finished,undoable};
}

export function taskWorkspaceSignature(systemTasks,operationHistory,{automations=null,view='active'}={}){
  const tasks=systemTasks.snapshot().tasks.map(item=>`${item.id}:${item.updatedAt}:${item.status}:${item.progress}`).join('|');
  const history=operationHistory.snapshot().records.map(item=>`${item.id}:${item.updatedAt}:${item.status}`).join('|');
  const scheduled=automations?.list?.().map(item=>`${item.id}:${item.updatedAt}:${item.enabled}:${item.lastRunAt}`).join('|')||'';
  return`${view}:${tasks}:${history}:${scheduled}`;
}

export function taskWorkspaceMarkup({systemTasks,operationHistory,automations=null,registry,i18n,view='active'}={}){
  const state=systemTasks.snapshot(),history=operationHistory.snapshot(),all=state.tasks,executionHistory=taskExecutionHistory(all,history.records),scheduled=automations?.list?.().filter(rule=>rule.enabled)||[],visible=all.filter(item=>!item.dismissed),waiting=visible.filter(item=>['approval','input'].includes(item.status)),active=visible.filter(item=>!TERMINAL_TASK_STATES.has(item.status)&&!['approval','input'].includes(item.status)),tasks=view==='waiting'?waiting:active;
  const upcomingRows=scheduled.map(rule=>{const nextRunAt=automationNextRunAt(rule),schedule=nextRunAt?`${i18n.t('nextRun')} · ${formatTime(nextRunAt,i18n)}`:`${i18n.t('waitingForTrigger')} · ${triggerLabel(rule,i18n)}`,lastRun=rule.lastRunAt?`${formatTime(rule.lastRunAt,i18n)} · ${i18n.t(`taskStatus_${rule.lastStatus}`)}`:i18n.t('never');return`<article class="ai-upcoming-automation" data-ai-upcoming-automation="${esc(rule.id)}"><span>${icon('timer',14)}</span><div><header><strong>${esc(rule.name)}</strong><em>${esc(i18n.t('scheduled'))}</em></header><p title="${esc(rule.action?.prompt||'')}">${esc(rule.action?.prompt||'')}</p><small>${esc(schedule)}</small></div><button data-ai-upcoming-expand aria-expanded="false" title="${esc(i18n.t('showDetails'))}">${icon('chevron',10)}</button><section hidden><dl><div><dt>${esc(i18n.t('trigger'))}</dt><dd>${esc(triggerLabel(rule,i18n))}</dd></div><div><dt>${esc(i18n.t('nextRun'))}</dt><dd>${esc(nextRunAt?formatTime(nextRunAt,i18n):i18n.t('waitingForTrigger'))}</dd></div><div><dt>${esc(i18n.t('lastRun'))}</dt><dd>${esc(lastRun)}</dd></div><div class="instruction"><dt>${esc(i18n.t('agentInstruction'))}</dt><dd data-copyable>${esc(rule.action?.prompt||'')}</dd></div></dl><footer><button data-ai-automation-delete="${esc(rule.id)}">${icon('delete',10)} ${esc(i18n.t('deleteAutomation'))}</button></footer></section></article>`}).join('');
  const taskRows=tasks.length?tasks.map(task=>{const content=task.error||task.taskContent||task.activeTool?.label||i18n.t('agentTask');return`<article class="ai-system-task status-${esc(task.status)}"><span>${icon(statusIcon(task),15)}</span><button data-ai-system-task-open="${esc(task.id)}"><header><strong>${esc(task.title)}</strong><em>${esc(i18n.t(`taskStatus_${task.status}`))}</em></header><p title="${esc(content)}">${esc(content)}</p><footer><small>${esc(i18n.t(task.origin==='automation'?'automation':'agentTask'))}</small><time>${esc(formatTime(task.updatedAt,i18n))}</time></footer><i><b style="width:${Math.max(6,Math.min(100,task.progress||0))}%"></b></i></button><nav><button data-ai-system-task-cancel="${esc(task.id)}" title="${esc(i18n.t('cancelTask'))}">${icon('stopSquare',11)}</button></nav></article>`}).join(''):`<div class="ai-system-empty">${icon('history',25)}<strong>${esc(i18n.t(view==='waiting'?'noWaitingTasks':'noActiveTasks'))}</strong><p>${esc(i18n.t('noSystemTasksCopy'))}</p></div>`;
  const finished=executionHistory.finished.filter(task=>history.records.some(record=>record.undoable&&record.status==='completed'&&receiptTask(record,task)&&receiptStep(record,task)));
  const historyRows=finished.length?finished.map(task=>{
    const receipts=history.records.filter(record=>record.taskId===task.id||(!record.taskId&&record.turnId&&record.turnId===task.turnId));
    const steps=(task.operations||[]).map(step=>{const receipt=receipts.find(record=>record.toolCallId===step.id)||receipts.find(record=>record.appId===step.appId&&record.operation===step.operation),app=registry.get(step.appId),phase=receipt?.status||step.phase||'completed',statusKey=receipt?`operationStatus_${phase}`:`toolStatus_${phase}`,detail=receipt?.error||step.error||step.parameters||step.operation||'';return`<article class="ai-task-history-step status-${esc(phase)}"><span class="app-icon app-icon-${esc(app?.color||'grey')}">${icon(app?.icon||'wrench',13)}</span><div><header><strong>${esc(step.label||receipt?.label||i18n.t('systemTool'))}</strong><em>${esc(i18n.t(statusKey))}</em></header>${detail?`<p title="${esc(detail)}">${esc(detail)}</p>`:''}</div>${receipt?.undoable&&receipt.status==='completed'?`<button data-ai-operation-undo="${esc(receipt.id)}">${icon('refresh',10)}${esc(i18n.t('undo'))}</button>`:''}</article>`}).join('');
    return`<details class="ai-task-history-record status-${esc(task.status)}"><summary><span>${icon(statusIcon(task),15)}</span><div><header><strong>${esc(task.title)}</strong><em>${esc(i18n.t(`taskStatus_${task.status}`))}</em></header><p title="${esc(task.error||task.taskContent||'')}">${esc(task.error||task.taskContent||i18n.t('agentTask'))}</p><time>${esc(formatTime(task.finishedAt||task.updatedAt,i18n))}</time></div><i>${icon('chevron',10)}</i></summary><section>${steps||`<p class="ai-task-history-no-steps">${esc(i18n.t('noTaskActions'))}</p>`}</section></details>`;
  }).join(''):`<div class="ai-system-empty">${icon('history',25)}<strong>${esc(i18n.t('noAvailableUndos'))}</strong><p>${esc(i18n.t('noAvailableUndosCopy'))}</p></div>`;
  const upcomingContent=upcomingRows||`<div class="ai-system-empty">${icon('timer',25)}<strong>${esc(i18n.t('noUpcomingAutomations'))}</strong><p>${esc(i18n.t('noUpcomingAutomationsCopy'))}</p></div>`,content=view==='upcoming'?`<div class="ai-upcoming-automations">${upcomingContent}</div>`:view==='undos'?`<div class="ai-operation-list">${historyRows}</div>`:`<div class="ai-system-task-list">${taskRows}</div>`;
  const summaries=[['upcoming',scheduled.length,'upcoming'],['active',active.length,'activeTasks'],['waiting',waiting.length,'waitingForYou'],['undos',executionHistory.undoable,'availableUndos']];
  return`<section class="ai-system-task-workspace"><header><div><strong>${esc(i18n.t('taskCenter'))}</strong><small>${esc(i18n.t('tasksPageCopy'))}</small></div></header><div class="ai-system-task-summary">${summaries.map(([value,count,label])=>`<button class="${view===value?'selected':''}" data-ai-task-summary-view="${value}" aria-pressed="${view===value}"><b>${count}</b><span>${esc(i18n.t(label))}</span></button>`).join('')}</div>${content}</section>`;
}

export function automationSettingsMarkup({automations,registry,i18n,formOpen=false,triggerType='daily'}={}){
  const rules=automations.list(),field=(type,markup)=>`<label data-ai-automation-field="${type}" ${triggerType===type?'':'hidden'}>${markup}</label>`;
  const form=formOpen?`<section class="ai-automation-editor"><header><div><strong>${esc(i18n.t('newAutomation'))}</strong><small>${esc(i18n.t('newAutomationCopy'))}</small></div><button data-ai-cancel-automation>${icon('close',11)}</button></header><div><label><span>${esc(i18n.t('automationName'))}</span><input data-ai-automation-name placeholder="${esc(i18n.t('automationNamePlaceholder'))}"></label><label><span>${esc(i18n.t('trigger'))}</span><select data-ai-automation-trigger>${[['daily','automationDaily'],['interval','automationInterval'],['app_opened','automationAppOpened'],['file_changed','automationFileChanged'],['network_online','automationNetworkOnline'],['memory_above','automationMemoryAbove']].map(([value,key])=>`<option value="${value}" ${triggerType===value?'selected':''}>${esc(i18n.t(key))}</option>`).join('')}</select></label>${field('daily',`<span>${esc(i18n.t('time'))}</span><input data-ai-automation-time type="time" value="09:00">`)}${field('interval',`<span>${esc(i18n.t('intervalMinutes'))}</span><input data-ai-automation-interval type="number" min="1" value="60">`)}${field('app_opened',`<span>${esc(i18n.t('application'))}</span><select data-ai-automation-app><option value="">${esc(i18n.t('anyApp'))}</option>${registry.list().filter(app=>app.id!=='ai').map(app=>`<option value="${esc(app.id)}">${esc(i18n.t(app.title))}</option>`).join('')}</select>`)}${field('file_changed',`<span>${esc(i18n.t('watchedPath'))}</span><input data-ai-automation-path value="/home/future/Desktop">`)}${field('memory_above',`<span>${esc(i18n.t('memoryThreshold'))}</span><input data-ai-automation-threshold type="number" min="1" max="100" value="80">`)}<label><span>${esc(i18n.t('agentInstruction'))}</span><textarea data-ai-automation-prompt rows="4" placeholder="${esc(i18n.t('agentInstructionPlaceholder'))}"></textarea><small>${esc(i18n.t('automationAgentCopy'))}</small></label></div><footer><button data-ai-cancel-automation>${esc(i18n.t('cancel'))}</button><button class="ai-primary" data-ai-save-automation>${esc(i18n.t('createAutomation'))}</button></footer></section>`:'';
  const rows=rules.length?rules.map(rule=>`<article class="ai-automation-row ${rule.enabled?'enabled':'disabled'}"><span>${icon(rule.trigger.type==='daily'||rule.trigger.type==='interval'?'clock':rule.trigger.type==='file_changed'?'folder':rule.trigger.type==='memory_above'?'memory':rule.trigger.type==='network_online'?'wifi':'grid',16)}</span><div><header><strong>${esc(rule.name)}</strong><small>${esc(triggerLabel(rule,i18n))}</small></header><p title="${esc(rule.lastError||'')}">${esc(rule.lastStatus==='failed'&&rule.lastError?rule.lastError:rule.action.prompt)}</p><time>${esc(i18n.t('lastRun'))}: ${rule.lastRunAt?`${esc(formatTime(rule.lastRunAt,i18n))} · ${esc(i18n.t(`taskStatus_${rule.lastStatus}`))}`:esc(i18n.t('never'))}</time></div><nav><label title="${esc(i18n.t(rule.enabled?'enabled':'disabled'))}"><input type="checkbox" data-ai-automation-toggle="${esc(rule.id)}" ${rule.enabled?'checked':''}><i></i></label><button data-ai-automation-run="${esc(rule.id)}" title="${esc(i18n.t('runNow'))}">${icon('play',11)}</button><button data-ai-automation-delete="${esc(rule.id)}" title="${esc(i18n.t('delete'))}">${icon('delete',11)}</button></nav></article>`).join(''):`<div class="ai-automation-empty">${icon('timer',27)}<strong>${esc(i18n.t('noAutomations'))}</strong><p>${esc(i18n.t('noAutomationsCopy'))}</p></div>`;
  return`<div class="ai-automation-settings"><header><div><h3>${esc(i18n.t('automations'))}</h3><p>${esc(i18n.t('automationsPageCopy'))}</p></div>${formOpen?'':`<button data-ai-new-automation>${icon('plus',11)}${esc(i18n.t('newAutomation'))}</button>`}</header>${form}<div class="ai-automation-list">${rows}</div></div>`;
}
