import {icon} from '../../icons.js';

const esc=value=>String(value??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
export const TERMINAL_TASK_STATES=new Set(['completed','failed','cancelled']);
const statusIcon=(task)=>task.status==='completed'?'check':task.status==='failed'?'warning':task.status==='approval'?'lock':task.status==='input'?'message':task.origin==='automation'?'timer':'futureAi';
const formatTime=(value,i18n)=>value?new Intl.DateTimeFormat(i18n.t('dateFormat'),{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(value)):'—';

export function taskWorkspaceSignature(systemTasks,operationHistory,{tab='tasks',filter='all'}={}){
  const tasks=systemTasks.snapshot().tasks.map(item=>`${item.id}:${item.updatedAt}:${item.status}:${item.progress}`).join('|');
  const history=operationHistory.snapshot().records.map(item=>`${item.id}:${item.updatedAt}:${item.status}`).join('|');
  return`${tab}:${filter}:${tasks}:${history}`;
}

export function taskWorkspaceMarkup({systemTasks,operationHistory,registry,i18n,tab='tasks',filter='all'}={}){
  const state=systemTasks.snapshot(),history=operationHistory.snapshot(),all=state.tasks,tasks=filter==='active'?all.filter(item=>!TERMINAL_TASK_STATES.has(item.status)):filter==='completed'?all.filter(item=>TERMINAL_TASK_STATES.has(item.status)):all;
  const taskRows=tasks.length?tasks.map(task=>{const active=!TERMINAL_TASK_STATES.has(task.status);return`<article class="ai-system-task status-${esc(task.status)}"><span>${icon(statusIcon(task),15)}</span><button data-ai-system-task-open="${esc(task.id)}"><header><strong>${esc(task.title)}</strong><em>${esc(i18n.t(`taskStatus_${task.status}`))}</em></header><p title="${esc(task.error||'')}">${esc(task.error||task.activeTool?.label||task.prompt||i18n.t('agentTask'))}</p><footer><small>${esc(i18n.t(task.origin==='automation'?'automation':'conversation'))}</small><time>${esc(formatTime(task.updatedAt,i18n))}</time></footer>${active?`<i><b style="width:${Math.max(6,Math.min(100,task.progress||0))}%"></b></i>`:''}</button><nav>${active?`<button data-ai-system-task-cancel="${esc(task.id)}" title="${esc(i18n.t('cancelTask'))}">${icon('stopSquare',11)}</button>`:task.prompt?`<button data-ai-system-task-retry="${esc(task.id)}" title="${esc(i18n.t('retryTask'))}">${icon('refresh',11)}</button>`:''}${active?'':`<button data-ai-system-task-remove="${esc(task.id)}" title="${esc(i18n.t('dismiss'))}">${icon('close',10)}</button>`}</nav></article>`}).join(''):`<div class="ai-system-empty">${icon('history',25)}<strong>${esc(i18n.t('noSystemTasks'))}</strong><p>${esc(i18n.t('noSystemTasksCopy'))}</p></div>`;
  const historyRows=history.records.length?history.records.map(record=>{const app=registry.get(record.appId),detail=record.error||`${record.agentName||i18n.t(record.source==='automation'?'automation':'futureAI')} · ${record.operation}`;return`<article class="ai-operation-receipt status-${esc(record.status)}"><span class="app-icon app-icon-${esc(app?.color||'grey')}">${icon(app?.icon||'wrench',14)}</span><div><header><strong>${esc(record.label)}</strong><em>${esc(i18n.t(`operationStatus_${record.status}`))}</em></header><p title="${esc(record.error||'')}">${esc(detail)}</p><time>${esc(formatTime(record.updatedAt,i18n))}</time></div>${record.undoable&&record.status==='completed'?`<button data-ai-operation-undo="${esc(record.id)}">${icon('refresh',10)}${esc(i18n.t('undo'))}</button>`:''}</article>`}).join(''):`<div class="ai-system-empty">${icon('history',25)}<strong>${esc(i18n.t('noOperations'))}</strong><p>${esc(i18n.t('noOperationsCopy'))}</p></div>`;
  return`<section class="ai-system-task-workspace"><header><div><strong>${esc(i18n.t('taskCenter'))}</strong><small>${esc(i18n.t('tasksPageCopy'))}</small></div></header><div class="ai-system-task-summary"><span><b>${state.running}</b>${esc(i18n.t('activeTasks'))}</span><span><b>${state.waiting}</b>${esc(i18n.t('waitingForYou'))}</span><span><b>${history.undoable}</b>${esc(i18n.t('availableUndos'))}</span></div><nav class="ai-system-task-tabs"><button class="${tab==='tasks'?'selected':''}" data-ai-task-workspace-tab="tasks">${esc(i18n.t('tasks'))}</button><button class="${tab==='history'?'selected':''}" data-ai-task-workspace-tab="history">${esc(i18n.t('operationHistory'))}</button></nav>${tab==='tasks'?`<div class="ai-system-task-filters">${['all','active','completed'].map(value=>`<button class="${filter===value?'selected':''}" data-ai-task-filter="${value}">${esc(i18n.t(value))}</button>`).join('')}</div><div class="ai-system-task-list">${taskRows}</div>`:`<div class="ai-operation-list">${historyRows}</div>`}</section>`;
}

const triggerLabel=(rule,i18n)=>{const trigger=rule.trigger||{};if(trigger.type==='daily')return`${i18n.t('automationDaily')} · ${trigger.time||'09:00'}`;if(trigger.type==='interval')return`${i18n.t('automationEvery')} ${trigger.intervalMinutes||60} ${i18n.t('minutes')}`;if(trigger.type==='app_opened')return`${i18n.t('automationAppOpened')} · ${trigger.appId||i18n.t('anyApp')}`;if(trigger.type==='file_changed')return`${i18n.t('automationFileChanged')} · ${trigger.path||'/home/future'}`;if(trigger.type==='network_online')return i18n.t('automationNetworkOnline');if(trigger.type==='memory_above')return`${i18n.t('automationMemoryAbove')} ${trigger.threshold||80}%`;return trigger.type};

export function automationSettingsMarkup({automations,registry,i18n,formOpen=false,triggerType='daily'}={}){
  const rules=automations.list(),field=(type,markup)=>`<label data-ai-automation-field="${type}" ${triggerType===type?'':'hidden'}>${markup}</label>`;
  const form=formOpen?`<section class="ai-automation-editor"><header><div><strong>${esc(i18n.t('newAutomation'))}</strong><small>${esc(i18n.t('newAutomationCopy'))}</small></div><button data-ai-cancel-automation>${icon('close',11)}</button></header><div><label><span>${esc(i18n.t('automationName'))}</span><input data-ai-automation-name placeholder="${esc(i18n.t('automationNamePlaceholder'))}"></label><label><span>${esc(i18n.t('trigger'))}</span><select data-ai-automation-trigger>${[['daily','automationDaily'],['interval','automationInterval'],['app_opened','automationAppOpened'],['file_changed','automationFileChanged'],['network_online','automationNetworkOnline'],['memory_above','automationMemoryAbove']].map(([value,key])=>`<option value="${value}" ${triggerType===value?'selected':''}>${esc(i18n.t(key))}</option>`).join('')}</select></label>${field('daily',`<span>${esc(i18n.t('time'))}</span><input data-ai-automation-time type="time" value="09:00">`)}${field('interval',`<span>${esc(i18n.t('intervalMinutes'))}</span><input data-ai-automation-interval type="number" min="1" value="60">`)}${field('app_opened',`<span>${esc(i18n.t('application'))}</span><select data-ai-automation-app><option value="">${esc(i18n.t('anyApp'))}</option>${registry.list().filter(app=>app.id!=='ai').map(app=>`<option value="${esc(app.id)}">${esc(i18n.t(app.title))}</option>`).join('')}</select>`)}${field('file_changed',`<span>${esc(i18n.t('watchedPath'))}</span><input data-ai-automation-path value="/home/future/Desktop">`)}${field('memory_above',`<span>${esc(i18n.t('memoryThreshold'))}</span><input data-ai-automation-threshold type="number" min="1" max="100" value="80">`)}<label><span>${esc(i18n.t('agentInstruction'))}</span><textarea data-ai-automation-prompt rows="4" placeholder="${esc(i18n.t('agentInstructionPlaceholder'))}"></textarea><small>${esc(i18n.t('automationAgentCopy'))}</small></label></div><footer><button data-ai-cancel-automation>${esc(i18n.t('cancel'))}</button><button class="ai-primary" data-ai-save-automation>${esc(i18n.t('createAutomation'))}</button></footer></section>`:'';
  const rows=rules.length?rules.map(rule=>`<article class="ai-automation-row ${rule.enabled?'enabled':'disabled'}"><span>${icon(rule.trigger.type==='daily'||rule.trigger.type==='interval'?'clock':rule.trigger.type==='file_changed'?'folder':rule.trigger.type==='memory_above'?'memory':rule.trigger.type==='network_online'?'wifi':'grid',16)}</span><div><header><strong>${esc(rule.name)}</strong><small>${esc(triggerLabel(rule,i18n))}</small></header><p title="${esc(rule.lastError||'')}">${esc(rule.lastStatus==='failed'&&rule.lastError?rule.lastError:rule.action.prompt)}</p><time>${esc(i18n.t('lastRun'))}: ${rule.lastRunAt?`${esc(formatTime(rule.lastRunAt,i18n))} · ${esc(i18n.t(`taskStatus_${rule.lastStatus}`))}`:esc(i18n.t('never'))}</time></div><nav><label title="${esc(i18n.t(rule.enabled?'enabled':'disabled'))}"><input type="checkbox" data-ai-automation-toggle="${esc(rule.id)}" ${rule.enabled?'checked':''}><i></i></label><button data-ai-automation-run="${esc(rule.id)}" title="${esc(i18n.t('runNow'))}">${icon('play',11)}</button><button data-ai-automation-delete="${esc(rule.id)}" title="${esc(i18n.t('delete'))}">${icon('delete',11)}</button></nav></article>`).join(''):`<div class="ai-automation-empty">${icon('timer',27)}<strong>${esc(i18n.t('noAutomations'))}</strong><p>${esc(i18n.t('noAutomationsCopy'))}</p></div>`;
  return`<div class="ai-automation-settings"><header><div><h3>${esc(i18n.t('automations'))}</h3><p>${esc(i18n.t('automationsPageCopy'))}</p></div>${formOpen?'':`<button data-ai-new-automation>${icon('plus',11)}${esc(i18n.t('newAutomation'))}</button>`}</header>${form}<div class="ai-automation-list">${rows}</div></div>`;
}
