import { icon } from '../../icons.js';

const SECTIONS=[['appearance','sun'],['dock','grid'],['language','globe'],['network','wifi'],['privacySecurity','privacy'],['accessibility','accessibility'],['virtualMachine','vm'],['about','logo']];
export default{
  id:'settings',title:'settings',icon:'settings',color:'grey',width:920,height:610,singleInstance:true,
  mount(root,{settings,i18n,kernel,dialog,system,registry}){
    let section='appearance',query='';
    const render=()=>{const fullName=settings.get('fullName')||'Aeris User',initials=fullName.split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase(),visible=SECTIONS.filter(([key])=>i18n.t(key).toLowerCase().includes(query.toLowerCase()));root.innerHTML=`<div class="system-app settings-system"><aside class="system-sidebar settings-sections"><div class="settings-account"><span>${initials}</span><strong>${fullName}</strong><small>aeris · ${i18n.t('localAccount')}</small></div><label class="settings-search">${icon('search',14)}<input data-settings-search value="${query}" placeholder="${i18n.t('searchSettings')}"></label><nav>${visible.map(([key,glyph])=>`<button data-section="${key}" class="${section===key?'selected':''}">${icon(glyph,18)} ${i18n.t(key)}</button>`).join('')}</nav></aside><section data-settings-page class="settings-page-host"></section></div>`;root.querySelectorAll('[data-section]').forEach(button=>button.onclick=()=>{section=button.dataset.section;render()});root.querySelector('[data-settings-search]').oninput=event=>{query=event.target.value;render();requestAnimationFrame(()=>{const input=root.querySelector('[data-settings-search]');input?.focus();input?.setSelectionRange(query.length,query.length)})};show()};
    const header=(glyph,title,copy)=>`<header><span>${icon(glyph,25)}</span><div><h2>${title}</h2><p>${copy}</p></div></header>`;
    const toggle=(key,title,copy)=>`<label class="settings-toggle"><span><strong>${title}</strong><small>${copy}</small></span><input type="checkbox" data-setting="${key}" ${settings.get(key)?'checked':''}></label>`;
    const renderNetworkState=state=>{const label=root.querySelector('[data-guest-network]'),dot=root.querySelector('[data-guest-network-dot]'),error=root.querySelector('[data-network-error]'),details=root.querySelector('[data-network-details]');if(!label)return;label.textContent=i18n.t(state.status==='connected'?'guestNetworkConnected':state.status==='connecting'?'connecting':'guestNetworkUnavailable');dot.classList.toggle('online',state.status==='connected');dot.classList.toggle('connecting',state.status==='connecting');error.textContent=state.error||'';if(details){details.hidden=state.status!=='connected';details.querySelector('[data-network-address]').textContent=state.address||'—';details.querySelector('[data-network-gateway]').textContent=state.gateway||'—';details.querySelector('[data-network-dns]').textContent=state.dns||'—'}};
    const show=()=>{const page=root.querySelector('[data-settings-page]');
      if(section==='appearance')page.innerHTML=`${header('sun',i18n.t('appearance'),i18n.t('appearanceCopy'))}<h3>${i18n.t('theme')}</h3><div class="setting-options">${['light','dark'].map(v=>`<button data-theme="${v}" class="${settings.get('theme')===v?'current':''}"><i class="theme-preview ${v}"></i><span>${i18n.t(v)}</span></button>`).join('')}</div><h3>${i18n.t('accent')}</h3><div class="accent-options">${['#5f87d7','#7c6dd9','#d36f91','#4c9a86','#d18a55'].map(c=>`<button data-accent="${c}" style="--swatch:${c}" class="${settings.get('accent')===c?'current':''}"></button>`).join('')}</div><h3>${i18n.t('wallpaper')}</h3><div class="wallpaper-options">${['aurora','mist','sunset'].map(value=>`<button data-wallpaper="${value}" class="wallpaper-swatch wallpaper-${value} ${settings.get('wallpaper')===value?'current':''}"><span>${i18n.t(value)}</span></button>`).join('')}</div><div class="settings-toggle-list appearance-behavior">${toggle('restoreSession',i18n.t('restoreWindows'),i18n.t('restoreWindowsCopy'))}</div>`;
      if(section==='dock'){const pinned=settings.get('dockApps')||[];page.innerHTML=`${header('grid',i18n.t('dock'),i18n.t('dockCopy'))}<div class="dock-app-list">${registry.list().filter(app=>!app.dockSpecial&&!app.dockLeading).map(app=>`<label><span class="app-icon app-icon-${app.color}">${icon(app.icon,20)}</span><strong>${i18n.t(app.title)}</strong><input type="checkbox" data-dock-app="${app.id}" ${pinned.includes(app.id)?'checked':''}></label>`).join('')}</div><p class="settings-footnote">${i18n.t('aiDockNote')} ${i18n.t('trashDockNote')}</p>`}
      if(section==='language')page.innerHTML=`${header('globe',i18n.t('language'),i18n.t('chooseRegionCopy'))}<div class="language-list">${i18n.list().map(lang=>`<button data-locale="${lang.code}" class="language-row ${i18n.locale===lang.code?'current':''}"><span class="lang-badge">${lang.code.toUpperCase()}</span><strong>${lang.name}</strong>${i18n.locale===lang.code?icon('check',18):''}</button>`).join('')}</div><div class="setting-card settings-details"><label>${i18n.t('region')}<strong>${settings.get('region')}</strong></label><label>${i18n.t('timezone')}<strong>${settings.get('timezone')}</strong></label><label>${i18n.t('keyboardLayout')}<strong>${settings.get('keyboardLayout').toUpperCase()}</strong></label></div><button class="import-language" data-import-pack>${icon('upload',18)} ${i18n.t('addLanguage')}</button><small class="settings-import-status" data-import-status>${i18n.t('languagePackPathHint')}</small>`;
      if(section==='network'){page.innerHTML=`${header('wifi',i18n.t('network'),i18n.t('networkCopy'))}<div class="network-status-card"><span>${icon('wifi',25)}</span><div><strong data-guest-network>${i18n.t('checkingSystem')}</strong><small>${i18n.t('guestNetworkDisclosure')}</small></div><i data-guest-network-dot></i></div><div class="setting-card network-details" data-network-details hidden><label>${i18n.t('ipAddress')}<strong data-network-address>—</strong></label><label>${i18n.t('gateway')}<strong data-network-gateway>—</strong></label><label>${i18n.t('dnsServer')}<strong data-network-dns>—</strong></label></div><div class="setting-card network-reconnect-card"><button data-connect-guest>${icon('refresh',16)} ${i18n.t('reconnect')}</button><small data-network-error></small></div>`;renderNetworkState(system.networkState);page.querySelector('[data-connect-guest]').onclick=()=>system.ensureNetwork().catch(()=>{});system.networkInfo().catch(()=>{})}
      if(section==='privacySecurity')page.innerHTML=`${header('privacy',i18n.t('privacySecurity'),i18n.t('privacyCopy'))}<div class="settings-toggle-list">${toggle('location',i18n.t('locationServices'),i18n.t('locationCopy'))}${toggle('analytics',i18n.t('shareAnalytics'),i18n.t('analyticsCopy'))}</div>`;
      if(section==='accessibility')page.innerHTML=`${header('accessibility',i18n.t('accessibility'),i18n.t('accessibilityCopy'))}<div class="settings-toggle-list">${toggle('reduceMotion',i18n.t('reduceMotion'),i18n.t('reduceMotionCopy'))}</div>`;
      if(section==='virtualMachine')page.innerHTML=`${header('vm',i18n.t('virtualMachine'),'Alpine Linux 3.24 · x86')}<div class="setting-card"><label>${i18n.t('guestMemory')}<div class="settings-memory-options">${[256,512].map(v=>`<button data-memory="${v}" class="${settings.get('memory')===v?'selected':''}">${v} MB</button>`).join('')}</div></label><small>${i18n.t('machineRestoreCopy')}</small></div>`;
      if(section==='about')page.innerHTML=`<div class="about-page"><span class="about-logo">${icon('logo',48)}</span><h2>Aeris</h2><p>Browser operating system · 0.4.0</p><div class="info-card"><span>${i18n.t('engine')}</span><strong>v86 / WebAssembly</strong><span>${i18n.t('architecture')}</span><strong>x86 · Alpine Linux 3.24</strong><span>${i18n.t('applications')}</span><strong>${registry.list().length} ${i18n.t('systemApps')}</strong><span>${i18n.t('persistence')}</span><strong>IndexedDB + Linux home</strong></div></div>`;
      bindPage()};
    const bindPage=()=>{root.querySelectorAll('[data-theme]').forEach(button=>button.onclick=()=>settings.set('theme',button.dataset.theme));root.querySelectorAll('[data-accent]').forEach(button=>button.onclick=()=>settings.set('accent',button.dataset.accent));root.querySelectorAll('[data-wallpaper]').forEach(button=>button.onclick=()=>settings.set('wallpaper',button.dataset.wallpaper));root.querySelectorAll('[data-locale]').forEach(button=>button.onclick=()=>i18n.use(button.dataset.locale));root.querySelectorAll('[data-setting]').forEach(input=>input.onchange=()=>settings.set(input.dataset.setting,input.checked));root.querySelectorAll('[data-dock-app]').forEach(input=>input.onchange=()=>{const apps=(settings.get('dockApps')||[]).filter(id=>id!==input.dataset.dockApp);if(input.checked)apps.push(input.dataset.dockApp);settings.set('dockApps',apps)});root.querySelectorAll('[data-memory]').forEach(button=>button.onclick=()=>{settings.set('memory',Number(button.dataset.memory));show()});const importButton=root.querySelector('[data-import-pack]');if(importButton)importButton.onclick=async()=>{const status=root.querySelector('[data-import-status]'),path=await dialog.prompt({title:i18n.t('addLanguage'),message:i18n.t('languagePackPathHint'),value:'/mnt/aeris/',placeholder:'/mnt/aeris/language.json'});if(!path)return;try{i18n.install(JSON.parse(await system.read(path)));show()}catch(error){status.textContent=i18n.t('languagePackInvalid');status.classList.add('error')}}};
    const off=kernel.bus.on('settings:change',({key,value})=>{if(key==='theme')document.documentElement.dataset.theme=value;if(key==='reduceMotion')document.documentElement.dataset.reduceMotion=value?'true':'false';if(['locale','theme','accent'].includes(key))render()}),offNetwork=kernel.bus.on('network:change',renderNetworkState);render();return()=>{off();offNetwork()};
  }
};
