import { icon } from '../../icons.js';
const esc=value=>String(value??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');

const SECTIONS=[['appearance','sun'],['dock','grid'],['language','globe'],['network','wifi'],['privacySecurity','privacy'],['accessibility','accessibility'],['virtualMachine','vm'],['about','logo']];
export default{
  id:'settings',title:'settings',icon:'settings',color:'grey',width:920,height:610,singleInstance:true,
  mount(root,{settings,themeRuntime,i18n,kernel,dialog,system,registry,factoryReset,agentContext}){
    let section='appearance',query='';
    const render=()=>{const fullName=settings.get('fullName')||'Future User',initials=fullName.split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase(),visible=SECTIONS.filter(([key])=>i18n.t(key).toLowerCase().includes(query.toLowerCase()));root.innerHTML=`<div class="system-app settings-system"><aside class="system-sidebar settings-sections"><div class="settings-account"><span>${initials}</span><strong>${fullName}</strong><small>future · ${i18n.t('localAccount')}</small></div><label class="settings-search">${icon('search',14)}<input data-settings-search value="${query}" placeholder="${i18n.t('searchSettings')}"></label><nav>${visible.map(([key,glyph])=>`<button data-section="${key}" class="${section===key?'selected':''}">${icon(glyph,18)} ${i18n.t(key)}</button>`).join('')}</nav></aside><section data-settings-page class="settings-page-host"></section></div>`;root.querySelectorAll('[data-section]').forEach(button=>button.onclick=()=>{section=button.dataset.section;render()});root.querySelector('[data-settings-search]').oninput=event=>{query=event.target.value;render();requestAnimationFrame(()=>{const input=root.querySelector('[data-settings-search]');input?.focus();input?.setSelectionRange(query.length,query.length)})};agentContext.set({appId:'settings',label:i18n.t('settings'),resource:{kind:'settings-section',id:section,name:i18n.t(section),metadata:{query}}});show()};
    const header=(glyph,title,copy)=>`<header><span>${icon(glyph,25)}</span><div><h2>${title}</h2><p>${copy}</p></div></header>`;
    const toggle=(key,title,copy)=>`<label class="settings-toggle"><span><strong>${title}</strong><small>${copy}</small></span><input type="checkbox" data-setting="${key}" ${settings.get(key)?'checked':''}></label>`;
    const renderNetworkState=state=>{const label=root.querySelector('[data-guest-network]'),dot=root.querySelector('[data-guest-network-dot]'),error=root.querySelector('[data-network-error]'),details=root.querySelector('[data-network-details]');if(!label)return;label.textContent=i18n.t(state.status==='connected'?'guestNetworkConnected':state.status==='connecting'?'connecting':'guestNetworkUnavailable');dot.classList.toggle('online',state.status==='connected');dot.classList.toggle('connecting',state.status==='connecting');error.textContent=state.error||'';if(details){details.hidden=state.status!=='connected';details.querySelector('[data-network-address]').textContent=state.address||'—';details.querySelector('[data-network-gateway]').textContent=state.gateway||'—';details.querySelector('[data-network-dns]').textContent=state.dns||'—'}};
    const show=()=>{const page=root.querySelector('[data-settings-page]');
      if(section==='appearance'){const themes=themeRuntime.list(),locale=i18n.locale;page.innerHTML=`${header('sun',i18n.t('appearance'),i18n.t('themePlatformCopy'))}<h3>${i18n.t('systemThemes')}</h3><div class="theme-gallery">${themes.map(theme=>`<button class="theme-card ${theme.active?'current':''} ${theme.preview?'previewing':''}" ${theme.installed?`data-theme-id="${theme.manifest.id}"`:'aria-disabled="true"'} ${theme.preview?`data-preview-label="${esc(i18n.t('preview'))}"`:''} style="--theme-preview:${esc(theme.wallpaper.background)}"><span class="theme-card-preview"></span><span><strong>${esc(theme.manifest.name[locale]||theme.manifest.name.en)}</strong><small>${esc(theme.manifest.author)} · ${theme.manifest.baseMode==='dark'?i18n.t('dark'):i18n.t('light')}${theme.preview?` · ${i18n.t('preview')}`:''}</small></span></button>`).join('')}</div><p class="settings-footnote">${i18n.t('themeAgentCopy')}</p><div class="settings-toggle-list appearance-behavior">${toggle('restoreSession',i18n.t('restoreWindows'),i18n.t('restoreWindowsCopy'))}</div>`}
      if(section==='dock'){const pinned=settings.get('dockApps')||[];page.innerHTML=`${header('grid',i18n.t('dock'),i18n.t('dockCopy'))}<div class="dock-app-list">${registry.list().filter(app=>!app.dockSpecial&&!app.dockLeading).map(app=>`<label><span class="app-icon app-icon-${app.color}">${icon(app.icon,20)}</span><strong>${i18n.t(app.title)}</strong><input type="checkbox" data-dock-app="${app.id}" ${pinned.includes(app.id)?'checked':''}></label>`).join('')}</div><p class="settings-footnote">${i18n.t('aiDockNote')} ${i18n.t('trashDockNote')}</p>`}
      if(section==='language')page.innerHTML=`${header('globe',i18n.t('language'),i18n.t('chooseRegionCopy'))}<div class="language-list">${i18n.list().map(lang=>`<button data-locale="${lang.code}" class="language-row ${i18n.locale===lang.code?'current':''}"><span class="lang-badge">${lang.code.toUpperCase()}</span><strong>${lang.name}</strong>${i18n.locale===lang.code?icon('check',18):''}</button>`).join('')}</div><div class="setting-card settings-details"><label>${i18n.t('region')}<strong>${settings.get('region')}</strong></label><label>${i18n.t('timezone')}<strong>${settings.get('timezone')}</strong></label><label>${i18n.t('keyboardLayout')}<strong>${settings.get('keyboardLayout').toUpperCase()}</strong></label></div><button class="import-language" data-import-pack>${icon('upload',18)} ${i18n.t('addLanguage')}</button><small class="settings-import-status" data-import-status>${i18n.t('languagePackPathHint')}</small>`;
      if(section==='network'){page.innerHTML=`${header('wifi',i18n.t('network'),i18n.t('networkCopy'))}<div class="network-status-card"><span>${icon('wifi',25)}</span><div><strong data-guest-network>${i18n.t('checkingSystem')}</strong><small>${i18n.t('guestNetworkDisclosure')}</small></div><i data-guest-network-dot></i></div><div class="setting-card network-details" data-network-details hidden><label>${i18n.t('ipAddress')}<strong data-network-address>—</strong></label><label>${i18n.t('gateway')}<strong data-network-gateway>—</strong></label><label>${i18n.t('dnsServer')}<strong data-network-dns>—</strong></label></div><div class="setting-card network-reconnect-card"><button data-connect-guest>${icon('refresh',16)} ${i18n.t('reconnect')}</button><small data-network-error></small></div>`;renderNetworkState(system.networkState);page.querySelector('[data-connect-guest]').onclick=()=>system.ensureNetwork().catch(()=>{});system.networkInfo().catch(()=>{})}
      if(section==='privacySecurity')page.innerHTML=`${header('privacy',i18n.t('privacySecurity'),i18n.t('privacyCopy'))}<div class="settings-toggle-list">${toggle('location',i18n.t('locationServices'),i18n.t('locationCopy'))}${toggle('analytics',i18n.t('shareAnalytics'),i18n.t('analyticsCopy'))}</div>`;
      if(section==='accessibility')page.innerHTML=`${header('accessibility',i18n.t('accessibility'),i18n.t('accessibilityCopy'))}<div class="settings-toggle-list">${toggle('reduceMotion',i18n.t('reduceMotion'),i18n.t('reduceMotionCopy'))}</div>`;
      if(section==='virtualMachine')page.innerHTML=`${header('vm',i18n.t('virtualMachine'),'Alpine Linux 3.24 · x86')}<div class="setting-card"><label>${i18n.t('guestMemory')}<div class="settings-memory-options">${[256,512].map(v=>`<button data-memory="${v}" class="${settings.get('memory')===v?'selected':''}">${v} MB</button>`).join('')}</div></label><small>${i18n.t('machineRestoreCopy')}</small></div><div class="setting-card settings-danger-zone"><span><strong>${i18n.t('factoryReset')}</strong><small>${i18n.t('factoryResetCopy')}</small><em data-reset-status></em></span><button data-factory-reset>${i18n.t('eraseReinstall')}</button></div>`;
      if(section==='about')page.innerHTML=`<div class="about-page"><span class="about-logo">${icon('logo',48)}</span><h2>Future</h2><p>Browser operating system · 0.4.0</p><div class="info-card"><span>${i18n.t('engine')}</span><strong>v86 / WebAssembly</strong><span>${i18n.t('architecture')}</span><strong>x86 · Alpine Linux 3.24</strong><span>${i18n.t('applications')}</span><strong>${registry.list().length} ${i18n.t('systemApps')}</strong><span>${i18n.t('persistence')}</span><strong>IndexedDB + Linux home</strong></div></div>`;
      bindPage()};
    const bindPage=()=>{root.querySelectorAll('[data-theme-id]').forEach(button=>button.onclick=()=>themeRuntime.apply(button.dataset.themeId));root.querySelectorAll('[data-locale]').forEach(button=>button.onclick=()=>i18n.use(button.dataset.locale));root.querySelectorAll('[data-setting]').forEach(input=>input.onchange=()=>settings.set(input.dataset.setting,input.checked));root.querySelectorAll('[data-dock-app]').forEach(input=>input.onchange=()=>{const apps=(settings.get('dockApps')||[]).filter(id=>id!==input.dataset.dockApp);if(input.checked)apps.push(input.dataset.dockApp);settings.set('dockApps',apps)});root.querySelectorAll('[data-memory]').forEach(button=>button.onclick=()=>{settings.set('memory',Number(button.dataset.memory));show()});const resetButton=root.querySelector('[data-factory-reset]');if(resetButton)resetButton.onclick=async()=>{const approved=await dialog.confirm({title:i18n.t('factoryReset'),message:i18n.t('eraseReinstallWarning'),confirmLabel:i18n.t('eraseReinstall'),danger:true});if(!approved)return;const status=root.querySelector('[data-reset-status]');resetButton.disabled=true;resetButton.classList.add('running');status.textContent=i18n.t('resettingSystem');try{await factoryReset.reset()}catch(error){resetButton.disabled=false;resetButton.classList.remove('running');status.textContent=`${i18n.t('factoryResetFailed')} ${error.message||error}`}};const importButton=root.querySelector('[data-import-pack]');if(importButton)importButton.onclick=async()=>{const status=root.querySelector('[data-import-status]'),path=await dialog.prompt({title:i18n.t('addLanguage'),message:i18n.t('languagePackPathHint'),value:'/mnt/future/',placeholder:'/mnt/future/language.json'});if(!path)return;try{i18n.install(JSON.parse(await system.read(path)));show()}catch(error){status.textContent=i18n.t('languagePackInvalid');status.classList.add('error')}}};
    const off=kernel.bus.on('settings:change',({key,value})=>{if(key==='reduceMotion')document.documentElement.dataset.reduceMotion=value?'true':'false';if(key==='locale')render()}),refreshThemes=()=>section==='appearance'&&render(),offTheme=kernel.bus.on('theme:changed',refreshThemes),offThemeInstall=kernel.bus.on('theme:installed',refreshThemes),offThemeUpdate=kernel.bus.on('theme:updated',refreshThemes),offThemeUninstall=kernel.bus.on('theme:uninstalled',refreshThemes),offNetwork=kernel.bus.on('network:change',renderNetworkState);render();return()=>{off();offTheme();offThemeInstall();offThemeUpdate();offThemeUninstall();offNetwork()};
  }
};
