import{validateWidgetPackage,widgetLocalePacks}from'../platform/widgets/WidgetPackage.js';
import{embeddedThemeStyles}from'../platform/themes/EmbeddedThemeStyles.js';

const PACKAGES_KEY='future.widget-runtime.packages.v1',STATE_PREFIX='future.widget-runtime.state.v1.',MAX_STATE_BYTES=64*1024;
const clone=value=>structuredClone(value),scriptText=value=>String(value||'').replace(/<\/script/gi,'<\\/script'),styleText=value=>String(value||'').replace(/<\/style/gi,'<\\/style');
const DATA_PERMISSIONS={calendar:'calendar.read',reminders:'reminders.read',weather:'weather.read',metrics:'metrics.read',music:'music.read'};
const sdkBootstrap=`
(()=>{let port,state={},environment={},sequence=0;const pending=new Map(),stateListeners=new Set(),environmentListeners=new Set(),lifecycleListeners=new Set(),errorListeners=new Set(),dataListeners=new Map();
const clone=value=>structuredClone(value);const request=(method,params={})=>new Promise((resolve,reject)=>{if(!port)return reject(new Error('Future Widget SDK is not connected.'));const id=++sequence;pending.set(id,{resolve,reject});port.postMessage({type:'request',id,method,params})});
let resolveReady;const ready=new Promise(resolve=>resolveReady=resolve);const applyEnvironment=value=>{environment=value||{};document.documentElement.lang=environment.locale||'en';document.documentElement.dataset.theme=environment.theme||'light';document.documentElement.dataset.themeId=environment.themeId||environment.theme||'light';document.documentElement.dataset.themeMotion=environment.tokens?.motion?.scale===0?'none':'full';document.documentElement.dataset.size=environment.size||'medium';document.documentElement.dataset.visible=String(environment.visible!==false);for(const[name,token]of Object.entries(environment.variables||{}))document.documentElement.style.setProperty(name,token);document.documentElement.style.setProperty('--accent',environment.accent||'#1788c8');environmentListeners.forEach(listener=>listener(clone(environment)))};
const reportError=(error,operation)=>{const value={message:error?.message||String(error),operation};errorListeners.forEach(listener=>listener(value));if(!errorListeners.size)console.error('[FutureWidget]',value.message)};
const api=Object.freeze({ready,state:Object.freeze({get:()=>request('get-state'),set:value=>request('set-state',{value}),patch:patch=>request('patch-state',{patch}),subscribe(listener){stateListeners.add(listener);if(port)listener(clone(state));return()=>stateListeners.delete(listener)}}),data:Object.freeze({get:source=>request('get-data',{source}),subscribe(source,listener){const listeners=dataListeners.get(source)||new Set();listeners.add(listener);dataListeners.set(source,listeners);request('subscribe-data',{source}).then(value=>listener(clone(value))).catch(error=>reportError(error,'data.subscribe:'+source));return()=>{listeners.delete(listener);if(!listeners.size){dataListeners.delete(source);request('unsubscribe-data',{source}).catch(error=>reportError(error,'data.unsubscribe:'+source))}}}}),music:Object.freeze({play:track=>request('music-control',{action:'play',value:track}),pause:()=>request('music-control',{action:'pause'}),toggle:()=>request('music-control',{action:'toggle'}),next:()=>request('music-control',{action:'next'}),previous:()=>request('music-control',{action:'previous'}),seek:seconds=>request('music-control',{action:'seek',value:seconds}),setVolume:value=>request('music-control',{action:'set-volume',value}),toggleShuffle:()=>request('music-control',{action:'toggle-shuffle'}),cycleRepeat:()=>request('music-control',{action:'cycle-repeat'}),refresh:()=>request('music-control',{action:'refresh'})}),apps:Object.freeze({open:(appId,params={})=>request('open-app',{appId,params})}),environment:Object.freeze({get current(){return clone(environment)},subscribe(listener){environmentListeners.add(listener);if(port)listener(clone(environment));return()=>environmentListeners.delete(listener)}}),lifecycle:Object.freeze({subscribe(listener){lifecycleListeners.add(listener);return()=>lifecycleListeners.delete(listener)}}),errors:Object.freeze({subscribe(listener){errorListeners.add(listener);return()=>errorListeners.delete(listener)}}),i18n:Object.freeze({t:key=>environment.strings?.[key]??key})});
Object.defineProperty(window,'FutureWidget',{value:api,writable:false,configurable:false});addEventListener('message',event=>{if(event.data?.type!=='future-widget:connect'||!event.ports?.[0]||port)return;port=event.ports[0];port.onmessage=message=>{const data=message.data||{};if(data.type==='response'){const task=pending.get(data.id);if(task){pending.delete(data.id);data.error?task.reject(new Error(data.error)):task.resolve(data.result)}}if(data.type==='state'){state=clone(data.value||{});stateListeners.forEach(listener=>listener(clone(state)))}if(data.type==='environment')applyEnvironment(data.value);if(data.type==='data'){for(const listener of dataListeners.get(data.source)||[])listener(clone(data.value))}if(data.type==='lifecycle')lifecycleListeners.forEach(listener=>listener(data.event))};state=clone(event.data.state||{});applyEnvironment(event.data.environment||{});port.start();resolveReady(api);stateListeners.forEach(listener=>listener(clone(state)))},{once:true});addEventListener('contextmenu',event=>{event.preventDefault();port?.postMessage({type:'event',name:'contextmenu',x:event.clientX,y:event.clientY})},true)})();`;

export class WidgetRuntimeService{
  constructor({registry,storage=globalThis.localStorage,bundledPackages=[],themeRuntime=null}={}){this.registry=registry;this.storage=storage;this.bundledPackages=bundledPackages;this.themeRuntime=themeRuntime;this.packages=new Map();this.mounts=new Map();this.offs=[]}
  async prepare(){let records=[];try{records=JSON.parse(this.storage?.getItem(PACKAGES_KEY)||'[]')}catch{}for(const record of Array.isArray(records)?records:[])try{this.#add(validateWidgetPackage(record.package),record.source||'user')}catch(error){console.warn('Skipped invalid Future widget package.',error)}for(const source of this.bundledPackages){const widgetPackage=validateWidgetPackage(source),current=this.packages.get(widgetPackage.manifest.id);if(!current||current.source==='bundled'){if(current)this.registry.unregister(widgetPackage.manifest.id);this.#add(widgetPackage,'bundled')}}this.#persist()}
  start(){const bus=this.kernel.bus;this.offs.push(bus.on('settings:change',()=>this.#broadcastEnvironment()),bus.on('theme:changed',()=>this.#broadcastEnvironment()),bus.on('userdata:change',detail=>{if(detail?.name==='calendar'||detail?.name==='reminders')this.#broadcastData(detail.name)}),bus.on('weather:update',()=>this.#broadcastData('weather')),bus.on('metrics:update',()=>this.#broadcastData('metrics')),bus.on('music:changed',()=>this.#broadcastData('music')),bus.on('music:time',()=>this.#broadcastData('music')),bus.on('music:volume',()=>this.#broadcastData('music')))}
  stop(){this.offs.splice(0).forEach(off=>off());for(const id of [...this.mounts.keys()])this.#closeMounts(id)}
  list(){return[...this.packages.values()].map(record=>({manifest:clone(record.package.manifest),source:record.source}))}
  get(id){const record=this.packages.get(id);return record?clone(record.package):null}
  install(source,{replace=false,preserveState=replace}={}){const widgetPackage=validateWidgetPackage(source),id=widgetPackage.manifest.id,current=this.packages.get(id);if(this.registry.get(id)&&!current)throw new Error(`Widget id is already in use: ${id}`);if(current&&!replace)throw new Error(`Widget is already installed: ${id}`);if(current?.source==='bundled')throw new Error('Bundled widgets cannot be replaced.');if(current){this.#closeMounts(id);if(!preserveState)this.storage?.removeItem(`${STATE_PREFIX}${id}`);this.packages.set(id,{package:widgetPackage,source:'user'});this.registry.replace(this.#definition(widgetPackage))}else this.#add(widgetPackage,'user');this.#persist();this.kernel?.bus.emit(current?'widget-runtime:updated':'widget-runtime:installed',{widgetId:id,manifest:clone(widgetPackage.manifest)});return clone(widgetPackage.manifest)}
  uninstall(id,{allowBundled=false,persist=true,preserveState=false}={}){const record=this.packages.get(id);if(!record)return false;if(record.source==='bundled'&&!allowBundled)throw new Error('Bundled widgets cannot be uninstalled.');this.#closeMounts(id);this.registry.unregister(id);this.packages.delete(id);if(!preserveState)this.storage?.removeItem(`${STATE_PREFIX}${id}`);if(persist)this.#persist();this.kernel?.bus.emit('widget-runtime:uninstalled',{widgetId:id});return true}
  mount(id,root,context={},target={}){const record=this.packages.get(id);if(!record)throw new Error(`Unknown extension widget: ${id}`);const widgetPackage=record.package,iframe=document.createElement('iframe');iframe.className='future-widget-frame';iframe.title=this.#localized(widgetPackage.manifest.name,context.i18n?.locale);iframe.sandbox='allow-scripts';iframe.referrerPolicy='no-referrer';iframe.hidden=true;root.innerHTML='<div class="future-widget-loading" role="status"><i></i></div>';const channel=new MessageChannel(),mount={iframe,port:channel.port1,context,target,subscriptions:new Set(),visible:true,observer:null,refreshTimer:0};const mounts=this.mounts.get(id)||new Set();mounts.add(mount);this.mounts.set(id,mounts);channel.port1.onmessage=event=>this.#handleRequest(id,mount,event.data);channel.port1.start();iframe.onload=()=>{iframe.onload=null;iframe.hidden=false;root.querySelector('.future-widget-loading')?.remove();iframe.contentWindow?.postMessage({type:'future-widget:connect',state:this.#state(widgetPackage),environment:this.#environment(widgetPackage,context,target,mount.visible)},'*',[channel.port2]);if(widgetPackage.manifest.refresh.mode==='interval')mount.refreshTimer=setInterval(()=>{if(mount.visible)mount.port.postMessage({type:'lifecycle',event:'refresh'})},widgetPackage.manifest.refresh.interval*1000)};iframe.srcdoc=this.#document(widgetPackage);root.append(iframe);mount.observer=new IntersectionObserver(entries=>{const visible=Boolean(entries[0]?.isIntersecting);if(visible!==mount.visible){mount.visible=visible;mount.port.postMessage({type:'environment',value:this.#environment(widgetPackage,context,target,visible)});mount.port.postMessage({type:'lifecycle',event:visible?'resume':'pause'})}},{threshold:.01});mount.observer.observe(iframe);return()=>this.#disposeMount(id,mount)}
  #definition(widgetPackage){const manifest=widgetPackage.manifest,id=manifest.id;return{id,name:manifest.name,description:manifest.description,glyph:manifest.icon,sizes:manifest.sizes,defaultSize:manifest.defaultSize,extension:true,mount:(root,context,target)=>this.mount(id,root,context,target)}}
  #add(widgetPackage,source){const id=widgetPackage.manifest.id;if(this.registry.get(id))throw new Error(`Widget id is already in use: ${id}`);this.packages.set(id,{package:widgetPackage,source});this.registry.register(this.#definition(widgetPackage))}
  #state(widgetPackage){try{const raw=this.storage?.getItem(`${STATE_PREFIX}${widgetPackage.manifest.id}`);return raw?JSON.parse(raw):clone(widgetPackage.manifest.initialState)}catch{return clone(widgetPackage.manifest.initialState)}}
  #setState(widgetPackage,value){if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('Widget state must be an object.');const encoded=JSON.stringify(value);if(new TextEncoder().encode(encoded).length>MAX_STATE_BYTES)throw new Error(`Widget state exceeds ${MAX_STATE_BYTES} bytes.`);const state=clone(value);this.storage?.setItem(`${STATE_PREFIX}${widgetPackage.manifest.id}`,encoded);for(const mount of this.mounts.get(widgetPackage.manifest.id)||[])mount.port.postMessage({type:'state',value:clone(state)});return state}
  async #handleRequest(id,mount,message){if(message?.type==='event'){if(message.name==='contextmenu'){const rect=mount.iframe.getBoundingClientRect();mount.iframe.dispatchEvent(new MouseEvent('contextmenu',{bubbles:true,cancelable:true,clientX:rect.left+(Number(message.x)||0),clientY:rect.top+(Number(message.y)||0),button:2,buttons:2}))}return}if(message?.type!=='request')return;const record=this.packages.get(id);if(!record)return;const{id:requestId,method,params={}}=message;try{let result;if(method==='get-state'){this.#assertPermission(record.package,'storage');result=this.#state(record.package)}else if(method==='set-state'){this.#assertPermission(record.package,'storage');result=this.#setState(record.package,params.value)}else if(method==='patch-state'){this.#assertPermission(record.package,'storage');result=this.#setState(record.package,{...this.#state(record.package),...(params.patch||{})})}else if(method==='get-data'||method==='subscribe-data'){this.#assertDataPermission(record.package,params.source);if(method==='subscribe-data')mount.subscriptions.add(params.source);result=await this.#data(params.source,mount.context)}else if(method==='unsubscribe-data'){mount.subscriptions.delete(params.source);result={subscribed:false}}else if(method==='music-control'){this.#assertPermission(record.package,'music.control');result=await this.#musicControl(params.action,params.value,mount.context)}else if(method==='open-app'){this.#assertPermission(record.package,'app.open');if(!mount.context.registry?.get(params.appId))throw new Error(`Unknown application: ${params.appId}`);mount.context.shell?.open(params.appId,params.params?.path);result={opened:true}}else throw new Error(`Unsupported Future Widget SDK method: ${method}`);mount.port.postMessage({type:'response',id:requestId,result:clone(result)})}catch(error){mount.port.postMessage({type:'response',id:requestId,error:error.message||String(error)})}}
  #assertPermission(widgetPackage,permission){if(!widgetPackage.manifest.permissions.includes(permission))throw new Error(`Widget permission is required: ${permission}`)}
  #assertDataPermission(widgetPackage,source){const permission=DATA_PERMISSIONS[source];if(!permission)throw new Error(`Unknown widget data source: ${source}`);this.#assertPermission(widgetPackage,permission)}
  async #data(source,context){if(source==='calendar')return context.userdata.load('calendar',{events:[]});if(source==='reminders')return context.userdata.load('reminders',[]);if(source==='weather')return context.weather.snapshot();if(source==='metrics')return context.metrics.snapshot();if(source==='music')return context.music.snapshot();throw new Error(`Unknown widget data source: ${source}`)}
  async #musicControl(action,value,context){const music=context.music;if(action==='play'){if(value)await music.play(String(value));else await music.toggle()}else if(action==='pause')music.pause();else if(action==='toggle')await music.toggle();else if(action==='next')await music.next();else if(action==='previous')await music.previous();else if(action==='seek')music.seek(value);else if(action==='set-volume')music.setVolume(value);else if(action==='toggle-shuffle')music.toggleShuffle();else if(action==='cycle-repeat')music.cycleRepeat();else if(action==='refresh')await music.refresh();else throw new Error(`Unsupported music control: ${action}`);return{completed:true,action}}
  async #broadcastData(source){for(const [id,mounts] of this.mounts){const record=this.packages.get(id);if(!record)continue;for(const mount of mounts)if(mount.subscriptions.has(source))try{mount.port.postMessage({type:'data',source,value:clone(await this.#data(source,mount.context))})}catch{}}}
  #environment(widgetPackage,context,target,visible){const settings=context.settings,locale=context.i18n?.locale||settings?.get?.('locale')||'en',packs=widgetLocalePacks(widgetPackage),theme=this.themeRuntime?.snapshot()||context.themeRuntime?.snapshot();return{widgetId:widgetPackage.manifest.id,locale,strings:packs[locale]||packs.en,theme:theme?.baseMode||'light',themeId:theme?.id||settings?.get?.('theme')||'light',themeVersion:theme?.version||'',tokens:clone(theme?.tokens||{}),variables:clone(theme?.variables||{}),accent:theme?.tokens?.colors?.accent||settings?.get?.('accent')||'#1788c8',size:target.size||widgetPackage.manifest.defaultSize,visible}}
  #broadcastEnvironment(){for(const [id,mounts] of this.mounts){const record=this.packages.get(id);if(record)for(const mount of mounts)mount.port.postMessage({type:'environment',value:this.#environment(record.package,mount.context,mount.target,mount.visible)})}}
  #localized(value,locale='en'){return value?.[locale]||value?.en||Object.values(value||{})[0]||''}
  #disposeMount(id,mount){clearInterval(mount.refreshTimer);mount.observer?.disconnect();mount.port.close();mount.iframe.remove();const mounts=this.mounts.get(id);mounts?.delete(mount);if(!mounts?.size)this.mounts.delete(id)}
  #closeMounts(id){for(const mount of [...(this.mounts.get(id)||[])])this.#disposeMount(id,mount)}
  #persist(){this.storage?.setItem(PACKAGES_KEY,JSON.stringify([...this.packages.values()].map(record=>({source:record.source,package:record.package}))))}
  #document(widgetPackage){const entry=widgetPackage.manifest.entry,files=widgetPackage.files;return`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src data: blob:; style-src 'unsafe-inline'; script-src 'unsafe-inline'; font-src data:; connect-src 'none'"><style>:root{color-scheme:light;--font-ui:Manrope,"SF Pro Display","Segoe UI",sans-serif;--font-mono:"Ubuntu Mono",ui-monospace,monospace;--accent:#5f87d7;--surface:rgba(245,249,251,.62);--surface-2:rgba(255,255,255,.42);--text:#31445a;--muted:#77899b;--line:rgba(96,122,138,.14);--shadow:0 8px 22px rgba(45,62,77,.14);--small-shadow:0 4px 12px rgba(45,62,77,.1);font-family:var(--font-ui);color:var(--text)}:root[data-theme="dark"]{color-scheme:dark;--surface:rgba(40,58,70,.64);--surface-2:rgba(255,255,255,.06);--text:#dce7ed;--muted:#91a6b2;--line:rgba(255,255,255,.09);--shadow:0 8px 22px rgba(9,22,29,.26);--small-shadow:0 4px 12px rgba(9,22,29,.2)}:root[data-theme-id="glass"]{color-scheme:dark;--surface:rgba(14,27,56,.7);--surface-2:rgba(255,255,255,.1);--shadow:0 16px 38px rgba(2,8,28,.32),inset 0 1px rgba(255,255,255,.18);--small-shadow:0 7px 18px rgba(2,8,28,.22),inset 0 1px rgba(255,255,255,.13)}:root[data-theme-id="glass"] body{background:linear-gradient(145deg,rgba(11,24,53,.65),rgba(52,28,90,.45));backdrop-filter:blur(var(--glass-blur,22px)) saturate(var(--glass-saturation,1.55))}:root[data-theme-id="glass"] button,:root[data-theme-id="glass"] input,:root[data-theme-id="glass"] select{border-color:var(--line)!important;background-color:rgba(255,255,255,.09);box-shadow:inset 0 1px rgba(255,255,255,.12)}*{box-sizing:border-box}html,body{width:100%;height:100%;margin:0;overflow:hidden}body{background:transparent;color:var(--text)}button,input,textarea,select{font:inherit;color:inherit}button{border:0;background:none}button:focus-visible,input:focus-visible{outline:2px solid var(--accent);outline-offset:2px}:root[data-theme-motion="none"] *,:root[data-theme-motion="none"] *:before,:root[data-theme-motion="none"] *:after{animation-duration:.001ms!important;animation-iteration-count:1!important;transition-duration:.001ms!important}@media(prefers-reduced-motion:reduce){*,*:before,*:after{animation-duration:.001ms!important;transition-duration:.001ms!important}}</style><style>${styleText(files[entry.css])}</style><style>${embeddedThemeStyles}</style><style>body,body *{font-family:var(--font-ui)!important}code,code *,pre,pre *,kbd,samp{font-family:var(--font-mono)!important}</style></head><body>${files[entry.html]}<script>${scriptText(sdkBootstrap)}</script><script>${scriptText(files[entry.script])}</script></body></html>`}
}
