import {icon} from '../../icons.js';
const LIBRARY='/home/future/Pictures';
const esc=value=>String(value??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/"/g,'&quot;');
const quote=value=>`'${String(value).replace(/'/g,`'"'"'`)}'`;
const isImage=name=>/\.(png|jpe?g|gif|webp|svg|bmp)$/i.test(name);
const mime=name=>({png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg',gif:'image/gif',webp:'image/webp',svg:'image/svg+xml',bmp:'image/bmp'})[name.split('.').at(-1).toLowerCase()]||'image/jpeg';
export default{
  id:'photos',title:'photos',icon:'image',color:'rainbow',width:1080,height:700,singleInstance:true,
  mount(root,{system,userdata,dialog,i18n,shell,kernel}){
    let section='library',items=[],selected='',query='',loading=true,state={favorites:[],albums:[]},urls=new Map();
    const filtered=()=>{const album=state.albums.find(x=>x.id===section);return items.filter(item=>isImage(item.name)&&(!query||item.name.toLowerCase().includes(query.toLowerCase()))&&(section!=='favorites'||state.favorites.includes(item.name))&&(!album||album.items.includes(item.name)))};
    const draw=()=>{const shown=filtered();root.innerHTML=`<div class="system-app photos-app"><aside><header><span class="photos-flower">${icon('image',22)}</span><strong>${i18n.t('photos')}</strong></header><nav><small>${i18n.t('library')}</small>${[['library','image'],['favorites','star'],['recent','clock']].map(([id,glyph])=>`<button data-photos-section="${id}" class="${section===id?'selected':''}">${icon(glyph,16)}<span>${i18n.t(id)}</span><b>${id==='favorites'?state.favorites.length:''}</b></button>`).join('')}<small>${i18n.t('albums')}</small><button data-new-album>${icon('plus',16)}<span>${i18n.t('newAlbum')}</span></button>${state.albums.map(album=>`<button data-album="${album.id}" class="${section===album.id?'selected':''}">${icon('folder',16)}<span>${esc(album.name)}</span><b>${album.items.length}</b></button>`).join('')}</nav><footer>${items.length} ${i18n.t('photos')}</footer></aside><section><div class="app-commandbar"><div><h1>${i18n.t(section==='library'?'allPhotos':section==='favorites'?'favorites':section==='recent'?'recent':'album')}</h1><small>${shown.length} ${i18n.t('items')}</small></div><div class="toolbar-spacer"></div><label class="photos-search">${icon('search',14)}<input value="${esc(query)}" placeholder="${i18n.t('search')}"></label><button data-photo-favorite ${selected?'':'disabled'} class="${state.favorites.includes(selected)?'selected':''}">${icon('star',15)}</button><button data-photo-import>${icon('upload',15)} ${i18n.t('import')}</button></div><main>${loading?`<div class="app-loading"><i></i>${i18n.t('loading')}</div>`:shown.length?`<div class="photos-timeline"><header><div><strong>${new Intl.DateTimeFormat(i18n.t('dateFormat'),{month:'long',year:'numeric'}).format(new Date())}</strong><small>${i18n.t('photoLibrary')}</small></div></header><div class="photos-grid">${shown.map(item=>`<button data-photo="${esc(item.name)}" class="${selected===item.name?'selected':''}"><span data-photo-thumb="${esc(item.name)}">${urls.has(item.name)?`<img alt="" src="${urls.get(item.name)}">`:icon('image',34)}</span><strong>${esc(item.name)}</strong>${state.favorites.includes(item.name)?`<i>${icon('star',12)}</i>`:''}</button>`).join('')}</div></div>`:`<div class="photos-empty">${icon(section==='favorites'?'star':'image',62)}<strong>${i18n.t(section==='favorites'?'noFavorites':'noPhotos')}</strong><p>${i18n.t('photosEmptyCopy')}</p><button data-photo-import>${i18n.t('importPhotos')}</button></div>`}</main><footer class="app-statusbar"><span>${i18n.t('photosLibraryLocation')}: ${LIBRARY}</span><span>${selected?esc(selected):''}</span></footer></section></div>`;bind();loadThumbs(shown)};
    const save=()=>userdata.save('photos',state);
    const refresh=async()=>{loading=true;draw();try{items=await system.list(LIBRARY,{priority:true})}catch{items=[]}loading=false;draw()};
    const loadThumbs=async shown=>{for(const item of shown.slice(0,60)){if(urls.has(item.name))continue;try{const {output}=await system.execChecked(`base64 < ${quote(`${LIBRARY}/${item.name}`)} | tr -d '\\n'`,30000);urls.set(item.name,`data:${mime(item.name)};base64,${output}`);const slot=root.querySelector(`[data-photo-thumb="${CSS.escape(item.name)}"]`);if(slot)slot.innerHTML=`<img alt="" src="${urls.get(item.name)}">`}catch{}}};
    const bind=()=>{root.querySelectorAll('[data-photos-section]').forEach(button=>button.onclick=()=>{section=button.dataset.photosSection;selected='';draw()});root.querySelectorAll('[data-album]').forEach(button=>button.onclick=()=>{section=button.dataset.album;selected='';draw()});const search=root.querySelector('.photos-search input');if(search)search.oninput=()=>{query=search.value;draw();requestAnimationFrame(()=>{const next=root.querySelector('.photos-search input');next?.focus();next?.setSelectionRange(query.length,query.length)})};root.querySelectorAll('[data-photo]').forEach(button=>{button.onclick=()=>{selected=button.dataset.photo;draw()};button.ondblclick=()=>shell.open('preview',`${LIBRARY}/${button.dataset.photo}`)});root.querySelector('[data-photo-favorite]')?.addEventListener('click',async()=>{state.favorites=state.favorites.includes(selected)?state.favorites.filter(x=>x!==selected):[...state.favorites,selected];await save();draw()});root.querySelectorAll('[data-photo-import]').forEach(button=>button.onclick=async()=>{const path=await dialog.prompt({title:i18n.t('importPhotos'),message:i18n.t('importPhotosCopy'),value:'/mnt/future/',validate:value=>value.startsWith('/')?'':i18n.t('invalidPath')});if(path){try{await system.copyTo(path,LIBRARY);await refresh()}catch(error){shell.toast(error.message,i18n.t('importFailed'))}}});root.querySelector('[data-new-album]')?.addEventListener('click',async()=>{const name=await dialog.prompt({title:i18n.t('newAlbum'),placeholder:i18n.t('albumName'),validate:value=>value?'':i18n.t('invalidName')});if(name){state.albums.push({id:`album-${crypto.randomUUID()}`,name,items:[]});await save();draw()}})};
    const off=kernel.bus.on('filesystem:changed',({path})=>{if(path===LIBRARY)refresh()});userdata.load('photos',{favorites:[],albums:[]}).then(value=>{state=value||state;refresh()});draw();return()=>off();
  }
};
