import {Terminal} from '@xterm/xterm';
import {FitAddon} from '@xterm/addon-fit';
import '@xterm/xterm/css/xterm.css';
import {icon} from '../../icons.js';

const leases=new Map();
export const terminalTheme={background:'#0f181f',foreground:'#d9e2e8',cursor:'#67c58b',cursorAccent:'#0f181f',selectionBackground:'#356b7eaa',black:'#111a22',red:'#ef7373',green:'#67c58b',yellow:'#e9bc64',blue:'#5aa7e8',magenta:'#b398ed',cyan:'#55c2c8',white:'#d9e2e8',brightBlack:'#607582',brightRed:'#ff8a8a',brightGreen:'#7cdda0',brightYellow:'#f4cb75',brightBlue:'#72b8f2',brightMagenta:'#c7adff',brightCyan:'#6dd8de',brightWhite:'#f5f8fa'};
export const terminalFontFamily=()=>getComputedStyle(document.documentElement).getPropertyValue('--font-mono').trim()||'monospace';
export const acquireTerminalPort=(system,owner)=>{const port=system.terminalPorts().find(candidate=>!leases.has(candidate));if(port)leases.set(port,owner);return port||null};
export const releaseTerminalPort=(port,owner)=>{if(leases.get(port)===owner)leases.delete(port)};

export const mountTerminalSession=(root,{kernel,system,i18n,clipboard,shell,openFullApp})=>{
  const owner=Symbol('activity-terminal'),port=acquireTerminalPort(system,owner);
  if(!port){root.innerHTML=`<div class="activity-terminal-unavailable"><span>${icon('terminal',28)}</span><strong>${i18n.t('terminalSessionLimit')}</strong><button data-terminal-open-full>${i18n.t('openInApp')}</button></div>`;root.querySelector('[data-terminal-open-full]').onclick=openFullApp;return()=>{}};
  root.innerHTML=`<div class="terminal-pro terminal-native activity-terminal-pro" data-terminal-theme="agnoster"><header><div class="terminal-tabs"><button class="selected"><i></i><span>${i18n.t('terminal')}</span></button></div><div class="terminal-session-meta"><i data-terminal-state-dot></i><span data-terminal-state></span></div><button data-terminal-open-full title="${i18n.t('openInApp')}">${icon('maximize',13)}</button></header><main class="terminal-native-host"><section class="terminal-native-pane" data-terminal-pane></section></main><footer><span class="terminal-connection"><i></i><b data-terminal-connection></b></span><span>UTF-8</span><span>ash</span></footer><menu class="terminal-context-menu" data-terminal-menu hidden><button data-terminal-copy>${i18n.t('copy')}</button><button data-terminal-paste>${i18n.t('paste')}</button></menu></div>`;
  const pane=root.querySelector('[data-terminal-pane]'),menu=root.querySelector('[data-terminal-menu]');let fitFrame=0,resizeTimer=0;
  const terminal=new Terminal({allowTransparency:true,convertEol:false,cursorBlink:true,cursorStyle:'bar',fontFamily:terminalFontFamily(),fontSize:12,fontWeight:'400',fontWeightBold:'700',letterSpacing:0,lineHeight:1.08,scrollback:10000,smoothScrollDuration:0,theme:terminalTheme});
  const fit=new FitAddon();terminal.loadAddon(fit);terminal.open(pane);
  const resize=()=>{cancelAnimationFrame(fitFrame);fitFrame=requestAnimationFrame(()=>{try{fit.fit()}catch{return}clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>system.resizeTerminal(port,terminal.cols,terminal.rows),150)})};
  const setStatus=()=>{const ready=system.ready;root.querySelector('[data-terminal-state]').textContent=i18n.t(ready?'terminalReady':'terminalWaiting');root.querySelector('[data-terminal-connection]').textContent=ready?'aeris@aeris':'Linux offline';root.querySelector('[data-terminal-state-dot]').classList.toggle('offline',!ready);root.querySelector('.terminal-connection i').classList.toggle('offline',!ready)};
  const copy=async()=>{const text=terminal.getSelection();if(text&&await clipboard.copyText(text))shell.toast(i18n.t('copiedToClipboard'));menu.hidden=true};
  const paste=()=>{if(clipboard.value)system.writeTerminal(clipboard.value,port);menu.hidden=true;terminal.focus()};
  const onData=terminal.onData(data=>system.writeTerminal(data,port)),offData=kernel.bus.on('terminal:data',detail=>{if(detail.port===port)terminal.write(detail.data)}),offReady=kernel.bus.on('guest:ready',()=>{setStatus();terminal.reset();const replay=system.terminalReplay(port);if(replay)terminal.write(replay);system.writeTerminal('\r',port);resize()}),offStatus=kernel.bus.on('machine:status',setStatus),offTheme=kernel.bus.on('theme:changed',()=>{terminal.options.fontFamily=terminalFontFamily();resize()});
  terminal.attachCustomKeyEventHandler(event=>{const key=event.key.toLowerCase(),copyKey=(event.metaKey||event.ctrlKey&&event.shiftKey)&&key==='c',pasteKey=(event.metaKey||event.ctrlKey&&event.shiftKey)&&key==='v';if(event.ctrlKey&&!event.metaKey&&!event.shiftKey&&key==='c'){if(event.type==='keydown')system.writeTerminal('\u0003',port);return false}if(copyKey&&terminal.hasSelection()){if(event.type==='keydown')copy();return false}if(pasteKey){if(event.type==='keydown')paste();return false}return true});
  pane.oncontextmenu=event=>{event.preventDefault();const bounds=root.getBoundingClientRect();menu.style.left=`${Math.max(8,Math.min(event.clientX-bounds.left,bounds.width-135))}px`;menu.style.top=`${Math.max(42,Math.min(event.clientY-bounds.top,bounds.height-90))}px`;menu.querySelector('[data-terminal-copy]').disabled=!terminal.hasSelection();menu.querySelector('[data-terminal-paste]').disabled=!clipboard.value;menu.hidden=false};
  menu.querySelector('[data-terminal-copy]').onclick=copy;menu.querySelector('[data-terminal-paste]').onclick=paste;root.querySelector('[data-terminal-open-full]').onclick=openFullApp;root.onpointerdown=event=>{if(!event.target.closest('[data-terminal-menu]'))menu.hidden=true};
  const observer=new ResizeObserver(resize);observer.observe(pane);const replay=system.terminalReplay(port);if(replay)terminal.write(replay);setStatus();requestAnimationFrame(()=>{resize();terminal.focus();if(system.ready)system.writeTerminal('\r',port)});
  return()=>{cancelAnimationFrame(fitFrame);clearTimeout(resizeTimer);observer.disconnect();onData.dispose();offData();offReady();offStatus();offTheme();terminal.dispose();releaseTerminalPort(port,owner);return system.resetTerminal(port)};
};
